### ISSUE TITLE
Error escaping message unpacking

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1062]
### What is wrong?

```
   ERROR  09-05 09:51:49               asyncio  Exception in callback UDPTransport._on_read_ready
handle: <Handle UDPTransport._on_read_ready>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 69, in uvloop.loop.Handle._run
  File "uvloop/handles/udp.pyx", line 64, in uvloop.loop.UDPTransport._on_read_ready
  File "/home/ubuntu/trinity/p2p/discovery.py", line 448, in datagram_received
    self.receive(address, cast(bytes, data))
  File "/home/ubuntu/trinity/p2p/discovery.py", line 463, in receive
    remote_pubkey, cmd_id, payload, message_hash = _unpack_v4(message)
  File "/home/ubuntu/trinity/p2p/discovery.py", line 1261, in _unpack_v4
    cmd = CMD_ID_MAP[cmd_id]
KeyError: 9
```

### How can it be fixed

:man_shrugging:

**Comment by cburgdorf** [comment]
This got fixed with #1063
