### ISSUE TITLE
Beam Sync from checkpoint failure

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1065]
* Trinity version: e8e6f59f
* OS: linux

### What is wrong?

I got a `KeyError` when trying to sync from a checkpoint with an empty database.
I launched with:
> trinity --disable-upnp --sync-mode=beam --data-dir /tmp/beamtest --port 33333 --disable-rpc --enable-experimental-eth1-peer-tracking --max-peers=10 --beam-from-checkpoint="eth://block/byhash/0x5750da03aa15ab40c4c04eee86bb39798591c961813ebffa052907fb39ac448a?score=11,780,376,910,758,050,534,442"

The error was:
```
    INFO  09-05 11:38:59       BeamSyncService  Starting beam-sync; current head: <BlockHeader #0 d4e56740>, using checkpoint: <Checkpoint block hash=#5750..448a score=11780376910758050534442>
 WARNING  09-05 11:39:01           ETHPeerPool  PeerCandidateRequest timed out to backend <trinity.plugins.builtin.network_db.eth1_peer_db.tracker.EventBusEth1PeerTracker object at 0x7f8d3ae05198>
    INFO  09-05 11:39:01     HeaderOnlyPersist  Caught up to skeleton peer. Switching to beam mode at <BlockHeader #8491721 e502b251>
    INFO  09-05 11:39:01            BeamSyncer  Downloading 8 block bodies for uncle validation, before <BlockHeader #8491721 e502b251>
   ERROR  09-05 11:39:01            BeamSyncer  Unexpected error in <trinity.sync.beam.chain.BeamSyncer object at 0x7f8d462cf630>, exiting
Traceback (most recent call last):
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/eth/db/header.py", line 122, in _get_block_header_by_hash
    header_rlp = db[block_hash]
  File "/home/jcarver/code/trinity/trinity/db/manager.py", line 376, in __getitem__
    raise KeyError(key)
KeyError: b'\xdaq\x85E\x05\xc7\x93\x06\xd4\xfb\xf6\x0f\x95\xbd\xd0]\x9a\x1b\x8d\x16!;\xea\xd2\x85\xab,!o=]\x90'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jcarver/code/trinity/p2p/service.py", line 121, in run
    await self._run()
  File "/home/jcarver/code/trinity/trinity/sync/beam/chain.py", line 205, in _run
    await self._download_blocks(final_headers[0])
  File "/home/jcarver/code/trinity/trinity/sync/beam/chain.py", line 238, in _download_blocks
    in self._get_ancestors(parents_needed, header=before_header)
  File "/home/jcarver/code/trinity/trinity/sync/beam/chain.py", line 237, in <listcomp>
    header async for header
  File "/home/jcarver/code/trinity/trinity/sync/beam/chain.py", line 276, in _get_ancestors
    parent = await self._chain.coro_get_block_header_by_hash(header.parent_hash)
  File "/home/jcarver/code/trinity/trinity/_utils/async_dispatch.py", line 23, in wrapper
    *args
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/eth/chains/base.py", line 300, in get_block_header_by_hash
    return self.chaindb.get_block_header_by_hash(block_hash)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/eth/db/header.py", line 111, in get_block_header_by_hash
    return self._get_block_header_by_hash(self.db, block_hash)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/eth/db/header.py", line 125, in _get_block_header_by_hash
    encode_hex(block_hash)))
eth.exceptions.HeaderNotFound: No header with hash 0xda71854505c79306d4fbf60f95bdd05d9a1b8d16213bead285ab2c216f3d5d90 found
```

### How can it be fixed

At first glance, it looks like we crash when accessing headers that come before the checkpoint. I think we might be collecting one more header than we used to, since the last time @cburgdorf  checked it out. Not sure why testing would have missed it.

**Comment by cburgdorf** [comment]
I'm going to look into this now

**Comment by cburgdorf** [comment]
I was able to reproduce this.

>I used a very recent score (probably too recent, now that I think about it!). If that's the problem

Yes, it's that. AFAICT the reason for this is that when beam sync imports new blocks it looks back `MAX_UNCLE_DEPTH` (currently set to `6`.

>If that's the problem, then the solution is probably to print a log that the chosen header is too recent, and wait for newer headers to come in from the peers.

Alternatively, we could auto-adjust the checkpoint by following it upwards for `n` blocks and then using that as the checkpoint. Do you see issues with that?

**Comment by carver** [comment]
> Alternatively, we could auto-adjust the checkpoint by following it upwards for `n` blocks and then using that as the checkpoint. Do you see issues with that?

First thoughts:
- if you pick a recent checkpoint and we follow it back, the checkpoint might not be on the canonical chain anymore, so it's a little weird that you're checkpoint won't be the start of your chain (maybe this is just a naming problem: that it's not really a checkpoint, just a score hint)
- I like that it's (probably) the fastest way to get beam sync started
- not sure when we'd detect it: waiting until we reach the tip seems too late/messy logically, but using timing might be flaky
- On how to use timing to determine an "old enough" checkpoint/hinter header: I guess it's very fast to download headers, so we can just bump the header back a *lot* more than the 6 headers we need. (Like aim for ~150 headers back from the current time, which still fits in a single request)
- It would still be possible to trigger this crash if we use this ^ timing, and the node you are connected to just happens to be very behind the tip. So probably worth just making slightly clearer error message (probably fine to just error out and implicitly ask the user to restart, for now)

So... I guess I'm good with it, as long as there's a big margin for error, and an improved error message when the bug still triggers :+1:

**Comment by cburgdorf** [comment]
>if you pick a recent checkpoint and we follow it back, the checkpoint might not be on the canonical chain anymore

Mmh, you are right. I think it would be terrible if someone chooses a checkpoint `x` and then ends up on the wrong fork just because we silently moved the checkpoint behind the scenes. I'm inclined to say it's not worth it. After all, the user gave us a very specific checkpoint to start from so we better respect that :)

So, I think I rather take a stab on the solution you originally proposed which I understand as:

1. Detect that the header is too recent (Checkpoint header is only `n` blocks away from what we currently know what the tip might be)
2. Print a message, offering the user to either hang on or restart with an older checkpoint
3. If the user decides to wait, just extend the prerequisite fulfillment call by waiting `estimated_duration` seconds and then re-validating that the tip is now far enough from the checkpoint.
