### ISSUE TITLE
Peer discovery halts, just a few minutes in

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1067]
* Trinity version: master

### What is wrong?

Discovery hums along and just stops after a few minutes, with nothing obvious indicating a problem in the debug logs. Only that this message stops showing up:

```
Initiating 1 peer connection attempts with 9 open peer slots
```

### How can it be fixed

:man_shrugging: I'm investigating, because it's blocking my live beam sync testing.

**Comment by carver** [comment]
This seems to be a relatively recent change.

**Comment by pipermerriam** [comment]
I think that this needs a timeout, but I'm not convinced it's actually fixing the right problem...

https://github.com/ethereum/trinity/blob/248efac0cc6daf43e49e5739a80f11737dd06161/p2p/peer_pool.py#L349

Adding at timeout to that appears to fix the issue though.

**Comment by carver** [comment]
Yeah, I came to the same conclusion locally, but then my screen blows up with:
```
   ERROR  09-05 15:25:55               asyncio  Task exception was never retrieved
future: <Task finished coro=<BasePeerFactory.handshake() done, defined at /home/jcarver/code/trinity/p2p/peer.py:492> exception=PeerConnectionLost() created at /home/jcarver/code/trinity/venv/lib/python3.6/site-packages/cancel_token/token.py:126>
source_traceback: Object created at (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 118, in _main
    return self._bootstrap()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jcarver/code/trinity/trinity/extensibility/plugin.py", line 222, in _prepare_spawn
    self._spawn_start()
  File "/home/jcarver/code/trinity/trinity/extensibility/asyncio.py", line 26, in _spawn_start
    self._loop.run_forever()
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 126, in send
    return self.gen.send(value)
  File "/home/jcarver/code/trinity/p2p/peer_pool.py", line 439, in connect_to_node
    peer = await self.connect(node)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/jcarver/code/trinity/p2p/peer_pool.py", line 354, in connect
    timeout=5,
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/jcarver/code/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/jcarver/code/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/cancel_token/token.py", line 126, in cancellable_wait
    futures = [asyncio.ensure_future(a, loop=self.loop) for a in awaitables + (self.wait(),)]
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/cancel_token/token.py", line 126, in <listcomp>
    futures = [asyncio.ensure_future(a, loop=self.loop) for a in awaitables + (self.wait(),)]
Traceback (most recent call last):
  File "/home/jcarver/code/trinity/p2p/transport.py", line 240, in read
    timeout=CONN_IDLE_TIMEOUT,
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/cancel_token/token.py", line 153, in cancellable_wait
    return done.pop().result()
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 126, in send
    return self.gen.send(value)
  File "/usr/lib/python3.6/asyncio/streams.py", line 672, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 32 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 126, in send
    return self.gen.send(value)
  File "/home/jcarver/code/trinity/p2p/peer.py", line 504, in handshake
    token=self.cancel_token
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/jcarver/code/trinity/p2p/handshake.py", line 306, in dial_out
    token=token,
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/jcarver/code/trinity/p2p/handshake.py", line 272, in negotiate_protocol_handshakes
    in zip(selected_handshakers, selected_protocols)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/home/jcarver/code/trinity/p2p/multiplexer.py", line 343, in multiplex
    fut.result()
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 126, in send
    return self.gen.send(value)
  File "/home/jcarver/code/trinity/p2p/multiplexer.py", line 365, in _do_multiplexing
    async for protocol, cmd, msg in msg_stream:
  File "/home/jcarver/code/trinity/p2p/cancellable.py", line 66, in wait_iter
    timeout=timeout,
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/jcarver/code/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/jcarver/code/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/cancel_token/token.py", line 153, in cancellable_wait
    return done.pop().result()
  File "/home/jcarver/code/trinity/p2p/multiplexer.py", line 59, in stream_transport_messages
    raw_msg = await transport.recv(token)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/jcarver/code/trinity/p2p/transport.py", line 265, in recv
    header_data = await self.read(HEADER_LEN + MAC_LEN, token)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/jcarver/code/trinity/p2p/transport.py", line 243, in read
    raise PeerConnectionLost from err
p2p.exceptions.PeerConnectionLost
```

Which confuses me. I think it's saying that the cancel token doesn't cancel the pending coro correctly, but I can't tell what's wrong by inspecting the cancel token code.

**Comment by pipermerriam** [comment]
I hate cancel tokens.........

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by cburgdorf** [comment]
@carver This looks a lot like the error I had reported in https://github.com/ethereum/trinity/issues/984

**Comment by pipermerriam** [comment]
Not the same as #984 

The exception path is the same but #984 is now handled in the `Connection` object's error handling.  This error rises from the same origin but it isn't yet housed in a `Connection` since it is part of the handshake.  This is something stranger, likely due to the `CancelToken` library being wrong about a few things...
