### ISSUE TITLE
Beam sync went stale after error

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1083]
### What is wrong?

This error came up during beam sync

```python
   ERROR  09-09 11:44:41  ETHHeaderChainSyncer  Unexpected error in <trinity.protocol.eth.sync.ETHHeaderChainSyncer object at 0x7fc3dfd1beb8>, exiting
Traceback (most recent call last):
  File "/home/ubuntu/trinity/p2p/service.py", line 118, in run
  File "/home/ubuntu/trinity/trinity/sync/common/headers.py", line 866, in _run
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 43, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/ubuntu/trinity/venv/lib/python3.6/site-packages/cancel_token/token.py", line 178, in cancellable_wait
    return done.pop().result()
  File "/home/ubuntu/trinity/trinity/sync/common/headers.py", line 880, in _build_skeleton
  File "/home/ubuntu/trinity/trinity/sync/common/headers.py", line 961, in _full_skeleton_sync
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 43, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/ubuntu/trinity/venv/lib/python3.6/site-packages/cancel_token/token.py", line 178, in cancellable_wait
    return done.pop().result()
  File "/home/ubuntu/trinity/trinity/sync/common/headers.py", line 596, in schedule_segment
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 43, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/ubuntu/trinity/venv/lib/python3.6/site-packages/cancel_token/token.py", line 178, in cancellable_wait
    return done.pop().result()
  File "/home/ubuntu/trinity/trinity/_utils/datastructures.py", line 160, in add
eth_utils.exceptions.ValidationError: Duplicate tasks detected: {(<eth.rlp.headers.BlockHeader object at 0x7fc39a1aee80>, 192, ETHPeer <Node(0xd64684e7a34c4f0aaaa07e1f6143ec91610b99b120b441387356def326890b40867a4aa4384af7fe4088858c161a05efb61499c35d194b4f46c4a0cac82f2ee2@35.193.221.102:40780)>)} are already present in the queue

```

After that, beam sync went stale but the node kept running.

### How can it be fixed

:man_shrugging:

**Comment by carver** [comment]
Do you have any more logs from before this? I'm wondering if there might be some hints about something that went wrong before this point.

**Comment by carver** [comment]
I'm guessing that this might have been some skeleton before this.  It's possible to capture this exception and continue on. It wouldn't be terrible, but it would be good to know why it's happening, so it's worthy of a warning log, I think.

**Comment by cburgdorf** [comment]
Sure, here's the debug log with 2000 lines before and 100 lines after the crash. Let me know if you need more/other logs.

[bug.log](https://github.com/ethereum/trinity/files/3593998/bug.log)

**Comment by carver** [comment]
Yup, looks like the skeleton sync cancelled then restarted and happened to add the same task in the meat filler. It seems like what we might end up doing is just downgrading the warning to a debug, so that we only notice it if it's happening a lot. It should be a very rare occurrence.
