### ISSUE TITLE
Sync from checkpoint may fail when not starting from clean db

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1106]
### What is wrong?

When beam sync starts from a  checkpoint it may fail when not started from a fresh db.

```
Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/peer_pool.py", line 360, in connect
    timeout=HANDSHAKE_TIMEOUT,
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/cancellable.py", line 43, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/cancel_token/token.py", line 178, in cancellable_wait
    return done.pop().result()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/peer.py", line 501, in handshake
    handshakers = await self.get_handshakers()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/protocol/eth/peer.py", line 166, in get_handshakers
    head = await wait(headerdb.coro_get_canonical_head())
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/cancel_token/token.py", line 178, in cancellable_wait
    return done.pop().result()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/_utils/async_dispatch.py", line 23, in wrapper
    *args
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/eth/db/header.py", line 97, in get_canonical_head
    return self._get_canonical_head(self.db)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/eth/db/header.py", line 102, in _get_canonical_head
    canonical_head_hash = db[SchemaV1.make_canonical_head_hash_lookup_key()]
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/db/manager.py", line 376, in __getitem__
    self._socket.sendall(GET.value + len(key).to_bytes(LEN_BYTES, 'little') + key)
BrokenPipeError: [Errno 32] Broken pipe
```

### How can it be fixed

Haven't investigated it yet.

**Comment by carver** [comment]
Hm, what could those two things possibly have to do with each other?

I ran into this problem too. (Nothing but broken pipes on every attempted handshake)

It *did* happen during a checkpoint sync on a non-empty database, but I still think it's a coincidence.

**Comment by cburgdorf** [comment]
Could it be that Trinity starts thinking it it's current head is on block `x` (whatever the head was on the last run) but then we reset the head midway as we resolve the checkpoint which causes things within the PeerPool (which still thinks we are on `x`) to fall apart?

**Comment by carver** [comment]
Maybe something in that vicinity, but whatever it is seems to be destroying the connection between the peer pool process and the database process. In other words, I think these are the symptom, not the cause:
```
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/eth/db/header.py", line 102, in _get_canonical_head
    canonical_head_hash = db[SchemaV1.make_canonical_head_hash_lookup_key()]
  File "/home/jcarver/code/trinity/trinity/db/manager.py", line 376, in __getitem__
    self._socket.sendall(GET.value + len(key).to_bytes(LEN_BYTES, 'little') + key)
BrokenPipeError: [Errno 32] Broken pipe
```
