### ISSUE TITLE
Beacon Validator crashes during interop testnets

### ISSUE THREAD

**Issue by lithp** [ethereum/trinity#1110]
From the `interop` branch. This happens within ~14 epochs in testnets with lighthouse+trinity+nimbus, and happens after about 2 hours (a few hundred epochs) in a testnet with trinity + lighthouse.

```
ESC[1mESC[33m WARNING  09-09 21:50:10             Validator  Task <coroutine object Validator.handle_slot_tick at 0x7f21ba95a7a0> finished unexpectedly: ValidationError("Attestation at slot 98 must be within 8 slots (1 epoch) of the state's slot 107")ESC[0m
   DEBUG  09-09 21:50:10             Validator  Task failure traceback
Traceback (most recent call last):
  File "/home/brian/ef/trinity/p2p/service.py", line 159, in _run_task_wrapper
    await awaitable
  File "/home/brian/ef/trinity/p2p/service.py", line 180, in _run_daemon_task_wrapper
    await awaitable
  File "/home/brian/ef/trinity/trinity/plugins/eth2/beacon/validator.py", line 135, in handle_slot_tick
    await self.handle_first_tick(event.slot)
  File "/home/brian/ef/trinity/trinity/plugins/eth2/beacon/validator.py", line 193, in handle_first_tick
    head_block=head,
  File "/home/brian/ef/trinity/trinity/plugins/eth2/beacon/validator.py", line 222, in propose_block
    attestations=ready_attestations,
  File "/home/brian/ef/trinity/trinity/plugins/eth2/beacon/validator.py", line 252, in _make_proposing_block
    check_proposer_index=False,
  File "/home/brian/ef/trinity/eth2/beacon/tools/builder/proposer.py", line 87, in create_block_on_state
    block, state, check_proposer_signature=False
  File "/home/brian/ef/trinity/eth2/beacon/state_machines/base.py", line 138, in import_block
    state, block=block, check_proposer_signature=check_proposer_signature
  File "/home/brian/ef/trinity/eth2/beacon/state_machines/forks/serenity/state_transitions.py", line 33, in apply_state_transition
    state = process_block(state, block, self.config, check_proposer_signature)
  File "/home/brian/ef/trinity/eth2/beacon/state_machines/forks/serenity/block_processing.py", line 113, in process_block
    state = process_operations(state, block, config)
  File "/home/brian/ef/trinity/eth2/beacon/state_machines/forks/serenity/operation_processing.py", line 200, in process_operations
    state = process_attestations(state, block, config)
  File "/home/brian/ef/trinity/eth2/beacon/state_machines/forks/serenity/operation_processing.py", line 105, in process_attestations
    validate_attestation(state, attestation, config)
  File "/home/brian/ef/trinity/eth2/beacon/state_machines/forks/serenity/block_validation.py", line 430, in validate_attestation
    _validate_attestation_data(state, attestation.data, config)
  File "/home/brian/ef/trinity/eth2/beacon/state_machines/forks/serenity/block_validation.py", line 392, in _validate_attestation_data
    config.MIN_ATTESTATION_INCLUSION_DELAY,
  File "/home/brian/ef/trinity/eth2/beacon/state_machines/forks/serenity/block_validation.py", line 319, in validate_attestation_slot
    f"Attestation at slot {attestation_slot} must be within {slots_per_epoch}"
eth_utils.exceptions.ValidationError: Attestation at slot 98 must be within 8 slots (1 epoch) of the state's slot 107
```

**Comment by lithp** [comment]
Here was the exception from a recent run w/ triniy+lighthouse:

```
WARNING  2019-09-10 20:05:10,114             Validator  Task <coroutine object Validator.handle_slot_tick at 0x7fad001109e0> finished unexpectedly: ValidationError("Attestation at slot 3556 must be within 8 slots (1 epoch) of the state's slot 3565")
```

**Comment by ralexstokes** [comment]
This looks like an issue b/t synchronizing our validator, the attestation pool and our chain instance.

Re-working our code here so that the validator gets an immutable version of the world before taking action will fix it :)
