### ISSUE TITLE
HeaderNotFound when restarting Beam Sync

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1118]
```
   DEBUG  09-11 16:47:03     HeaderOnlyPersist  Task failure traceback
Traceback (most recent call last):
  File "/home/jcarver/code/trinity/trinity/db/manager.py", line 488, in __getitem__
    value = self._track_diff[key]
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/eth/db/diff.py", line 80, in __getitem__
    raise DiffMissingError(key, result)  # type: ignore # ignore over cast for perf reasons
eth.db.diff.DiffMissingError: (b'block-hash-to-score:-62\x9f\x1b\x14\xa7F\x06\xc0\x8d\x94\x8e\x14_\x87\xe3a\xc4_[p\xd7\xf4n\x94\xea\xc3v\xe1m\x03', 'Key is missing because it was never inserted')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/eth/db/header.py", line 134, in _get_score
    encoded_score = db[SchemaV1.make_block_hash_to_score_lookup_key(block_hash)]
  File "/home/jcarver/code/trinity/trinity/db/manager.py", line 493, in __getitem__
    return self._db[key]
  File "/home/jcarver/code/trinity/trinity/db/manager.py", line 384, in __getitem__
    raise KeyError(key)
KeyError: b'block-hash-to-score:-62\x9f\x1b\x14\xa7F\x06\xc0\x8d\x94\x8e\x14_\x87\xe3a\xc4_[p\xd7\xf4n\x94\xea\xc3v\xe1m\x03'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jcarver/code/trinity/p2p/service.py", line 159, in _run_task_wrapper
    await awaitable
  File "/home/jcarver/code/trinity/p2p/service.py", line 178, in _run_daemon_task_wrapper
    await awaitable
  File "/home/jcarver/code/trinity/trinity/sync/beam/chain.py", line 410, in _persist_headers
    exited = await self._exit_if_checkpoint(headers)
  File "/home/jcarver/code/trinity/trinity/sync/beam/chain.py", line 484, in _exit_if_checkpoint
    self._db.coro_persist_header_chain(persist_headers)
  File "/home/jcarver/code/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/jcarver/code/trinity/p2p/cancellable.py", line 43, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/cancel_token/token.py", line 178, in cancellable_wait
    return done.pop().result()
  File "/home/jcarver/code/trinity/trinity/_utils/async_dispatch.py", line 23, in wrapper
    *args
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/eth/db/header.py", line 167, in persist_header_chain
    return self._persist_header_chain(db, headers, genesis_parent_hash)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/eth/db/header.py", line 231, in _persist_header_chain
    score = cls._get_score(db, first_header.parent_hash)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/eth/db/header.py", line 137, in _get_score
    encode_hex(block_hash)))
eth.exceptions.HeaderNotFound: No header with hash 0x2d36329f1b14a74606c08d948e145f87e361c45f5b70d7f46e94eac376e16d03 found
```

_Originally posted by @carver in https://github.com/ethereum/trinity/pull/1116/review_comment/create_

**Comment by carver** [comment]
First guess from scanning it:
- run beam sync
- preview blocks
  - store header rlp
  - preview execution might get ancestor block hashes, which are retrievable using ^
- close out of beam sync before the previewed headers are imported
- ...
- start beam sync again
- header syncer skips over the headers that are persisted, thinking they've already been imported
- the next header import tries to get the score of the parent
- that score isn't available, because the header was never persisted
- `HeaderNotFound` crash

I can't come up with a good reason why I haven't seen this before, though. It seems like the kind of thing that would happen often, if I understand the series of steps above correctly.

**Comment by carver** [comment]
Nope, that can't be it. There's already a fix to make sure we don't skip headers that have no score:
https://github.com/ethereum/trinity/blob/9e9ed906e7e09545acac97795854dc0b4acdcd4a/trinity/sync/common/headers.py#L268-L284

**Comment by carver** [comment]
Ah, this is probably it:
https://github.com/ethereum/trinity/blob/9e9ed906e7e09545acac97795854dc0b4acdcd4a/trinity/sync/common/headers.py#L259-L262

Looks like that should use `_should_skip_header()` to make sure the header is really already imported.
