### ISSUE TITLE
Broken logging statment

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#1126]
### What is wrong?

--- Logging error ---
Traceback (most recent call last):
  File "/home/piper/projects/trinity/trinity/sync/common/headers.py", line 453, in _fetch_headers_from
    reverse=False,
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 43, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/cancel_token/token.py", line 178, in cancellable_wait
    return done.pop().result()
  File "/home/piper/projects/trinity/trinity/protocol/eth/exchanges.py", line 84, in __call__
    timeout,
  File "/home/piper/projects/trinity/trinity/protocol/common/exchanges.py", line 46, in get_result
    timeout,
  File "/home/piper/projects/trinity/trinity/protocol/common/managers.py", line 83, in get_result
    async for payload in stream.payload_candidates(request, tracker, timeout=timeout):
  File "/home/piper/projects/trinity/trinity/protocol/common/candidate_stream.py", line 99, in payload_candidates
    yield await self._get_payload(timeout_remaining)
  File "/home/piper/projects/trinity/trinity/protocol/common/candidate_stream.py", line 146, in _get_payload
    payload = await self.wait(future, timeout=timeout)
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 43, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/cancel_token/token.py", line 168, in cancellable_wait
    raise asyncio.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/logging/handlers.py", line 1395, in emit
    self.enqueue(self.prepare(record))
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/logging/handlers.py", line 1382, in prepare
    self.format(record)
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not NoneType
Call stack:
  File "<string>", line 1, in <module>
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/spawn.py", line 118, in _main
    return self._bootstrap()
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/piper/projects/trinity/trinity/extensibility/plugin.py", line 222, in _prepare_spawn
    self._spawn_start()
  File "/home/piper/projects/trinity/trinity/extensibility/asyncio.py", line 26, in _spawn_start
    self._loop.run_forever()
  File "/home/piper/projects/trinity/trinity/sync/common/headers.py", line 464, in _fetch_headers_from
    self.logger.debug("Timeout waiting for headers (skip=%d) from %s", skip, peer)
Message: 'Timeout waiting for headers (skip=%d) from %s'
Arguments: (None, ETHPeer Session(<Node(0x1ed6ea0494b8a380cdac88126f30df3151ec458790ba1a6a3713627d8a9790cde87c5070c4a40b9b80ee7b3177c46de5ff24cddbd3ecb070ca35f529f697b25e@164.68.105.24:30303)> UUID('e5f3b2c3-112d-495c-9ba2-06d17fd3f2fc')))
    INFO  09-13 06:55:08           ETHPeerPool  Connected peers: 0 inbound, 25 outbound
```

### How can it be fixed

Fis the string formatting so that it's doesn't raise an error.

**Comment by hjlee9182** [comment]
What file that error was occured?

**Comment by l0rb** [comment]
The following commit should already have fixed that:
https://github.com/ethereum/trinity/commit/7b8643efab9498b120603af4f5b7c7d5041a4e65
