### ISSUE TITLE
Malformed disconnect message

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#1128]
### What is wrong?

```
 WARNING  09-13 15:39:27            Disconnect  Malformed Disconnect message: b"\x01\xf8y\x05\xa7odash/v1.0.0-stable/linux-amd64/go1.8.3\xcc\xc5\x83eth?\xc5\x83eth>\x80\xb8@\xf7\xb0\xea\xf08\x8dx\x8f\x07\xf6\xcd\xa8\x92G@\x9b\xa1\x9cZ\x8c\x83\xd4>p{\xec\xb7\x8f\xb0I\n\xb2\xba@\x07\xc2IB\r\xc9v\xed\x7f\xd7\x97\x7f\xf7\xd6e\xbb\xdc\xa2'\xde8\xa1\x14\x82\t\xf3\xa2\xab\xaf\xc4"
   ERROR  09-13 15:39:27            FullServer  Unexpected error handling handshake
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/p2p/p2p_proto.py", line 58, in decode
    raw_decoded = cast(Dict[str, int], super().decode(data))
  File "/usr/local/lib/python3.7/dist-packages/p2p/protocol.py", line 100, in decode
    return self.decode_payload(encoded_payload)
  File "/usr/local/lib/python3.7/dist-packages/p2p/protocol.py", line 80, in decode_payload
    data = rlp.decode(rlp_data, sedes=decoder, recursive_cache=True)
  File "/usr/local/lib/python3.7/dist-packages/rlp/codec.py", line 237, in decode
    obj = sedes.deserialize(item, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/rlp/sedes/lists.py", line 89, in deserialize
    serial)
rlp.exceptions.ListDeserializationError: Deserializing list length (5) does not match sedes (1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/trinity/server.py", line 155, in receive_handshake
    await self._receive_handshake(reader, writer)
  File "/usr/local/lib/python3.7/dist-packages/trinity/server.py", line 181, in _receive_handshake
    token=self.cancel_token,
  File "/usr/local/lib/python3.7/dist-packages/p2p/handshake.py", line 343, in receive_dial_in
    token=token,
  File "/usr/local/lib/python3.7/dist-packages/p2p/handshake.py", line 216, in negotiate_protocol_handshakes
    token,
  File "/usr/local/lib/python3.7/dist-packages/p2p/handshake.py", line 125, in _do_p2p_handshake
    async for _, cmd, msg in stream_transport_messages(transport, base_protocol, token=token):
  File "/usr/local/lib/python3.7/dist-packages/p2p/multiplexer.py", line 84, in stream_transport_messages
    msg = cmd.decode(raw_msg)
  File "/usr/local/lib/python3.7/dist-packages/p2p/p2p_proto.py", line 61, in decode
    raise MalformedMessage(f"Malformed Disconnect message: {data}")
p2p.exceptions.MalformedMessage: Malformed Disconnect message: b"\x01\xf8y\x05\xa7odash/v1.0.0-stable/linux-amd64/go1.8.3\xcc\xc5\x83eth?\xc5\x83eth>\x80\xb8@\xf7\xb0\xea\xf08\x8dx\x8f\x07\xf6\xcd\xa8\x92G@\x9b\xa1\x9cZ\x8c\x83\xd4>p{\xec\xb7\x8f\xb0I\n\xb2\xba@\x07\xc2IB\r\xc9v\xed\x7f\xd7\x97\x7f\xf7\xd6e\xbb\xdc\xa2'\xde8\xa1\x14\x82\t\xf3\xa2\xab\xaf\xc4"
```

I've seen this exception while running beam sync at least once.

### How can it be fixed

Add handling for it but not exactly sure where..

**Comment by carver** [comment]
I *think* this might be the same issue, but with the new peer transports:

```
   ERROR  2019-11-21 14:27:13,570            FullServer  Unexpected error handling handshake with ('106.38.3.253', 46690)
Traceback (most recent call last):
  File "/home/jcarver/code/trinity/p2p/transport.py", line 315, in recv
    header_data = _decode_header_data(padded_header[3:])
  File "/home/jcarver/code/trinity/p2p/transport.py", line 62, in _decode_header_data
    header_data = rlp.decode(data, sedes=HEADER_DATA_SEDES, strict=False)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/rlp/codec.py", line 237, in decode
    obj = sedes.deserialize(item, **kwargs)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/rlp/sedes/lists.py", line 89, in deserialize
    serial)
rlp.exceptions.ListDeserializationError: Deserializing list length (1) does not match sedes (2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jcarver/code/trinity/trinity/server.py", line 148, in receive_handshake
    await self._receive_handshake(reader, writer)
  File "/home/jcarver/code/trinity/trinity/server.py", line 176, in _receive_handshake
    token=self.cancel_token,
  File "/home/jcarver/code/trinity/p2p/handshake.py", line 349, in receive_dial_in
    token=token,
  File "/home/jcarver/code/trinity/p2p/handshake.py", line 222, in negotiate_protocol_handshakes
    token,
  File "/home/jcarver/code/trinity/p2p/handshake.py", line 129, in _do_p2p_handshake
    async for _, cmd in stream_transport_messages(transport, base_protocol, token=token):
  File "/home/jcarver/code/trinity/p2p/multiplexer.py", line 60, in stream_transport_messages
    msg = await transport.recv(token)
  File "/home/jcarver/code/trinity/p2p/transport.py", line 317, in recv
    raise MalformedMessage from err
p2p.exceptions.MalformedMessage
```

**Comment by pipermerriam** [comment]
Probably nice to update that code path to include the raw `data` for the header that failed to decode so that we can see what it is when this happens.

**Comment by gsalgado** [comment]
Looks like this is now manifesting as an error during handshake: #2052
