### ISSUE TITLE
MalformedMessage escaping beam sync

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1153]
### What is wrong?

```python
ERROR  09-16 13:13:18            Connection  Unexpected error in <p2p.connection.Connection object at 0x7fc210435a10>, exiting
Traceback (most recent call last):
  File "/usr/src/app/trinity/p2p/transport.py", line 275, in recv
    header = self._decrypt_header(header_data)
  File "/usr/src/app/trinity/p2p/transport.py", line 357, in _decrypt_header
    f'Invalid header mac: expected {expected_header_mac}, got {header_mac}'
p2p.exceptions.DecryptionError: Invalid header mac: expected b'7\xb2\x04\x0f\x92!\xb9t`\x88\xe4X\xa8vU/', got b'!\x9b_\x1a;\xf5\xec\xce\x9e\xab\x82\xea\xaf\xdf\xe4\x8f'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/trinity/p2p/connection.py", line 98, in _run
    await self.cancellation()
  File "/usr/local/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/usr/src/app/trinity/p2p/multiplexer.py", line 336, in multiplex
    await asyncio.wait_for(fut, timeout=1)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/src/app/trinity/p2p/multiplexer.py", line 370, in _do_multiplexing
    async for protocol, cmd, msg in msg_stream:
  File "/usr/src/app/trinity/p2p/cancellable.py", line 67, in wait_iter
    timeout=timeout,
  File "/usr/src/app/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/usr/src/app/trinity/p2p/cancellable.py", line 43, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/cancel_token/token.py", line 178, in cancellable_wait
    return done.pop().result()
  File "/usr/src/app/trinity/p2p/multiplexer.py", line 60, in stream_transport_messages
    raw_msg = await transport.recv(token)
  File "/usr/src/app/trinity/p2p/transport.py", line 281, in recv
    raise MalformedMessage from err
p2p.exceptions.MalformedMessage

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/trinity/p2p/service.py", line 118, in run
    await self._run()
  File "/usr/src/app/trinity/p2p/connection.py", line 107, in _run
    self.get_base_protocol().send_disconnect(DisconnectReason.bad_protocol)
  File "/usr/src/app/trinity/p2p/p2p_proto.py", line 127, in send_disconnect
    self.transport.send(header, body)
  File "/usr/src/app/trinity/p2p/transport.py", line 305, in send
    "Attempted to send msg with cmd id %d to disconnected peer %s", cmd_id, self)
p2p.exceptions.PeerConnectionLost: ('Attempted to send msg with cmd id %d to disconnected peer %s', 1, <p2p.transport.Transport object at 0x7fc2103076d0>)

```

### How can it be fixed

:man_shrugging:

**Comment by cburgdorf** [comment]
@pipermerriam I guess the idea is that `MalformedMessage` would be caught here:

https://github.com/ethereum/trinity/blob/a873f330753de18b5596768df644d708db61f919/p2p/connection.py#L94-L110

But it looks like this didn't happen. I wonder if that's because it ends up being raised int this background task?

https://github.com/ethereum/trinity/blob/a873f330753de18b5596768df644d708db61f919/p2p/multiplexer.py#L326

**Comment by pipermerriam** [comment]
> But it looks like this didn't happen. I wonder if that's because it ends up being raised int this background task?

No, you can see that we're looking at 3 nested exceptions.  The `MalformedMessage` is properly caught, but then the next line that tries to send the `Disconnect` message throws an exception.  Ideal situation would be a more robust way to send that disconnect such that if the connection is already closed it just does nothing..

**Comment by cburgdorf** [comment]
Oh! Yes, I see, thanks for explaining it.
