### ISSUE TITLE
BrokenPipe bubbling out of database manager on shutdown.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#1188]
### What is wrong?
Our DBManager process still runs on the same process group as the main process, so when there's a Ctrl-C in the terminal that process is likely to terminate before we send a SIGINT to our components' processes, leading to BrokenPipeErrors like below

```
   ERROR  2019-09-19 16:07:34,941        BeamDownloader  Unexpected error in <trinity.sync.beam.state.BeamDownloader object at 0x7f4ae1aea4e0>, exiting
Traceback (most recent call last):
  File "/home/piper/projects/trinity/p2p/service.py", line 118, in run
    await self._run()
  File "/home/piper/projects/trinity/trinity/sync/beam/state.py", line 516, in _run
    await self.wait(self._match_node_requests_to_peers())
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 43, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/cancel_token/token.py", line 174, in cancellable_wait
    task.result()
  File "/home/piper/projects/trinity/trinity/sync/beam/state.py", line 333, in _match_node_requests_to_peers
    predictive_batch_id,
  File "/home/piper/projects/trinity/trinity/sync/beam/state.py", line 396, in _get_nodes_from_peer
    batch[node_hash] = node
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/piper/projects/trinity/trinity/db/manager.py", line 446, in atomic_batch
    ATOMIC_BATCH.value + kv_pair_count_and_size_data + kv_and_delete_data
BrokenPipeError: [Errno 32] Broken pipe
```

### How can it be fixed

Not sure.  There's no clear place that I see that handling this makes sense.  Ideally what we want to do is have the `DBManager` shutdown after all of the other processes have shutdown, or to have it give all of the connected clients some amount of time to disconnect before shutting down.

**Comment by gsalgado** [comment]
If we run the DBManager process in its own process group it should fix this because it'd only get a SIGINT after all components have terminated. The problem is that we use `multiprocessing` to run the DBManager and that package doesn't seem to let us run a process in its own process group

**Comment by cburgdorf** [comment]
I think that the long term plan was to put the db in an isolated component as well and then also change our component architecture in a way that allows orchestration of dependencies so that e.g. the db is the first to start during boot and the last to leave when the ship is sinking...eh the app is shutting down.

**Comment by pipermerriam** [comment]
@gsalgado The solution I've forseen for this is to add a concept of dependencies to the components so that they form a DAG and to force shutdown based on that hierarchy.  I never got around to prototyping but I'm reasonably confident that we need something like this since we have implicit dependencies between our compotnents but those dependencies are not accounted for in how they startup or shut down.
