### ISSUE TITLE
"Stale task history too long", coincides with sync stall

### ISSUE THREAD

**Issue by veox** [ethereum/trinity#120]
* py-evm Version: d6b746ca6deaf0c439ce1293f1419b96a0a5f08f
* OS: Arch Linux
* Python Version (python --version): 3.7.2
* Environment (output of `pip freeze`): MISSING

### What is wrong?

Not sure if one causes the other, or just coincidence.

Happens after `trinity` running for an hour or so.

~~Can force to happen much sooner by selectively blocking some outgoing connections (as described in https://github.com/ethereum/trinity/issues/118#issuecomment-452088723), a-la Corporate Firewall.~~ (Not sure anymore.)

Note that the "unexpected err" is at `INFO` level.

``` html
   DEBUG  01-08 15:25:46            FullServer  Receiving handshake from Address(89.163.224.38:udp:58364|tcp:58364)
   DEBUG  01-08 15:25:46               ETHPeer  Finished P2P handshake with <Node(0x7892@89.163.224.38)>, using sub-protocol (eth, 63)
   DEBUG  01-08 15:25:46               ETHPeer  Finished (eth, 63) handshake with <Node(0x7892@89.163.224.38)>
   DEBUG  01-08 15:25:46  ResponseCandidateStream  Launching <ResponseCandidateStream(ETHPeer <Node(0x7892@89.163.224.38)>, <class 'trinity.protocol.eth.commands.BlockHeaders'>)>
   DEBUG  01-08 15:25:46  ETHPeerRequestHandler  ETHPeer <Node(0xaf7c@172.11.72.143)> asked receipts for a block we don't have: 0x87b459c54f0efbcbf9c741468dc695527f8798eaa1ffadc2e57dfdb223f8c6c7
   DEBUG  01-08 15:25:46  ETHPeerRequestHandler  ETHPeer <Node(0xaf7c@172.11.72.143)> asked for a trie node we don't have: 0xd7fcce6c3b9eb4b7e42da69c2fcb1a9492163fae25f93a7cc57f8faed1d20f48
   DEBUG  01-08 15:25:46  ETHPeerRequestHandler  ETHPeer <Node(0xaf7c@172.11.72.143)> asked receipts for a block we don't have: 0x544e206e94e0305dd82728df6c7faa2d438594b5477007aaf9300c05a93cdd4b
   DEBUG  01-08 15:25:46  ETHPeerRequestHandler  ETHPeer <Node(0xaf7c@172.11.72.143)> asked for a trie node we don't have: 0xb7ca15d8645547deda1b6f64e6759c447842253eb315fa793133782de396e5c8
   DEBUG  01-08 15:25:46            FullServer  Receiving handshake from Address(159.89.164.235:udp:43422|tcp:43422)
   DEBUG  01-08 15:25:46   DAOCheckBootManager  <trinity.protocol.common.boot.DAOCheckBootManager object at 0x7f8e581e5ac8> had nothing left to do, ceasing operation...
   DEBUG  01-08 15:25:46   DAOCheckBootManager  <trinity.protocol.common.boot.DAOCheckBootManager object at 0x7f8e581e5ac8> halted cleanly
    INFO  01-08 15:25:46           ETHPeerPool  Adding ETHPeer <Node(0x7892@89.163.224.38)> to pool
   DEBUG  01-08 15:25:46      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x7892@89.163.224.38)>
   DEBUG  01-08 15:25:46  ETHPeerRequestHandler  ETHPeer <Node(0xaf7c@172.11.72.143)> asked for a block we don't have: 0x6735bad148ff5488c090ada4987ffbe6bb504fc9e36b4950b77865954c47bea1
   DEBUG  01-08 15:25:46               ETHPeer  Finished P2P handshake with <Node(0x8e87@159.89.164.235)>, using sub-protocol (eth, 63)
   DEBUG  01-08 15:25:46  ETHPeerRequestHandler  ETHPeer <Node(0xaf7c@172.11.72.143)> asked for a block we don't have: 0xd466056824f38ff07b3807a9ca25775a5d5dee77843c7531f482f2b343e3818a
   DEBUG  01-08 15:25:46  ETHPeerRequestHandler  ETHPeer <Node(0x7892@89.163.224.38)> requested headers: {'block_number_or_hash': 1920000, 'max_headers': 1, 'skip': 0, 'reverse': False}
   DEBUG  01-08 15:25:46               ETHPeer  Disconnecting from remote peer <Node(0x8e87@159.89.164.235)>; reason: useless_peer
   DEBUG  01-08 15:25:46            FullServer  Could not complete handshake: ETHPeer <Node(0x8e87@159.89.164.235)> network (18114) does not match ours (1), disconnecting
   DEBUG  01-08 15:25:46  ETHPeerRequestHandler  Peer requested header number 1920000 that is unavailable, stopping search.
   DEBUG  01-08 15:25:46  ETHPeerRequestHandler  ETHPeer <Node(0xaf7c@172.11.72.143)> asked receipts for a block we don't have: 0x511dc314a887af7d6f26a126cee5c0e5d7cd48dc0599905d90996325b2a414f1
   DEBUG  01-08 15:25:46  ETHPeerRequestHandler  ETHPeer <Node(0xaf7c@172.11.72.143)> asked for a block we don't have: 0xf8f66f7ed66f553760e789b827b27fe0e0b4e5d9658ede305dae72a103095f71
   DEBUG  01-08 15:25:46  ETHPeerRequestHandler  ETHPeer <Node(0xaf7c@172.11.72.143)> asked receipts for a block we don't have: 0xcfb1193d2a89edb0aaf1f8fe8b31e6f047415485328150e157b1503c73173448
   DEBUG  01-08 15:25:46  ETHPeerRequestHandler  ETHPeer <Node(0xaf7c@172.11.72.143)> asked for a block we don't have: 0xe7f9b7c3fa29927e33156d582ee5097aaef07372ec1483383f60e42c05956129
   DEBUG  01-08 15:25:46            FullServer  Receiving handshake from Address(94.130.18.190:udp:33608|tcp:33608)
   DEBUG  01-08 15:25:46               ETHPeer  Disconnecting from remote peer <Node(0x10ab@94.130.18.190)>; reason: too_many_peers
    INFO  01-08 15:25:46      HeaderMeatSyncer  Unexpected err while downloading headers from ETHPeer <Node(0x7892@89.163.224.38)>: Stale task history too long (9999) before pruning. b'\xdf\x0eq\x01\x13\x1e\xa2\x8a\xe8\xdc\x9c-\xad\xbea\xd6\x82\xcf%\xd0\xbdUg\xf6\x9c\x17\xcb\xb4\xd9\xce<\x9b' is still in cache.
   DEBUG  01-08 15:25:46      HeaderMeatSyncer  Problem downloading headers from peer, dropping...
```

Immediately followed by (this break for highlighting only):

``` python
Traceback (most recent call last):
  File "/home/veox/src/trinity/trinity/sync/common/headers.py", line 599, in _run_fetch_segment
    completed_headers = await peer.wait(self._fetch_segment(peer, parent_header, length))
  File "/home/veox/src/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/veox/src/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/veox/src/trinity/.virtualenv/trinity/lib/python3.7/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/home/veox/src/trinity/trinity/sync/common/headers.py", line 677, in _fetch_segment
    self._stitcher.register_tasks(headers, ignore_duplicates=True)
  File "/home/veox/src/trinity/trinity/_utils/datastructures.py", line 557, in register_tasks
    self._mark_complete(task_id)
  File "/home/veox/src/trinity/trinity/_utils/datastructures.py", line 601, in _mark_complete
    for task_id in qualified_tasks
  File "/home/veox/src/trinity/trinity/_utils/datastructures.py", line 601, in <genexpr>
    for task_id in qualified_tasks
  File "/home/veox/src/trinity/.virtualenv/trinity/lib/python3.7/site-packages/eth_utils/functional.py", line 46, in inner
    return callback(fn(*args, **kwargs))
  File "/home/veox/src/trinity/trinity/_utils/datastructures.py", line 620, in _mark_one_task_complete
    self._prune_finished(task_id)
  File "/home/veox/src/trinity/trinity/_utils/datastructures.py", line 639, in _prune_finished
    root_id, depth = self._find_root(oldest_id)
  File "/home/veox/src/trinity/trinity/_utils/datastructures.py", line 675, in _find_root
    f"Stale task history too long ({depth}) before pruning. {dependency} is still in cache."
eth_utils.exceptions.ValidationError: Stale task history too long (9999) before pruning. b'\xdf\x0eq\x01\x13\x1e\xa2\x8a\xe8\xdc\x9c-\xad\xbea\xd6\x82\xcf%\xd0\xbdUg\xf6\x9c\x17\xcb\xb4\xd9\xce<\x9b' is still in cache.
```

### How can it be fixed

Not sure.

### Extra

One indication that sync has stalled is `FastChainBodySyncer` lines, like

```
    INFO  01-14 15:55:17   FastChainBodySyncer  blks=209   txs=3260   bps=39   tps=279   elapsed=5.0  head=#2647534 2670..f531  age=2y1m3w

```

... are not being printed anymore.

**Comment by veox** [comment]
Am currently working on this. Found candidate solution.

**Comment by carver** [comment]
Huh, that's strange. I am trying to imagine how that's possible. I guess in an `OrderedTaskPreparation` that allows dangling tasks, if one task got added that linked two long chains, you might end up with a root that's much deeper (maybe up to 2x `_max_depth`).

If that's right, then changing this line: https://gist.github.com/veox/5c64f2b1a8ca853ae4a04126e6253883#file-trinity-issue-120-diff-L42

to this:
```py
        for depth in range(0, 2 * self._max_depth + 1):
```
(and removing the rest of the patch) would make the problem go away.

I am signing off now, but I can look into it more, later. (perhaps tomorrow)

**Comment by veox** [comment]
The actual much sloppier diff actually followed all the way down (using [sloppy debug-printing](https://github.com/veox/trinity/commit/59c7446b51234ac8bed6898f57122543b2111fa4#diff-8a085c33e95b52e1aba4d210b0d288c3R680)).

I've observed actual depths of, say, 122 (when `_max_depth` == 10); so just 2x would be insufficient; but that's with the rest of the patch, which prevents actual pruning.

I'll try your suggestion, but would like to note that if we assume two long chains are possible, then so are N long chains (with lower probability, but still).

**Comment by veox** [comment]
Also, on `sync-hodge-podge`, task pruning takes up 31.6% percent of execution time.

Not sure on `master` - will check in a sec...
