### ISSUE TITLE
Trinity crashes when given a bad block

### ISSUE THREAD

**Issue by lithp** [ethereum/trinity#1368]
* Trinity version: `v0.1.0-alpha.31` (0e3e67d2ceb52e124fcb866f11d3f9704cfe04bf)

### What is wrong?

I "fast synced" Trinity by coping the database over from geth, and have been full syncing it against mainnet. Trinity did not handle the Istanbul transition gracefully:

```
    INFO  2019-12-07 23:25:09,785  RegularChainBodySyncer  Imported block 9068993 (96 txs) in 15.48 seconds, with 7h1m46s lag                                                                                     
    INFO  2019-12-07 23:25:20,906  RegularChainBodySyncer  Imported block 9068994 (41 txs) in 11.12 seconds, with 7h1m14s lag                                                                                     
    INFO  2019-12-07 23:25:27,371  RegularChainBodySyncer  Imported block 9068995 (58 txs) in 6.44 seconds, with 7h1m8s lag                                                                                       
    INFO  2019-12-07 23:25:34,678  RegularChainBodySyncer  Imported block 9068996 (54 txs) in 7.30 seconds, with 7h0m57s lag                                                                                      
    INFO  2019-12-07 23:25:40,868  RegularChainBodySyncer  Imported block 9068997 (18 txs) in 6.19 seconds, with 7h1m lag                                                                                         
    INFO  2019-12-07 23:25:42,706  RegularChainBodySyncer  Imported block 9068998 (3 txs) in 1.84 seconds, with 7h0m54s lag                                                                                       
    INFO  2019-12-07 23:25:42,719  RegularChainBodySyncer  Imported block 9068999 (0 txs) in 0.01 seconds, with 7h0m34s lag                                                                                       
 WARNING  2019-12-07 23:25:53,757                    VM  Failed to validate header proof of work on header: {'parent_hash': b'\x1d\xb3\xfap\xc7\xce\xb9\xee\x9f?\xff)8|r\xd4p\x80\x84:\t\x9b~\xa9\x016\x97\xf5t9S\x8b', 'uncles_hash': b'\x1d\xccM\xe8\xde\xc7]z\xab\x85\xb5g\xb6\xcc\xd4\x1a\xd3\x12E\x1b\x94\x8at\x13\xf0\xa1B\xfd@\xd4\x93G', 'coinbase': b'Z\x0bT\xd5\xdc\x17\xe0\xaa\xdc8=-\xb4;\n\r>\x02\x9cL', 'state_root': b'qXS\xcb\x85\x92\xc7\x18\xf0,\x07\xbe\xc5\xb0\xf2\x88>J\xb9\x00\xe8#G\xac\x07U\xc9YjN\xbc\xf1', 'transaction_root': b'\xce\xe1e\x01\xe0\x07\xfeR@\xaaP\xfa\xa9l\xce`\xc7\xde\x8a\xe5o4\x04M\x85\x0e7\x8b\x98\xe0E7', 'receipt_root': b'\xbaj\xca\xe5\xe3\xea3\x8e\xff\xbe\xd4\x85\xc6\x97\xb2\xe0A\x86\xa1\x03H/\xd6_\x17\xdf\x81\xee\n8\x19\xe4', 'bloom': 7079330804815641557814028426732075174289296880037038290457232631635827604236693151891945914891804639870280694352264850785828522419117704767251152149281310664040495738292978730227004841092610499989354175533225828717212167564337904077381475381983872058634967122082818441964975965433316142362784454493341255985517222155652897754879807575890131925378963538051979436492914224925672773256984499732109359764618357588912636268826912756436250804453495353846162231458196585691134950585397039390715394725598230864202404932620443258465354843451878042385408628870029364450741200559916632148052762173457354220442709675759094595684, 'difficulty': 2557447920526205, 'block_number': 9069000, 'gas_limit': 8950633, 'gas_used': 8632735, 'timestamp': 1575764709, 'extra_data': b'PPYE sparkpool-eth-tw', 'mix_hash': b'\x8fs\xe0/t\x88\xe2\xe7\xa1\xc0\x9b\xdf\xf0c\xc5\xd48\xf3\x18\x1f\xa0\xbao\xf9\xc2^\x94OS\xc2\x9d\xb3', 'nonce': b'C\xbafp\x02[\xc5\xe0'}
 WARNING  2019-12-07 23:25:53,759  RegularChainBodySyncer  Task <coroutine object RegularChainBodySyncer._import_ready_blocks at 0x7f8b6d1551c8> finished unexpectedly: ValidationError('mix hash mismatch; expected: 0x519ebec0149864183cfe270ac7d38a2b914419f6d65ce469de0b88e427a9d61e != actual: 0x8f73e02f7488e2e7a1c09bdff063c5d438f3181fa0ba6ff9c25e944f53c29db3. Mix hash calculated from block #9069000, mine hash 0x7451898109874779369d159ebdc8a5158c01111f04aa96e381b13a30795d8e40, nonce 0x43ba6670025bc5e0, difficulty 2557447920526205, cache hash 0x7d8dc56dffec0be00bce2d28be6870072eeb8ea18a39c3044e358f896c4911b3')                   
```

Here's the debug log from the same time period:

```
ESC[1mESC[33m WARNING  2019-12-07 23:25:53,757                    VM  Failed to validate header proof of work on header: {'parent_hash': b'\x1d\xb3\xfap\xc7\xce\xb9\xee\x9f?\xff)8|r\xd4p\x80\x84:\t\x9b~\xa9\x016\x97\xf5t9S\x8b', 'uncles_hash': b'\x1d\xccM\xe8\xde\xc7]z\xab\x85\xb5g\xb6\xcc\xd4\x1a\xd3\x12E\x1b\x94\x8at\x13\xf0\xa1B\xfd@\xd4\x93G', 'coinbase': b'Z\x0bT\xd5\xdc\x17\xe0\xaa\xdc8=-\xb4;\n\r>\x02\x9cL', 'state_root': b'qXS\xcb\x85\x92\xc7\x18\xf0,\x07\xbe\xc5\xb0\xf2\x88>J\xb9\x00\xe8#G\xac\x07U\xc9YjN\xbc\xf1', 'transaction_root': b'\xce\xe1e\x01\xe0\x07\xfeR@\xaaP\xfa\xa9l\xce`\xc7\xde\x8a\xe5o4\x04M\x85\x0e7\x8b\x98\xe0E7', 'receipt_root': b'\xbaj\xca\xe5\xe3\xea3\x8e\xff\xbe\xd4\x85\xc6\x97\xb2\xe0A\x86\xa1\x03H/\xd6_\x17\xdf\x81\xee\n8\x19\xe4', 'bloom': 7079330804815641557814028426732075174289296880037038290457232631635827604236693151891945914891804639870280694352264850785828522419117704767251152149281310664040495738292978730227004841092610499989354175533225828717212167564337904077381475381983872058634967122082818441964975965433316142362784454493341255985517222155652897754879807575890131925378963538051979436492914224925672773256984499732109359764618357588912636268826912756436250804453495353846162231458196585691134950585397039390715394725598230864202404932620443258465354843451878042385408628870029364450741200559916632148052762173457354220442709675759094595684, 'difficulty': 2557447920526205, 'block_number': 9069000, 'gas_limit': 8950633, 'gas_used': 8632735, 'timestamp': 1575764709, 'extra_data': b'PPYE sparkpool-eth-tw', 'mix_hash': b'\x8fs\xe0/t\x88\xe2\xe7\xa1\xc0\x9b\xdf\xf0c\xc5\xd48\xf3\x18\x1f\xa0\xbao\xf9\xc2^\x94OS\xc2\x9d\xb3', 'nonce': b'C\xbafp\x02[\xc5\xe0'}ESC[0m
   DEBUG  2019-12-07 23:25:53,758  RegularChainBodySyncer  <coroutine object RegularChainBodySyncer._import_ready_blocks at 0x7f8b6d1550c8> finished while <trinity.sync.full.chain.RegularChainBodySyncer object at 0x7f8b6d1687f0> is still running, terminating as well
   DEBUG  2019-12-07 23:25:53,758  RegularChainBodySyncer  Cancelling service: <trinity.sync.full.chain.RegularChainBodySyncer object at 0x7f8b6d1687f0>
ESC[1mESC[33m WARNING  2019-12-07 23:25:53,759  RegularChainBodySyncer  Task <coroutine object RegularChainBodySyncer._import_ready_blocks at 0x7f8b6d1551c8> finished unexpectedly: ValidationError('mix hash mismatch; expected: 0x519ebec0149864183cfe270ac7d38a2b914419f6d65ce469de0b88e427a9d61e != actual: 0x8f73e02f7488e2e7a1c09bdff063c5d438f3181fa0ba6ff9c25e944f53c29db3. Mix hash calculated from block #9069000, mine hash 0x7451898109874779369d159ebdc8a5158c01111f04aa96e381b13a30795d8e40, nonce 0x43ba6670025bc5e0, difficulty 2557447920526205, cache hash 0x7d8dc56dffec0be00bce2d28be6870072eeb8ea18a39c3044e358f896c4911b3')ESC[0m
   DEBUG  2019-12-07 23:25:53,759  RegularChainBodySyncer  Task failure traceback
Traceback (most recent call last):
  File "/home/brian/trinity/p2p/service.py", line 158, in _run_task_wrapper
    await awaitable
  File "/home/brian/trinity/p2p/service.py", line 179, in _run_daemon_task_wrapper
    await awaitable
  File "/home/brian/trinity/trinity/sync/full/chain.py", line 1135, in _import_ready_blocks
    await self._import_block(block)
  File "/home/brian/trinity/trinity/sync/full/chain.py", line 1140, in _import_block
    self._block_importer.import_block(block)
  File "/home/brian/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/brian/trinity/p2p/cancellable.py", line 43, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/brian/.local/share/virtualenvs/trinity-dwQEboUK/lib/python3.7/site-packages/cancel_token/token.py", line 178, in cancellable_wait
    return done.pop().result()
  File "/home/brian/trinity/trinity/sync/common/chain.py", line 297, in import_block
    return await self._chain.coro_import_block(block, perform_validation=True)
  File "/home/brian/trinity/trinity/_utils/async_dispatch.py", line 23, in wrapper
    *args
  File "/home/brian/.pyenv/versions/3.7.3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/brian/.local/share/virtualenvs/trinity-dwQEboUK/lib/python3.7/site-packages/eth/chains/base.py", line 531, in import_block
    imported_block = self.get_vm(base_header_for_import).import_block(block)
  File "/home/brian/.local/share/virtualenvs/trinity-dwQEboUK/lib/python3.7/site-packages/eth/vm/base.py", line 326, in import_block
    return self.mine_block()
  File "/home/brian/.local/share/virtualenvs/trinity-dwQEboUK/lib/python3.7/site-packages/eth/vm/base.py", line 337, in mine_block
    self.validate_block(final_block)
  File "/home/brian/.local/share/virtualenvs/trinity-dwQEboUK/lib/python3.7/site-packages/eth/vm/base.py", line 581, in validate_block
    self.validate_header(block.header, parent_header)
  File "/home/brian/.local/share/virtualenvs/trinity-dwQEboUK/lib/python3.7/site-packages/eth/vm/base.py", line 645, in validate_header
    cls.validate_seal(header)
  File "/home/brian/.local/share/virtualenvs/trinity-dwQEboUK/lib/python3.7/site-packages/eth/vm/base.py", line 660, in validate_seal
    header.mix_hash, header.nonce, header.difficulty)
  File "/home/brian/.local/share/virtualenvs/trinity-dwQEboUK/lib/python3.7/site-packages/eth/consensus/pow.py", line 72, in check_pow
    f"mix hash mismatch; expected: {encode_hex(mining_output[b'mix digest'])} "
eth_utils.exceptions.ValidationError: mix hash mismatch; expected: 0x519ebec0149864183cfe270ac7d38a2b914419f6d65ce469de0b88e427a9d61e != actual: 0x8f73e02f7488e2e7a1c09bdff063c5d438f3181fa0ba6ff9c25e944f53c29db3. Mix hash calculated from block #9069000, mine hash 0x7451898109874779369d159ebdc8a5158c01111f04aa96e381b13a30795d8e40, nonce 0x43ba6670025bc5e0, difficulty 2557447920526205, cache hash 0x7d8dc56dffec0be00bce2d28be6870072eeb8ea18a39c3044e358f896c4911b3
   DEBUG  2019-12-07 23:25:53,782  RegularChainBodySyncer  <trinity.sync.full.chain.RegularChainBodySyncer object at 0x7f8b6d1687f0> finished: Cancellation requested by RegularChainBodySyncer:RegularChainSyncer:FullChainSyncer:FullNode token
```

**Comment by lithp** [comment]
Related to https://github.com/ethereum/py-evm/issues/1893, but I think the bug here is that anyone can kick trinity off the network by giving it a block which doesn't validate.

**Comment by cburgdorf** [comment]
Related: it looks like we aren't yet validating against Istanbul in Trinity :scream: 

https://github.com/ethereum/trinity/pull/1372
