### ISSUE TITLE
"key could not be deleted in JournalDB, because it was missing"

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1376]
* Trinity version: x.x.x
* OS: osx/linux/win
* Python version (output of `python --version`):
* Environment (output of `pip freeze`):

### What is wrong?

Bummer, looks like another consensus issue. I'm thinking we should probably add some required tasks for going Beta: integration with hive and the fuzz tester.

Introduced by: #1375

```
    INFO  2019-12-09 17:28:54,452     BeamBlockImporter  Beam importing <BlockHeader #9080467 0fa17295> (140 txns) ...
   DEBUG  2019-12-09 17:28:55,000     BlockImportServer  <coroutine object BlockImportServer.serve at 0x7f84fa1e3e60> finished while <trinity.sync.beam.importer.BlockImportServer object at 0x7f8509f28b70> is still running, terminating as
well
   DEBUG  2019-12-09 17:28:55,000     BlockImportServer  Cancelling service: <trinity.sync.beam.importer.BlockImportServer object at 0x7f8509f28b70>
ESC[1mESC[33m WARNING  2019-12-09 17:28:55,003     BlockImportServer  Task <coroutine object BlockImportServer.serve at 0x7f84fa1e3eb8> finished unexpectedly: KeyError(b'\x03', 'key could not be deleted in JournalDB, because it was missin
g')ESC[0m
   DEBUG  2019-12-09 17:28:55,003     BlockImportServer  Task failure traceback
Traceback (most recent call last):
  File "/home/jcarver/code/trinity/p2p/service.py", line 158, in _run_task_wrapper
    await awaitable
  File "/home/jcarver/code/trinity/p2p/service.py", line 179, in _run_daemon_task_wrapper
    await awaitable
  File "/home/jcarver/code/trinity/trinity/sync/beam/importer.py", line 486, in serve
    try:
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jcarver/code/trinity/trinity/sync/beam/importer.py", line 414, in _import_block
    reorg_info = beam_chain.import_block(block, perform_validation=True)
  File "/home/jcarver/code/py-evm/eth/chains/base.py", line 446, in import_block
    imported_block = self.get_vm(base_header_for_import).import_block(block)
  File "/home/jcarver/code/py-evm/eth/vm/base.py", line 284, in import_block
    new_header, receipts, _ = self.apply_all_transactions(block.transactions, header)
  File "/home/jcarver/code/py-evm/eth/vm/base.py", line 236, in apply_all_transactions
    transaction,
  File "/home/jcarver/code/py-evm/eth/vm/base.py", line 157, in apply_transaction
    computation = self.state.apply_transaction(transaction)
  File "/home/jcarver/code/py-evm/eth/vm/forks/frontier/state.py", line 193, in apply_transaction
    return executor(transaction)
  File "/home/jcarver/code/py-evm/eth/vm/state.py", line 275, in __call__
    computation = self.build_computation(message, transaction)
  File "/home/jcarver/code/py-evm/eth/vm/forks/frontier/state.py", line 133, in build_computation
    transaction_context).apply_message()
  File "/home/jcarver/code/py-evm/eth/vm/forks/frontier/computation.py", line 77, in apply_message
    self.transaction_context,
  File "/home/jcarver/code/py-evm/eth/vm/computation.py", line 554, in apply_computation
    opcode_fn(computation=computation)
  File "/home/jcarver/code/py-evm/eth/vm/logic/call.py", line 135, in __call__
    child_computation = computation.apply_child_computation(child_msg)
  File "/home/jcarver/code/py-evm/eth/vm/computation.py", line 366, in apply_child_computation
    child_computation = self.generate_child_computation(child_msg)
  File "/home/jcarver/code/py-evm/eth/vm/computation.py", line 381, in generate_child_computation
    self.transaction_context,
  File "/home/jcarver/code/py-evm/eth/vm/forks/frontier/computation.py", line 77, in apply_message
    self.transaction_context,
  File "/home/jcarver/code/py-evm/eth/vm/computation.py", line 554, in apply_computation
    opcode_fn(computation=computation)
  File "/home/jcarver/code/py-evm/eth/vm/forks/byzantium/opcodes.py", line 42, in inner
    return opcode_fn(computation)
  File "/home/jcarver/code/py-evm/eth/vm/forks/istanbul/storage.py", line 24, in sstore_eip2200
    return net_sstore(GAS_SCHEDULE_EIP2200, computation)
  File "/home/jcarver/code/py-evm/eth/vm/logic/storage.py", line 128, in net_sstore
    value=value,
  File "/home/jcarver/code/py-evm/eth/vm/state.py", line 111, in set_storage
    return self._account_db.set_storage(address, slot, value)
  File "/home/jcarver/code/py-evm/eth/db/account.py", line 162, in set_storage
    account_store.set(slot, value)
  File "/home/jcarver/code/py-evm/eth/db/storage.py", line 221, in set
    del self._journal_storage[key]
  File "/home/jcarver/code/py-evm/eth/db/journal.py", line 383, in __delitem__
    raise KeyError(key, "key could not be deleted in JournalDB, because it was missing")
KeyError: (b'\x03', 'key could not be deleted in JournalDB, because it was missing')
```

### How can it be fixed

Maybe this:
https://github.com/ethereum/py-evm/blob/e10fb92b08113dd7a11eff3d047f9348ea93a228/eth/db/storage.py#L190

to this?

```py
        self._locked_changes = BatchDB(self._storage_cache, read_through_deletes=True)
```

Oh nope, because:

```
eth_utils.exceptions.ValidationError: BatchDB should never apply deletes when reading through deletes
```

hmmm. Well, this may be a terrible idea, but...

I tried turning this:

https://github.com/ethereum/py-evm/blob/e10fb92b08113dd7a11eff3d047f9348ea93a228/eth/db/journal.py#L380-L383

into this:

```py
self._journal.delete_local(key)
```

... and so far it's fine. Obviously, I'll have to think about it for a while, and add some more tests before we just abandon that check. I'm not entirely sure why it's there in the first place...

**Comment by lithp** [comment]
Sad, I just run across this as well, on block 9069020 :cry:

**Comment by cburgdorf** [comment]
>I'm thinking we should probably add some required tasks for going Beta: integration with hive and the fuzz tester.

I'm in full agreement and it's something that I can direct some focus towards.

**Comment by carver** [comment]
So AIUI, this basically comes down to:
- `HexaryTrie` returns an empty value if you ask it for a key that doesn't exist
- `BatchDB` raises a `KeyError` if you ask it for a key that doesn't exist

`JournalDB` was requiring that a key be present in the wrapped database before it's deleted... but that check was meaningless against a `HexaryTrie`.

IIRC, the reason for that check is that we didn't want `JournalDB` to blow up later at `persist()` time, when it tries to delete a key that doesn't exist.
