### ISSUE TITLE
Publishing to a disconnected peer is unhandled

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/trinity#1395]
### What is wrong?

```
 WARNING  2019-12-13 05:05:29,089             Validator  Task <coroutine object Validator.handle_slot_tick at 0x7fd652a3c320> finished unexpectedly: KeyError(<libp2p.peer.id.ID (16Uiu2HAmJG8pt9jP3bfsFHsAVTsT9a6YRAEKRCNu8tjxnYghMArY)>)
   DEBUG  2019-12-13 05:05:29,089             Validator  Task failure traceback
Traceback (most recent call last):
  File "/home/ubuntu/trinity/p2p/service.py", line 158, in _run_task_wrapper
    await awaitable
  File "/home/ubuntu/trinity/p2p/service.py", line 179, in _run_daemon_task_wrapper
    await awaitable
  File "/home/ubuntu/trinity/trinity/components/eth2/beacon/validator.py", line 137, in handle_slot_tick
    await self.handle_first_tick(event.slot)
  File "/home/ubuntu/trinity/trinity/components/eth2/beacon/validator.py", line 225, in handle_first_tick
    head_block=head,
  File "/home/ubuntu/trinity/trinity/components/eth2/beacon/validator.py", line 268, in propose_block
    await self.p2p_node.broadcast_beacon_block(block)
  File "/home/ubuntu/trinity/trinity/protocol/bcc_libp2p/node.py", line 422, in broadcast_beacon_block
    await self._broadcast_data(PUBSUB_TOPIC_BEACON_BLOCK, ssz.encode(block))
  File "/home/ubuntu/trinity/trinity/protocol/bcc_libp2p/node.py", line 428, in _broadcast_data
    await self.pubsub.publish(topic, data)
  File "/home/ubuntu/.pyenv/versions/3.7.4/envs/trinity/lib/python3.7/site-packages/libp2p/pubsub/pubsub.py", line 451, in publish
    await self.push_msg(self.host.get_id(), msg)
  File "/home/ubuntu/.pyenv/versions/3.7.4/envs/trinity/lib/python3.7/site-packages/libp2p/pubsub/pubsub.py", line 525, in push_msg
    await self.router.publish(msg_forwarder, msg)
  File "/home/ubuntu/.pyenv/versions/3.7.4/envs/trinity/lib/python3.7/site-packages/libp2p/pubsub/gossipsub.py", line 187, in publish
    stream = self.pubsub.peers[peer_id]
KeyError: <libp2p.peer.id.ID (16Uiu2HAmJG8pt9jP3bfsFHsAVTsT9a6YRAEKRCNu8tjxnYghMArY)>
```

### How can it be fixed

Fill this in if you know how to fix it.

**Comment by ChihChengLiang** [comment]
Unable to reproduce again in a new version 😭
