### ISSUE TITLE
cancel_token.exceptions.OperationCancelled: Cancellation requested by BeaconChainSyncer:Node token

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#1398]
* Trinity version: 123e171a3b673f7d5d5372c71f808b5145ae52f8
* OS: osx
* Python version (output of `python --version`): Python 3.7.5
* Environment (output of `pip freeze`):
**libp2p==0.1.4**

### What is wrong?

Command
```
python eth2/beacon/scripts/run_beacon_nodes.py
```

Error messages
```
alice@16Uiu	    INFO  2019-12-15 23:47:41,026      BCCReceiveServer  Timed out waiting for <trinity.protocol.bcc_libp2p.servers.BCCReceiveServer object at 0x10a690310> to finish its cleanup, forcibly cancelling pending tasks and exiting anyway
alice@16Uiu	   DEBUG  2019-12-15 23:47:41,027      BCCReceiveServer  <trinity.protocol.bcc_libp2p.servers.BCCReceiveServer object at 0x10a690310>: Pending tasks (3): [<Task pending coro=<BCCReceiveServer._handle_beacon_attestation_loop() running at /Users/hwwang/ethereum/trinity/p2p/service.py:158> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10a6cd690>()]> cb=[gather.<locals>._done_callback() at /Users/hwwang/.pyenv/versions/3.7.5/lib/python3.7/asyncio/tasks.py:691]>, <Task pending coro=<BCCReceiveServer._handle_beacon_block_loop() running at /Users/hwwang/ethereum/trinity/p2p/service.py:158> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10a7beb50>()]> cb=[gather.<locals>._done_callback() at /Users/hwwang/.pyenv/versions/3.7.5/lib/python3.7/asyncio/tasks.py:691]>, <Task finished coro=<BCCReceiveServer._process_orphan_blocks_loop() done, defined at /Users/hwwang/ethereum/trinity/p2p/service.py:154> result=None>]
alice@16Uiu	   DEBUG  2019-12-15 23:47:41,027      BCCReceiveServer  All tasks finished
alice@16Uiu	   DEBUG  2019-12-15 23:47:41,027      BCCReceiveServer  <trinity.protocol.bcc_libp2p.servers.BCCReceiveServer object at 0x10a690310> halted cleanly
alice@16Uiu	   DEBUG  2019-12-15 23:47:41,040                  Node  Cancelling service: <trinity.protocol.bcc_libp2p.node.Node object at 0x10a5d4a90>
alice@16Uiu	   DEBUG  2019-12-15 23:47:41,040                  Node  <trinity.protocol.bcc_libp2p.node.Node object at 0x10a5d4a90> finished: Cancellation requested by Node token
alice@16Uiu	   DEBUG  2019-12-15 23:47:41,040                  Node  <trinity.protocol.bcc_libp2p.node.Node object at 0x10a5d4a90> halted cleanly
alice@16Uiu	   DEBUG  2019-12-15 23:47:41,040                  Node  <trinity.protocol.bcc_libp2p.node.Node object at 0x10a5d4a90> finished cleanly
alice@16Uiu	   DEBUG  2019-12-15 23:47:41,040             DBManager  <trinity.db.manager.DBManager object at 0x10e22bfd0>: closing client connection: Connection closed
alice@16Uiu	   DEBUG  2019-12-15 23:47:41,040  AsyncioEventBusService  Cancelling service: <trinity.extensibility.event_bus.AsyncioEventBusService object at 0x1056807d0>
alice@16Uiu	   DEBUG  2019-12-15 23:47:41,041              Endpoint  Endpoint[bbeacon-node]: server stopped
alice@16Uiu	   DEBUG  2019-12-15 23:47:41,042            Connection  Failed to send SubscriptionsUpdated(subscriptions=set(), response_expected=False). Handler closed.
alice@16Uiu	   DEBUG  2019-12-15 23:47:41,042              Endpoint  Endpoint[bbeacon-node]: stopped
alice@16Uiu	   DEBUG  2019-12-15 23:47:41,043  AsyncioEventBusService  <trinity.extensibility.event_bus.AsyncioEventBusService object at 0x1056807d0> finished: Cancellation requested by AsyncioEventBusService token
alice@16Uiu	   DEBUG  2019-12-15 23:47:41,043  AsyncioEventBusService  <trinity.extensibility.event_bus.AsyncioEventBusService object at 0x1056807d0> halted cleanly
alice@16Uiu	   DEBUG  2019-12-15 23:47:41,043  AsyncioEventBusService  <trinity.extensibility.event_bus.AsyncioEventBusService object at 0x1056807d0> finished cleanly
alice@16Uiu	   DEBUG  2019-12-15 23:47:41,043           IPCListener  <trinity._utils.logging.IPCListener object at 0x10fda42d0>: closing client connection: Connection closed
bob@16Uiu	   DEBUG  2019-12-15 23:47:41,044                 mplex  mplex unavailable while waiting for incoming: failed to read messages correctly from the underlying connection
bob@16Uiu	   DEBUG  2019-12-15 23:47:41,045                pubsub  fail to read from peer 16Uiu2HAmRkNuKCY8UVcYRaaoqRD71e841aEJV9DVXnHBZs34Jop2, error=,closing the stream and remove the peer from record
bob@16Uiu	   DEBUG  2019-12-15 23:47:41,045             gossipsub  removing peer 16Uiu2HAmRkNuKCY8UVcYRaaoqRD71e841aEJV9DVXnHBZs34Jop2
bob@16Uiu	   DEBUG  2019-12-15 23:47:41,045                pubsub  removed dead peer 16Uiu2HAmRkNuKCY8UVcYRaaoqRD71e841aEJV9DVXnHBZs34Jop2
alice@16Uiu	/Users/hwwang/.pyenv/versions/3.7.5/envs/env37a/lib/python3.7/site-packages/eth_keys/datatypes.py:28: DeprecationWarning: The eth_utils.typing module will be deprecated in favor of eth-typing in the next major version bump.
alice@16Uiu	  from eth_utils.typing import (
alice@16Uiu	/Users/hwwang/.pyenv/versions/3.7.5/envs/env37a/lib/python3.7/site-packages/ssz/sedes/serializable.py:97: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
alice@16Uiu	  class BaseSerializable(collections.Sequence):
alice@16Uiu	/Users/hwwang/ethereum/trinity/trinity/extensibility/asyncio.py:60: ResourceWarning: unclosed resource <TCPServer closed=False 0x10a6ae520>
alice@16Uiu	  loop.close()
alice@16Uiu	/Users/hwwang/ethereum/trinity/trinity/extensibility/asyncio.py:60: ResourceWarning: unclosed resource <TCPTransport closed=False reading=True 0x7fdc6b716330>
alice@16Uiu	  loop.close()
alice@16Uiu	Process SpawnProcess-5:
alice@16Uiu	Traceback (most recent call last):
alice@16Uiu	  File "/Users/hwwang/.pyenv/versions/3.7.5/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
alice@16Uiu	    self.run()
alice@16Uiu	  File "/Users/hwwang/.pyenv/versions/3.7.5/lib/python3.7/multiprocessing/process.py", line 99, in run
alice@16Uiu	    self._target(*self._args, **self._kwargs)
alice@16Uiu	  File "/Users/hwwang/ethereum/trinity/trinity/extensibility/component.py", line 105, in _run_process
alice@16Uiu	    cls.run_process(boot_info)
alice@16Uiu	  File "/Users/hwwang/ethereum/trinity/trinity/extensibility/asyncio.py", line 56, in run_process
alice@16Uiu	    loop.run_until_complete(task)
alice@16Uiu	  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
alice@16Uiu	  File "/Users/hwwang/ethereum/trinity/trinity/extensibility/asyncio.py", line 73, in _do_run
alice@16Uiu	    await cls.do_run(boot_info, event_bus)
alice@16Uiu	  File "/Users/hwwang/ethereum/trinity/trinity/components/eth2/beacon/component.py", line 173, in do_run
alice@16Uiu	    for service in services
alice@16Uiu	  File "/Users/hwwang/ethereum/trinity/p2p/service.py", line 358, in cancellation
alice@16Uiu	    await self.wait(self.events.cancelled.wait())
alice@16Uiu	  File "/Users/hwwang/ethereum/trinity/p2p/cancellable.py", line 20, in wait
alice@16Uiu	    return await self.wait_first(awaitable, token=token, timeout=timeout)
alice@16Uiu	  File "/Users/hwwang/ethereum/trinity/p2p/cancellable.py", line 43, in wait_first
alice@16Uiu	    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
alice@16Uiu	  File "/Users/hwwang/.pyenv/versions/3.7.5/envs/env37a/lib/python3.7/site-packages/cancel_token/token.py", line 176, in cancellable_wait
alice@16Uiu	    "Cancellation requested by {} token".format(self.triggered_token)
alice@16Uiu	cancel_token.exceptions.OperationCancelled: Cancellation requested by BeaconChainSyncer:Node token
alice@16Uiu	Task was destroyed but it is pending!
alice@16Uiu	task: <Task pending coro=<GossipSub.heartbeat() running at /Users/hwwang/.pyenv/versions/3.7.5/envs/env37a/lib/python3.7/site-packages/libp2p/pubsub/gossipsub.py:403> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10a719e50>()]>>
alice@16Uiu	    INFO  2019-12-15 23:47:41,192  AsyncioIsolatedComponent  Process 73624 has already terminated
alice@16Uiu	    INFO  2019-12-15 23:47:41,192  AsyncioIsolatedComponent  Process 73624 has already terminated
alice@16Uiu	    INFO  2019-12-15 23:47:41,192  AsyncioIsolatedComponent  Process 73624 has already terminated
```

[Full log is here](https://gist.github.com/hwwhww/420aa31417944ade68cbc729728155a9)

It seems something else is going wrong after #1379. Both nodes crashed.

### How can it be fixed

Fill this in if you know how to fix it.

**Comment by ChihChengLiang** [comment]
On this
