### ISSUE TITLE
Unexpected error during peer connection

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1405]
### What is wrong?

```
   DEBUG  12-18 15:21:47  async_process_runner.py  b'\x1b[1m\x1b[31m   ERROR  2019-12-18 15:21:47,268           LESPeerPool  unexpected error during peer connection\n'
   DEBUG  12-18 15:21:47  async_process_runner.py  b'Traceback (most recent call last):\n'
   DEBUG  12-18 15:21:47  async_process_runner.py  b'  File "/home/circleci/repo/p2p/peer_pool.py", line 209, in maybe_connect_more_peers\n'
   DEBUG  12-18 15:21:47  async_process_runner.py  b'    for backend in self.peer_backends\n'
   DEBUG  12-18 15:21:47  async_process_runner.py  b'  File "/home/circleci/repo/p2p/peer_pool.py", line 191, in _add_peers_from_backend\n'
   DEBUG  12-18 15:21:47  async_process_runner.py  b'    await self.connect_to_nodes(iter(candidates))\n'
   DEBUG  12-18 15:21:47  async_process_runner.py  b'  File "/home/circleci/repo/p2p/peer_pool.py", line 419, in connect_to_nodes\n'
   DEBUG  12-18 15:21:47  async_process_runner.py  b'    loop=self.get_event_loop(),\n'
   DEBUG  12-18 15:21:47  async_process_runner.py  b'  File "/home/circleci/repo/p2p/peer_pool.py", line 440, in connect_to_node\n'
   DEBUG  12-18 15:21:47  async_process_runner.py  b'    async with self.lock_node_for_handshake(node):\n'
   DEBUG  12-18 15:21:47  async_process_runner.py  b'  File "/home/circleci/repo/p2p/peer_pool.py", line 423, in lock_node_for_handshake\n'
   DEBUG  12-18 15:21:47  async_process_runner.py  b'    return self._handshake_locks.lock(node)\n'
   DEBUG  12-18 15:21:47  async_process_runner.py  b'  File "/home/circleci/repo/p2p/resource_lock.py", line 18, in lock\n'
   DEBUG  12-18 15:21:47  async_process_runner.py  b'    lock = self._locks[resource]\n'
   DEBUG  12-18 15:21:47  async_process_runner.py  b'  File "/home/circleci/repo/.tox/py36-wheel-cli/lib/python3.6/weakref.py", line 394, in __getitem__\n'
   DEBUG  12-18 15:21:47  async_process_runner.py  b'    return self.data[ref(key)]\n'
   DEBUG  12-18 15:21:47  async_process_runner.py  b"KeyError: <weakref at 0x7f48b9d9cf48; to 'Node' at 0x7f48b83175c0>\x1b[0m\n"
```
See: https://circleci.com/gh/ethereum/trinity/163515?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

### How can it be fixed

:man_shrugging:

**Comment by pipermerriam** [comment]
That is **very** odd on first look.  It suggests that `node` from has no non-weak references and thus it is not maintaining the reference to the lock.  If this occurs again we may need to just move away from the `weakref` approach and manage garbage collection of the locks manually.

**Comment by carver** [comment]
> If this occurs again we may need to just move away from the `weakref` approach and manage garbage collection of the locks manually.

I just got another repeat of this in CI:
https://circleci.com/gh/ethereum/trinity/186444

**Comment by pipermerriam** [comment]
PR incoming to update to manual garbage collection.
