### ISSUE TITLE
ListDeserializationError escaping

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1476]
### What is wrong?

```
DEBUG  01-15 09:24:19  async_process_runner.py  b'\x1b[1m\x1b[31m   ERROR  2020-01-15 09:24:19,047           ETHPeerPool  unexpected error during peer connection\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'Traceback (most recent call last):\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/commands.py", line 131, in decode\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    payload = cls.serialization_codec.decode(payload_data)\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/commands.py", line 64, in decode\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    rlp.decode(data, strict=self.decode_strict, sedes=self.sedes, recursive_cache=True)\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/.tox/py36-long_run_integration/lib/python3.6/site-packages/rlp/codec.py", line 237, in decode\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    obj = sedes.deserialize(item, **kwargs)\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/.tox/py36-long_run_integration/lib/python3.6/site-packages/eth_utils/functional.py", line 45, in inner\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    return callback(fn(*args, **kwargs))\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/.tox/py36-long_run_integration/lib/python3.6/site-packages/rlp/sedes/lists.py", line 83, in deserialize\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b"    raise ListDeserializationError('Can only deserialize sequences', serial)\n"
   DEBUG  01-15 09:24:19  async_process_runner.py  b'rlp.exceptions.ListDeserializationError: Can only deserialize sequences\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'The above exception was the direct cause of the following exception:\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'Traceback (most recent call last):\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/peer_pool.py", line 209, in maybe_connect_more_peers\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    for backend in self.peer_backends\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/peer_pool.py", line 191, in _add_peers_from_backend\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    await self.connect_to_nodes(iter(candidates))\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/peer_pool.py", line 413, in connect_to_nodes\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    loop=self.get_event_loop(),\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/peer_pool.py", line 444, in connect_to_node\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    peer = await self.connect(node)\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/peer_pool.py", line 358, in connect\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    timeout=HANDSHAKE_TIMEOUT,\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/cancellable.py", line 20, in wait\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    return await self.wait_first(awaitable, token=token, timeout=timeout)\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/cancellable.py", line 43, in wait_first\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/.tox/py36-long_run_integration/lib/python3.6/site-packages/cancel_token/token.py", line 178, in cancellable_wait\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    return done.pop().result()\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/peer.py", line 492, in handshake\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    token=self.cancel_token\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/handshake.py", line 321, in dial_out\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    token=token,\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/handshake.py", line 286, in negotiate_protocol_handshakes\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    in zip(selected_handshakers, selected_protocols)\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/.tox/py36-long_run_integration/lib/python3.6/site-packages/async_generator/_util.py", line 53, in __aexit__\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    await self._agen.athrow(type, value, traceback)\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/multiplexer.py", line 378, in multiplex\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    await fut\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/multiplexer.py", line 396, in _do_multiplexing\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    async for protocol, cmd in msg_stream:\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/cancellable.py", line 67, in wait_iter\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    timeout=timeout,\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/cancellable.py", line 20, in wait\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    return await self.wait_first(awaitable, token=token, timeout=timeout)\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/cancellable.py", line 43, in wait_first\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/.tox/py36-long_run_integration/lib/python3.6/site-packages/cancel_token/token.py", line 178, in cancellable_wait\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    return done.pop().result()\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/multiplexer.py", line 87, in stream_transport_messages\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    cmd = command_type.decode(msg, msg_proto.snappy_support)\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'  File "/home/circleci/repo/p2p/commands.py", line 136, in decode\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'    ) from err\n'
   DEBUG  01-15 09:24:19  async_process_runner.py  b'rlp.exceptions.DeserializationError: DeserializationError for p2p.p2p_proto.Disconnect\x1b[0m\n'
```

### How can it be fixed

:man_shrugging:

**Comment by pipermerriam** [comment]
Haven't looked where to handle this but it should be converted to a `MalformedMessage` exception somewhere in the call stack.
