### ISSUE TITLE
Stopping trinity-beacon doesn't work

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/trinity#1507]
* Trinity version: master
* OS: Arch Linux
* Python version (output of `python --version`):

### What is wrong?

Attempting to stop `trinity-beacon` by hitting `CTRL-c` fails on my machine. Here's the log output:

```
    INFO  2020-01-23 17:54:57,778      ComponentManager  Stopping components
    INFO  2020-01-23 17:54:57,779  TrioIsolatedComponent  Sent SIGINT to process 20572, waiting 10 seconds for it to terminate
    INFO  2020-01-23 17:54:57,785           Eth1Monitor  Eth1 Monitor got new eth1 block: Eth1Block(block_hash=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xb2\x81', number=45697, timestamp=396045), number of logs contained in the block: 1
Task was destroyed but it is pending!
task: <Task pending coro=<Event.wait() running at /home/jannik/.pyenv/versions/3.7.5/lib/python3.7/asyncio/locks.py:293> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f72c9bbb710>()]> cb=[_release_waiter(<Future pending>)() at /home/jannik/.pyenv/versions/3.7.5/lib/python3.7/asyncio/tasks.py:392]>
    INFO  2020-01-23 17:54:59,011  TrioIsolatedComponent  Process 20572 has already terminated
    INFO  2020-01-23 17:54:59,011  TrioIsolatedComponent  Process 20572 has already terminated
 WARNING  2020-01-23 17:55:03,017  asyncio_run_in_process  Child process pid=20570 failed to exit cleanly.  Sending SIGKILL
Traceback (most recent call last):
  File "/home/jannik/.pyenv/versions/3.7.5/envs/trinity/lib/python3.7/site-packages/asyncio_run_in_process/run_in_process.py", line 298, in _open_in_process
    raise err
  File "/home/jannik/.pyenv/versions/3.7.5/envs/trinity/lib/python3.7/site-packages/asyncio_run_in_process/run_in_process.py", line 263, in _open_in_process
    yield proc
  File "/home/jannik/Projects/Ethereum/trinity/trinity/extensibility/asyncio.py", line 52, in run
    raise err
  File "/home/jannik/Projects/Ethereum/trinity/trinity/extensibility/asyncio.py", line 37, in run
    await proc.wait()
  File "/home/jannik/.pyenv/versions/3.7.5/envs/trinity/lib/python3.7/site-packages/asyncio_run_in_process/process.py", line 249, in wait
    await self.wait_returncode()
  File "/home/jannik/.pyenv/versions/3.7.5/envs/trinity/lib/python3.7/site-packages/asyncio_run_in_process/process.py", line 174, in wait_returncode
    await self._has_returncode.wait()
  File "/home/jannik/.pyenv/versions/3.7.5/lib/python3.7/asyncio/locks.py", line 293, in wait
    await fut
concurrent.futures._base.CancelledError
```

After that, additional `CTRL-c`s don't seem to do anything and I have to `SIGKILL` it.

### How can it be fixed

No idea :(

**Comment by ralexstokes** [comment]
looks like an issue in `asyncio_run_in_process` -- pinging @carver and @pipermerriam as it looks they have touched that repo the most

**Comment by jannikluhn** [comment]
Probably related to https://github.com/ethereum/asyncio-run-in-process/issues/11

**Comment by gsalgado** [comment]
I believe whatever fixes come out of https://github.com/ethereum/trinity/issues/1613 will make this go away too
