### ISSUE TITLE
LifecycleError on shutdown

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1557]
* Trinity version: x.x.x
* OS: osx/linux/win
* Python version (output of `python --version`):
* Environment (output of `pip freeze`):

### What is wrong?

Left in a bit of context, but the main problem starts with `Task exception was never retrieved`:
```
Task <coroutine object BaseService.run at 0x7faf442a8468> finished unexpectedly: BrokenPipeError(32, 'Broken pipe')

sys:1: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2050, proto=0, laddr=('0.0.0.0', 30303)>

Task exception was never retrieved
future: <Task finished coro=<AsyncioManager.run() done, defined at /home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/asyncio.py:181> exception=LifecycleError('Should have already been completed',)>
Traceback (most recent call last):
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/asyncio.py", line 205, in run
    await self._wait_all_tasks_done()
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/asyncio.py", line 344, in cleanup_tasks
    await task
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/asyncio.py", line 142, in _handle_cancelled
    raise LifecycleError("Should have already been completed")
async_service.exceptions.LifecycleError: Should have already been completed

```

### How can it be fixed

:man_shrugging:

**Comment by gsalgado** [comment]
Well, with just that traceback it'd be nearly impossible to track this down. If it happens again, please include the debug logs. Closing for now as I haven't seen it lately
