### ISSUE TITLE
Failure to log over socket on shutdown

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1558]
### What is wrong?

While working on #1549 -- getting this regularly:
```
^C    INFO  2020-02-14 21:34:17,018      ComponentManager  Stopping components
--- Logging error ---
Traceback (most recent call last):
  File "/home/jcarver/code/trinity/trinity/db/manager.py", line 150, in serve_conn
    operation_byte = sock.read_exactly(1)
  File "/home/jcarver/code/trinity/trinity/_utils/socket.py", line 27, in read_exactly
    raise OSError("Connection closed")
OSError: Connection closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jcarver/code/trinity/trinity/_utils/logging.py", line 76, in emit
    self._socket.sendall(msg_length_data + msg_data)
OSError: [Errno 9] Bad file descriptor
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jcarver/code/trinity/trinity/_utils/socket.py", line 152, in _serve_conn
    self.serve_conn(sock)
  File "/home/jcarver/code/trinity/trinity/db/manager.py", line 152, in serve_conn
    self.logger.debug("%s: closing client connection: %s", self, err)
  File "/usr/lib/python3.6/logging/__init__.py", line 1296, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/home/jcarver/code/trinity/trinity/_utils/logging.py", line 78, in emit
    self.handleError(record)
Message: '%s: closing client connection: %s'
Arguments: (<trinity.db.manager.DBManager object at 0x7fcc5e3c7e10>, OSError('Connection closed',))
```

### How can it be fixed

Looks like the pipe for the logs is shutting down too early.

**Comment by carver** [comment]
Closed as (basically) a duplicate of #1381.
