### ISSUE TITLE
Crash with ListDeserializationError during peer discovery

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1584]
* Trinity version: 08c678437 (master)

### What is wrong?

Node shut down with:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jcarver/code/trinity/trinity/extensibility/trio.py", line 56, in run_process
    trio.run(cls._do_run, boot_info)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/trio/_core/_run.py", line 1804, in run
    raise runner.main_task_outcome.error
  File "/home/jcarver/code/trinity/trinity/extensibility/trio.py", line 70, in _do_run
    nursery.cancel_scope.cancel()
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/trio/_core/_run.py", line 730, in __aexit__
    raise combined_error_from_nursery
  File "/home/jcarver/code/trinity/trinity/components/builtin/peer_discovery/component.py", line 101, in do_run
    await async_service.run_trio_service(discovery_service)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/trio.py", line 156, in run_service
    await manager.run()
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/trio.py", line 208, in run
    for _, exc_value, exc_tb in self._errors
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/base.py", line 301, in _run_and_manage_task
    await task.run()
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/trio.py", line 76, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/jcarver/code/trinity/p2p/discovery.py", line 239, in handle_get_peer_candidates_requests
    candidates = self.get_peer_candidates(event.should_skip_fn, event.max_candidates)
  File "/home/jcarver/code/trinity/p2p/discovery.py", line 222, in get_peer_candidates
    if should_skip_fn(candidate):
  File "/home/jcarver/code/trinity/trinity/protocol/common/peer.py", line 293, in skip_candidate_if_on_list_or_fork_mismatch
    candidate_forkid = extract_forkid(candidate.enr)
  File "/home/jcarver/code/trinity/trinity/protocol/eth/forkid.py", line 127, in extract_forkid
    [forkid] = rlp.sedes.List([ForkID]).deserialize(eth_cap)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/rlp/sedes/lists.py", line 89, in deserialize
    serial)
rlp.exceptions.ListDeserializationError: Deserializing list length (0) does not match sedes (1)
```

Similar, but not the same as, #1476 

Looks like a misformatted message back from a peer during discovery isn't handled.

### How can it be fixed

Probably catch and re-wrap as something else, like a `MalformedMessage`?

cc @gsalgado

**Comment by gsalgado** [comment]
According to https://github.com/ethereum/devp2p/blob/master/enr-entries/eth.md, the `eth` ENR entry should always be a single element list, so it doesn't look like a bug in our deserializing of ForkIDs, but something we should handle regardless.
