### ISSUE TITLE
Crash when ENR is missing secp256k1 key

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1596]
* Trinity version: c634e39d

### What is wrong?

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jcarver/code/trinity/trinity/extensibility/trio.py", line 56, in run_process
    trio.run(cls._do_run, boot_info)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/trio/_core/_run.py", line 1804, in run
    raise runner.main_task_outcome.error
  File "/home/jcarver/code/trinity/trinity/extensibility/trio.py", line 70, in _do_run
    nursery.cancel_scope.cancel()
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/trio/_core/_run.py", line 730, in __aexit__
    raise combined_error_from_nursery
  File "/home/jcarver/code/trinity/trinity/components/builtin/peer_discovery/component.py", line 101, in do_run
    await async_service.run_trio_service(discovery_service)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/trio.py", line 156, in run_service
    await manager.run()
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/trio.py", line 208, in run
    for _, exc_value, exc_tb in self._errors
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/base.py", line 301, in _run_and_manage_task
    await task.run()
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/trio.py", line 76, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/jcarver/code/trinity/p2p/discovery.py", line 706, in receive
    await handler(node, payload, message_hash)
  File "/home/jcarver/code/trinity/p2p/discovery.py", line 848, in recv_enr_response
    enr = ENR.deserialize(serialized_enr)
  File "/home/jcarver/code/trinity/p2p/discv5/enr.py", line 163, in deserialize
    identity_scheme_registry=identity_scheme_registry,
  File "/home/jcarver/code/trinity/p2p/discv5/enr.py", line 89, in deserialize
    return UnsignedENR(sequence_number, kv_pairs, identity_scheme_registry)
  File "/home/jcarver/code/trinity/p2p/discv5/enr.py", line 206, in __init__
    self.identity_scheme.validate_enr_structure(self)
  File "/home/jcarver/code/trinity/p2p/discv5/identity_schemes.py", line 245, in validate_enr_structure
    raise ValidationError(f"ENR is missing required key {cls.public_key_enr_key!r}")
eth_utils.exceptions.ValidationError: ENR is missing required key b'secp256k1'
```

(Note that `enr.py` moved to `p2p/enr.py` since that commit)

### How can it be fixed

First thought is that we should capture the `ValidationError` raised by `UnsignedENR` here:

https://github.com/ethereum/trinity/blob/df92df488c6ade7a168483075c1d4f76843d3090/p2p/enr.py#L75-L82

and re-raise it as a `DeserializationError`.

---

But, that's an rlp-specific error, so maybe just catch `ValidationError` specifically at `deserialize()` call sites.

**Comment by gsalgado** [comment]
Yeah, `recv_enr_response()` has to handle these errors, and there is also a call to `enr.validate_signature()` there that can raise a `ValidationError`
