### ISSUE TITLE
Connection leaks BrokenPipeError, leading to shutdown

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1683]
I'm getting frequent shutdowns because of those. Guess we just need to handle the BrokenPipeError when closing a transport?

```
   DEBUG  2020-04-20 07:50:15,998               Manager  <Manager[FullNode] flags=SRcfe>: task FullServer[daemon=True] exited with error: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/salgado/src/async-service/async_service/base.py", line 301, in _run_and_manage_task
    await task.run()
  File "/home/salgado/src/async-service/async_service/base.py", line 166, in run
    await self.child_manager.run()
  File "/home/salgado/src/async-service/async_service/asyncio.py", line 217, in run
    for _, exc_value, exc_tb in self._errors
  File "/home/salgado/src/async-service/async_service/base.py", line 301, in _run_and_manage_task
    await task.run()
  File "/home/salgado/src/async-service/async_service/base.py", line 166, in run
    await self.child_manager.run()
  File "/home/salgado/src/async-service/async_service/asyncio.py", line 217, in run
    for _, exc_value, exc_tb in self._errors
  File "/home/salgado/src/async-service/async_service/base.py", line 301, in _run_and_manage_task
    await task.run()
  File "/home/salgado/src/async-service/async_service/base.py", line 166, in run
    await self.child_manager.run()
  File "/home/salgado/src/async-service/async_service/asyncio.py", line 217, in run
    for _, exc_value, exc_tb in self._errors
  File "/home/salgado/src/async-service/async_service/base.py", line 301, in _run_and_manage_task
    await task.run()
  File "/home/salgado/src/async-service/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/salgado/src/trinity/p2p/connection.py", line 154, in run
    await self._multiplexer.close()
  File "/home/salgado/src/trinity/p2p/multiplexer.py", line 185, in close
    await self._transport.close()
  File "/home/salgado/src/trinity/p2p/transport.py", line 333, in close
    await self._writer.drain()
  File "/usr/lib/python3.7/asyncio/streams.py", line 339, in drain
    raise exc
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by gsalgado** [comment]
And here's a nearly identical traceback, but with a ConnectionResetError instead. Might make sense to fix both at the same time

``` 
   DEBUG  2020-04-28 10:35:36,496               Manager  <Manager[Connection-<Session <Node(0x15ac30@52.176.7.10)> fcfed144-4bc4-4dfd-ae0f-a9b156f53e99>] flags=SRCfe>: task run[daemon=False] exited with error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/salgado/src/async-service/async_service/base.py", line 301, in _run_and_manage_task
    await task.run()
  File "/home/salgado/src/async-service/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/salgado/src/trinity/p2p/connection.py", line 154, in run
    await self._multiplexer.close()
  File "/home/salgado/src/trinity/p2p/multiplexer.py", line 187, in close
    await self._transport.close()
  File "/home/salgado/src/trinity/p2p/transport.py", line 333, in close
    await self._writer.drain()
  File "/usr/lib/python3.7/asyncio/streams.py", line 339, in drain
    raise exc
ConnectionResetError: [Errno 104] Connection reset by peer
```
