### ISSUE TITLE
DB process sometimes terminates before components

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1700]
Our DBManager process still runs on the same process group as the main process, so when there's a Ctrl-C in the terminal that process is likely to terminate before we send a SIGINT to our components' processes, leading to BrokenPipeErrors like below

```
   DEBUG  2020-04-28 07:39:12,250             component  Stopped component: Upnp
   DEBUG  2020-04-28 07:39:12,274             component  Stopped component: Discovery
   DEBUG  2020-04-28 07:39:13,125           ETHPeerPool  Could not complete handshake with <Node(0x648642c322691fdfa24a48bf70fcdc784669d1881dec2a6d3526b6e267a1e5ae3135523c53d3b92714d99db135a8c420a5cf15e96bbfe4b51513b3d7179f28c0@68.183.230.183:30303)>: TimeoutError()
   DEBUG  2020-04-28 07:39:13,126               Manager  <Manager[ETHPeerPool] flags=SRcfe>: task maybe_connect_more_peers[daemon=True] exited with error: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/salgado/src/async-service/async_service/base.py", line 301, in _run_and_manage_task
    await task.run()
  File "/home/salgado/src/async-service/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/salgado/src/trinity/trinity/protocol/common/peer.py", line 184, in maybe_connect_more_peers
    head = await self.get_chain_head()
  File "/home/salgado/src/trinity/trinity/protocol/common/peer.py", line 223, in get_chain_head
    return await self.context.headerdb.coro_get_canonical_head()
  File "/home/salgado/src/trinity/trinity/_utils/async_dispatch.py", line 25, in wrapper
    *args
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/salgado/virtualenvs/trinity-asyncio/lib/python3.7/site-packages/eth/db/header.py", line 82, in get_canonical_head
    return self._get_canonical_head(self.db)
  File "/home/salgado/virtualenvs/trinity-asyncio/lib/python3.7/site-packages/eth/db/header.py", line 86, in _get_canonical_head
    canonical_head_hash = cls._get_canonical_head_hash(db)
  File "/home/salgado/virtualenvs/trinity-asyncio/lib/python3.7/site-packages/eth/db/header.py", line 92, in _get_canonical_head_hash
    return Hash32(db[SchemaV1.make_canonical_head_hash_lookup_key()])
  File "/home/salgado/src/trinity/trinity/db/manager.py", line 266, in __getitem__
    self._socket.sendall(GET.value + len(key).to_bytes(LEN_BYTES, 'little') + key)
BrokenPipeError: [Errno 32] Broken pipe
   DEBUG  2020-04-28 07:39:13,138               Manager  <Manager[ETHPeerPool] flags=SRCfE>: _handle_cancelled triggering task cancellation
   DEBUG  2020-04-28 07:39:13,138               Manager  <Manager[ETHPeerPool] flags=SrCFE>: finished
```

**Comment by gsalgado** [comment]
Dupe of #1188
