### ISSUE TITLE
Intermittent failure on test_web3_commands_via_attached_console

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1706]
`tests/integration/test_trinity_cli.py::test_web3_commands_via_attached_console`: https://circleci.com/gh/ethereum/trinity/220367

**Comment by cburgdorf** [comment]
It looks like a variation of the pesky `EOFError`

```
   DEBUG  04-29 04:47:36  async_process_runner.py  b'Traceback (most recent call last):\n'
   DEBUG  04-29 04:47:36  async_process_runner.py  b'  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main\n'
   DEBUG  04-29 04:47:36  async_process_runner.py  b'    "__main__", mod_spec)\n'
   DEBUG  04-29 04:47:36  async_process_runner.py  b'  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code\n'
   DEBUG  04-29 04:47:36  async_process_runner.py  b'    exec(code, run_globals)\n'
   DEBUG  04-29 04:47:36  async_process_runner.py  b'  File "/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/asyncio_run_in_process/_child.py", line 265, in <module>\n'
   DEBUG  04-29 04:47:36  async_process_runner.py  b'    parent_pid=args.parent_pid, fd_read=args.fd_read, fd_write=args.fd_write\n'
   DEBUG  04-29 04:47:36  async_process_runner.py  b'  File "/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/asyncio_run_in_process/_child.py", line 197, in _run_process\n'
   DEBUG  04-29 04:47:36  async_process_runner.py  b'    async_fn, args = receive_pickled_value(from_parent)\n'
   DEBUG  04-29 04:47:36  async_process_runner.py  b'  File "/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/asyncio_run_in_process/_utils.py", line 62, in receive_pickled_value\n'
   DEBUG  04-29 04:47:36  async_process_runner.py  b'    len_bytes = read_exactly(stream, 4)\n'
   DEBUG  04-29 04:47:36  async_process_runner.py  b'  File "/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/asyncio_run_in_process/_utils.py", line 54, in read_exactly\n'
   DEBUG  04-29 04:47:36  async_process_runner.py  b'    raise ConnectionError("Got end of stream")\n'
   DEBUG  04-29 04:47:36  async_process_runner.py  b'ConnectionError: Got end of stream\n'
```
