### ISSUE TITLE
PeerConnectionLost triggering crash?

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#1715]
Working from master @ 9d3289918706fe5fa55fc8903248e45e63b2b1d6

### What is wrong?

I'm consistently getting a node crash with the following stack trace.

```
   ERROR  2020-05-06 12:17:48,671               asyncio  Exception in callback <TaskWakeupMethWrapper object at 0x7fc89b6c01c8>
handle: <Handle <TaskWakeupMethWrapper object at 0x7fc89b6c01c8>>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 70, in uvloop.loop.Handle._run
  File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 301, in _run_and_manage_task
    await task.run()
  File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 166, in run
    await self.child_manager.run()
  File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 217, in run
    for _, exc_value, exc_tb in self._errors
trio.MultiError: DaemonTaskExit('Daemon task _feed_protocol_handlers[daemon=True] exited'), PeerConnectionLost('Attempted to send msg with cmd id 2 to <Node(0x9d3825@185.154.159.152)> but transport is closing'), PeerConnectionLost('Attempted to send msg with cmd id 2 to <Node(0x596b0d@95.216.136.60)> but transport is closing')

Details of embedded exception 1:

  Traceback (most recent call last):
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 301, in _run_and_manage_task
      await task.run()
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 166, in run
      await self.child_manager.run()
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 217, in run
      for _, exc_value, exc_tb in self._errors
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 301, in _run_and_manage_task
      await task.run()
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 37, in run
      raise DaemonTaskExit(f"Daemon task {self} exited")
  async_service.exceptions.DaemonTaskExit: Daemon task _feed_protocol_handlers[daemon=True] exited

Details of embedded exception 2:

  Traceback (most recent call last):
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 338, in cleanup_tasks
      yield
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 406, in background_asyncio_service
      yield manager
    File "/home/piper/projects/trinity/p2p/p2p_api.py", line 87, in apply
      yield
    File "/home/piper/projects/trinity/p2p/behaviors.py", line 61, in apply
      yield
    File "/home/piper/projects/trinity/p2p/logic.py", line 91, in apply
      yield
    File "/home/piper/projects/trinity/p2p/behaviors.py", line 61, in apply
      yield
    File "/home/piper/projects/trinity/p2p/peer.py", line 285, in run
      await self.manager.wait_finished()
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 251, in wait_finished
      await self._finished.wait()
    File "/home/piper/.pyenv/versions/3.7.3/lib/python3.7/asyncio/locks.py", line 293, in wait
      await fut
  concurrent.futures._base.CancelledError

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 301, in _run_and_manage_task
      await task.run()
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 166, in run
      await self.child_manager.run()
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 217, in run
      for _, exc_value, exc_tb in self._errors
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 301, in _run_and_manage_task
      await task.run()
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 166, in run
      await self.child_manager.run()
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 217, in run
      for _, exc_value, exc_tb in self._errors
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 301, in _run_and_manage_task
      await task.run()
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 35, in run
      await self._async_fn(*self._async_fn_args)
    File "/home/piper/projects/trinity/p2p/peer.py", line 285, in run
      await self.manager.wait_finished()
    File "/home/piper/.pyenv/versions/3.7.3/lib/python3.7/contextlib.py", line 652, in __aexit__
      raise exc_details[1]
    File "/home/piper/.pyenv/versions/3.7.3/lib/python3.7/contextlib.py", line 635, in __aexit__
      cb_suppress = await cb(*exc_details)
    File "/home/piper/.pyenv/versions/3.7.3/lib/python3.7/contextlib.py", line 539, in _exit_wrapper
      return await cm_exit(cm, exc_type, exc, tb)
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
      await self._agen.athrow(type, value, traceback)
    File "/home/piper/projects/trinity/p2p/behaviors.py", line 61, in apply
      yield
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
      await self._agen.athrow(type, value, traceback)
    File "/home/piper/projects/trinity/p2p/logic.py", line 91, in apply
      yield
    File "/home/piper/.pyenv/versions/3.7.3/lib/python3.7/contextlib.py", line 652, in __aexit__
      raise exc_details[1]
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
      await self._agen.athrow(type, value, traceback)
    File "/home/piper/projects/trinity/p2p/behaviors.py", line 61, in apply
      yield
    File "/home/piper/.pyenv/versions/3.7.3/lib/python3.7/contextlib.py", line 635, in __aexit__
      cb_suppress = await cb(*exc_details)
    File "/home/piper/.pyenv/versions/3.7.3/lib/python3.7/contextlib.py", line 539, in _exit_wrapper
      return await cm_exit(cm, exc_type, exc, tb)
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
      await self._agen.athrow(type, value, traceback)
    File "/home/piper/projects/trinity/p2p/behaviors.py", line 61, in apply
      yield
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
      await self._agen.athrow(type, value, traceback)
    File "/home/piper/projects/trinity/p2p/p2p_api.py", line 87, in apply
      yield
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
      await self._agen.athrow(type, value, traceback)
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 415, in background_asyncio_service
      for _, exc_value, exc_tb in manager._errors
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 301, in _run_and_manage_task
      await task.run()
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 35, in run
      await self._async_fn(*self._async_fn_args)
    File "/home/piper/projects/trinity/p2p/p2p_api.py", line 56, in run
      _send_ping(conn)
    File "/home/piper/projects/trinity/p2p/p2p_api.py", line 140, in _send_ping
      connection.get_base_protocol().send(Ping(None))
    File "/home/piper/projects/trinity/p2p/protocol.py", line 58, in send
      self.transport.send(message)
    File "/home/piper/projects/trinity/p2p/transport.py", line 322, in send
      f"Attempted to send msg with cmd id {message.command_id} to "
  p2p.exceptions.PeerConnectionLost: Attempted to send msg with cmd id 2 to <Node(0x9d3825@185.154.159.152)> but transport is closing

Details of embedded exception 3:

  Traceback (most recent call last):
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 338, in cleanup_tasks
      yield
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 406, in background_asyncio_service
      yield manager
    File "/home/piper/projects/trinity/p2p/p2p_api.py", line 87, in apply
      yield
    File "/home/piper/projects/trinity/p2p/behaviors.py", line 61, in apply
      yield
    File "/home/piper/projects/trinity/p2p/logic.py", line 91, in apply
      yield
    File "/home/piper/projects/trinity/p2p/behaviors.py", line 61, in apply
      yield
    File "/home/piper/projects/trinity/p2p/peer.py", line 285, in run
      await self.manager.wait_finished()
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 251, in wait_finished
      await self._finished.wait()
    File "/home/piper/.pyenv/versions/3.7.3/lib/python3.7/asyncio/locks.py", line 293, in wait
      await fut
  concurrent.futures._base.CancelledError

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 301, in _run_and_manage_task
      await task.run()
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 166, in run
      await self.child_manager.run()
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 217, in run
      for _, exc_value, exc_tb in self._errors
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 301, in _run_and_manage_task
      await task.run()
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 166, in run
      await self.child_manager.run()
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 217, in run
      for _, exc_value, exc_tb in self._errors
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 301, in _run_and_manage_task
      await task.run()
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 35, in run
      await self._async_fn(*self._async_fn_args)
    File "/home/piper/projects/trinity/p2p/peer.py", line 285, in run
      await self.manager.wait_finished()
    File "/home/piper/.pyenv/versions/3.7.3/lib/python3.7/contextlib.py", line 652, in __aexit__
      raise exc_details[1]
    File "/home/piper/.pyenv/versions/3.7.3/lib/python3.7/contextlib.py", line 635, in __aexit__
      cb_suppress = await cb(*exc_details)
    File "/home/piper/.pyenv/versions/3.7.3/lib/python3.7/contextlib.py", line 539, in _exit_wrapper
      return await cm_exit(cm, exc_type, exc, tb)
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
      await self._agen.athrow(type, value, traceback)
    File "/home/piper/projects/trinity/p2p/behaviors.py", line 61, in apply
      yield
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
      await self._agen.athrow(type, value, traceback)
    File "/home/piper/projects/trinity/p2p/logic.py", line 91, in apply
      yield
    File "/home/piper/.pyenv/versions/3.7.3/lib/python3.7/contextlib.py", line 652, in __aexit__
      raise exc_details[1]
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
      await self._agen.athrow(type, value, traceback)
    File "/home/piper/projects/trinity/p2p/behaviors.py", line 61, in apply
      yield
    File "/home/piper/.pyenv/versions/3.7.3/lib/python3.7/contextlib.py", line 635, in __aexit__
      cb_suppress = await cb(*exc_details)
    File "/home/piper/.pyenv/versions/3.7.3/lib/python3.7/contextlib.py", line 539, in _exit_wrapper
      return await cm_exit(cm, exc_type, exc, tb)
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
      await self._agen.athrow(type, value, traceback)
    File "/home/piper/projects/trinity/p2p/behaviors.py", line 61, in apply
      yield
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
      await self._agen.athrow(type, value, traceback)
    File "/home/piper/projects/trinity/p2p/p2p_api.py", line 87, in apply
      yield
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
      await self._agen.athrow(type, value, traceback)
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 415, in background_asyncio_service
      for _, exc_value, exc_tb in manager._errors
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 301, in _run_and_manage_task
      await task.run()
    File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 35, in run
      await self._async_fn(*self._async_fn_args)
    File "/home/piper/projects/trinity/p2p/p2p_api.py", line 56, in run
      _send_ping(conn)
    File "/home/piper/projects/trinity/p2p/p2p_api.py", line 140, in _send_ping
      connection.get_base_protocol().send(Ping(None))
    File "/home/piper/projects/trinity/p2p/protocol.py", line 58, in send
      self.transport.send(message)
    File "/home/piper/projects/trinity/p2p/transport.py", line 322, in send
      f"Attempted to send msg with cmd id {message.command_id} to "
  p2p.exceptions.PeerConnectionLost: Attempted to send msg with cmd id 2 to <Node(0x596b0d@95.216.136.60)> but transport is closing
```

### How can it be fixed

:woman_shrugging:

**Comment by pipermerriam** [comment]
I'm not seeing why in the stacktrace but this appears to stop the peer pool which then causes this exception to show up:

```
   ERROR  2020-05-06 12:18:26,737            FullServer  Unexpected error handling handshake with ('127.0.0.1', 56612)
Traceback (most recent call last):
  File "/home/piper/projects/trinity/trinity/server.py", line 141, in receive_handshake
    await self._receive_handshake(reader, writer)
  File "/home/piper/projects/trinity/trinity/server.py", line 199, in _receive_handshake
    await self.peer_pool.start_peer(peer)
  File "/home/piper/projects/trinity/p2p/peer_pool.py", line 265, in start_peer
    self.manager.run_child_service(peer.connection)
  File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 314, in run_child_service
    self._common_run_task(task)
  File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 276, in _common_run_task
    "Tasks may not be scheduled if the service is not running"
async_service.exceptions.LifecycleError: Tasks may not be scheduled if the service is not running

   ERROR  2020-05-06 12:19:01,831            FullServer  Unexpected error handling handshake with ('127.0.0.1', 56676)
Traceback (most recent call last):
  File "/home/piper/projects/trinity/trinity/server.py", line 141, in receive_handshake
    await self._receive_handshake(reader, writer)
  File "/home/piper/projects/trinity/trinity/server.py", line 199, in _receive_handshake
    await self.peer_pool.start_peer(peer)
  File "/home/piper/projects/trinity/p2p/peer_pool.py", line 265, in start_peer
    self.manager.run_child_service(peer.connection)
  File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/asyncio.py", line 314, in run_child_service
    self._common_run_task(task)
  File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/async_service/base.py", line 276, in _common_run_task
    "Tasks may not be scheduled if the service is not running"
async_service.exceptions.LifecycleError: Tasks may not be scheduled if the service is not running
```

**Comment by gsalgado** [comment]
So, I believe the `PeerConnectionLost` would be expected/handled by the PeerPool, but asyncio-service is raising a MultiError containing a `DaemonTaskExit`, and that is not something the `PeerPool` expects/handles, so it crashes and takes everything else with it

**Comment by pipermerriam** [comment]
Good catch.  I recently had to write some `MultiError` handling code that dug into the sub-exceptions and felt quite hacky but it does work *ok*.

I suspect the better solution we want to find (if it exists) is to prevent the `DaemonTaskExit` from triggering so that we don't end up with the `MultiError` in the first place.
