### ISSUE TITLE
Exception in `FastChainBodySyncer`

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#177]
### What is wrong?

```
b'\x1b[1m\x1b[31m   ERROR  01-16 09:53:18   FastChainBodySyncer  Unknown error when getting block bodies\n'
b'Traceback (most recent call last):\n'
b'  File "/home/circleci/repo/.tox/py36-wheel-cli/lib/python3.6/site-packages/trinity/sync/full/chain.py", line 270, in _request_block_bodies\n'
b'    block_body_bundles = await peer.requests.get_block_bodies(batch)\n'
b'  File "/home/circleci/repo/.tox/py36-wheel-cli/lib/python3.6/site-packages/trinity/protocol/eth/exchanges.py", line 156, in __call__\n'
b'    timeout,\n'
b'  File "/home/circleci/repo/.tox/py36-wheel-cli/lib/python3.6/site-packages/trinity/protocol/common/exchanges.py", line 83, in get_result\n'
b'    timeout,\n'
b'  File "/home/circleci/repo/.tox/py36-wheel-cli/lib/python3.6/site-packages/trinity/protocol/common/managers.py", line 287, in get_result\n'
b'    result = await stream._run_in_executor(normalizer.normalize_result, payload)\n'
b'  File "/home/circleci/repo/.tox/py36-wheel-cli/lib/python3.6/site-packages/p2p/service.py", line 235, in _run_in_executor\n'
b'    return await self.wait(loop.run_in_executor(self._executor, callback, *args))\n'
b'  File "uvloop/loop.pyx", line 2512, in uvloop.loop.Loop.run_in_executor\n'
b'  File "/usr/local/lib/python3.6/concurrent/futures/process.py", line 452, in submit\n'
b"    raise BrokenProcessPool('A child process terminated '\n"
b'concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore\x1b[0m\n'
b'\x1b[1m\x1b[33m WARNING  01-16 09:53:18               ETHPeer  Task <coroutine object BaseBodyChainSyncer._run_body_download_batch at 0x7f9bc0740938> finished unexpectedly: A child process terminated abruptly, the process pool is not usable anymore\x1b[0m\n'
b'    INFO  01-16 09:53:18   FastChainBodySyncer  blks=42    txs=22     bps=0    tps=0     elapsed=5.0  head=#42 930e..99e6  age=2y1m3w\n'
b'\x1b[1m\x1b[31m   ERROR  01-16 09:53:18   FastChainBodySyncer  Unknown error when getting block bodies\n'
b'Traceback (most recent call last):\n'
b'  File "/home/circleci/repo/.tox/py36-wheel-cli/lib/python3.6/site-packages/trinity/sync/full/chain.py", line 270, in _request_block_bodies\n'
b'    block_body_bundles = await peer.requests.get_block_bodies(batch)\n'
b'  File "/home/circleci/repo/.tox/py36-wheel-cli/lib/python3.6/site-packages/trinity/protocol/eth/exchanges.py", line 156, in __call__\n'
b'    timeout,\n'
b'  File "/home/circleci/repo/.tox/py36-wheel-cli/lib/python3.6/site-packages/trinity/protocol/common/exchanges.py", line 83, in get_result\n'
b'    timeout,\n'
b'  File "/home/circleci/repo/.tox/py36-wheel-cli/lib/python3.6/site-packages/trinity/protocol/common/managers.py", line 287, in get_result\n'
b'    result = await stream._run_in_executor(normalizer.normalize_result, payload)\n'
b'  File "/home/circleci/repo/.tox/py36-wheel-cli/lib/python3.6/site-packages/p2p/service.py", line 235, in _run_in_executor\n'
b'    return await self.wait(loop.run_in_executor(self._executor, callback, *args))\n'
b'  File "uvloop/loop.pyx", line 2512, in uvloop.loop.Loop.run_in_executor\n'
b'  File "/usr/local/lib/python3.6/concurrent/futures/process.py", line 452, in submit\n'
b"    raise BrokenProcessPool('A child process terminated '\n"
b'concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore\x1b[0m\n'
b'\x1b[1m\x1b[33m WARNING  01-16 09:53:18               ETHPeer  Task <coroutine object BaseBodyChainSyncer._run_body_download_batch at 0x7f9bc07409e8> finished unexpectedly: A child process terminated abruptly, the process pool is not usable anymore\x1b[0m\n'
```

### How can it be fixed

Needs investigation

**Comment by carver** [comment]
I haven't ever seen this one. Did it go away? Maybe we can close and re-open if it resurfaces.

**Comment by cburgdorf** [comment]
Oh, I think that one was caused by the db writes getting swamped by too much incoming traffic and then causing the process pool to die. Should be fixed.
