### ISSUE TITLE
LifecycleError on RegularChainBodySyncer._assign_body_download_to_peers

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1770]
That method calls `peer.manager.run_task()` without first checking that the peer is still running, leading to the following LifecycleError:

```
   DEBUG  2020-06-03 11:26:02,837               Manager  <Manager[RegularChainBodySyncer] flags=SRcfe>: task _assign_body_download_to_peers[daemon=True] exited with error: Tasks may not be scheduled if the service is not running
Traceback (most recent call last):
  File "/home/salgado/virtualenvs/trinity37/lib/python3.7/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/salgado/virtualenvs/trinity37/lib/python3.7/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/salgado/src/trinity/trinity/sync/full/chain.py", line 277, in _assign_body_download_to_peers
    peer.manager.run_task(self._run_body_download_batch, peer, batch_id, headers)
  File "/home/salgado/virtualenvs/trinity37/lib/python3.7/site-packages/async_service/asyncio.py", line 328, in run_task
    self._common_run_task(task)
  File "/home/salgado/virtualenvs/trinity37/lib/python3.7/site-packages/async_service/base.py", line 275, in _common_run_task
    "Tasks may not be scheduled if the service is not running"
async_service.exceptions.LifecycleError: Tasks may not be scheduled if the service is not running
```

This is fallout from the conversion to new-style services, as before it was possible to schedule tasks on services that were already cancelled

**Comment by gsalgado** [comment]
`FastChainBodySyncer._assign_receipt_download_to_peers` and `HeaderMeatSyncer._match_dl_to_peer` as well
