### ISSUE TITLE
Malformed response during handshake

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1784]
### What is wrong?

I'm getting a malformed response from one of the Görli bootnodes.

```sh
ERROR  2020-06-15 10:34:29,388           ETHPeerPool  Got malformed response from <Node(0x46add44b9f13965f7b9875ac6b85f016f341012d84f975377573800a863526f4da19ae2c620ec73d11591fa9510e992ecc03ad0751f53cc02f7c7ed6d55c7291@94.237.54.114:30313)> during handshake
```

This is most likely an error on our end so I'm going to investigate further

The error is thrown here:

https://github.com/ethereum/trinity/blob/615d6bcc871ac8c8ae795a39fb55ac6745650cb2/p2p/transport.py#L263-L266

```python
Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/peer_pool.py", line 352, in connect
    return await asyncio.wait_for(task, timeout=HANDSHAKE_TIMEOUT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/peer.py", line 527, in handshake
    protocol_handshakers=handshakers,
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/handshake.py", line 336, in dial_out
    protocol_handshakers=protocol_handshakers,
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/handshake.py", line 233, in negotiate_protocol_handshakes
    ephemeral_base_protocol,
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/handshake.py", line 138, in _do_p2p_handshake
    async for _, cmd in stream_transport_messages(transport, base_protocol):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/multiplexer.py", line 56, in stream_transport_messages
    msg = await transport.recv()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/transport.py", line 266, in recv
    raise MalformedMessage(*err.args) from err
p2p.exceptions.MalformedMessage: Deserializing list length (1) does not match sedes (2)
```

### How can it be fixed

Debug

**Comment by gsalgado** [comment]
Closing as we have more info in #2052
