### ISSUE TITLE
On Clique, checkpoints need to be aligned with Clique checkpoints

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1785]
### What is wrong?

Using `--sync-from-checkpoint eth://block/byetherscan/latest` will most likely result in such a crash for the Görli network.

```sh

[1m[31m   ERROR  2020-06-15 11:14:14,649                  Sync  Unexpected error in component <trinity.components.builtin.syncer.component.SyncerComponent object at 0x7fa48426e810>, shutting down trinity
Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/eth/consensus/clique/snapshot_manager.py", line 159, in get_or_create_snapshot
    snapshot = self.get_snapshot(block_number, block_hash)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/eth/consensus/clique/snapshot_manager.py", line 237, in get_snapshot
    raise SnapshotNotFound(f"Can not get snapshot for {block_hash!r} at {block_number}")
eth.consensus.clique.exceptions.SnapshotNotFound: Can not get snapshot for b'\xd0\x8d\x8e\xfc\x02\x0f\xc8\x88\xdc"\tWzlU\xde\xb2`y\xac\x80\x8c\xd93\xc8\xb4\xee\xef\x83l\xdcP' at 2872206

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/eth/consensus/clique/snapshot_manager.py", line 184, in create_snapshot_for
    current_header.block_number, current_header.parent_hash)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/eth/consensus/clique/snapshot_manager.py", line 237, in get_snapshot
    raise SnapshotNotFound(f"Can not get snapshot for {block_hash!r} at {block_number}")
eth.consensus.clique.exceptions.SnapshotNotFound: Can not get snapshot for b'\xc2\xd2\x1a\x0fqu8)\x9b\xb5o\xaf\x85\x07\xf4\x10\xb6\xa24v\x81O\x8c\x92W\x8a"\x11\xb9\x8c\xee\xc9' at 2872206

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/eth/db/header.py", line 162, in _get_block_header_by_hash
    header_rlp = db[block_hash]
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/db/manager.py", line 291, in __getitem__
    raise KeyError(key)
KeyError: b'\xc2\xd2\x1a\x0fqu8)\x9b\xb5o\xaf\x85\x07\xf4\x10\xb6\xa24v\x81O\x8c\x92W\x8a"\x11\xb9\x8c\xee\xc9'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/eth/consensus/clique/snapshot_manager.py", line 77, in _lookup_header
    return self._chain_db.get_block_header_by_hash(block_hash)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/eth/db/header.py", line 151, in get_block_header_by_hash
    return self._get_block_header_by_hash(self.db, block_hash)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/eth/db/header.py", line 164, in _get_block_header_by_hash
    raise HeaderNotFound(f"No header with hash {encode_hex(block_hash)} found")
eth.exceptions.HeaderNotFound: No header with hash 0xc2d21a0f717538299bb56faf8507f410b6a23476814f8c92578a2211b98ceec9 found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/extensibility/asyncio.py", line 58, in _do_run
    await self.do_run(event_bus)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/components/builtin/syncer/component.py", line 393, in do_run
    await self.launch_sync(node, strategy, boot_info, event_bus)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/components/builtin/syncer/component.py", line 409, in launch_sync
    event_bus,
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/components/builtin/syncer/component.py", line 241, in sync
    await manager.wait_finished()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/async_service/asyncio.py", line 444, in background_asyncio_service
    for _, exc_value, exc_tb in manager._errors
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/async_service/asyncio.py", line 246, in run
    for _, exc_value, exc_tb in self._errors
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/sync/beam/chain.py", line 212, in run
    await manager.wait_finished()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/async_service/asyncio.py", line 444, in background_asyncio_service
    for _, exc_value, exc_tb in manager._errors
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/sync/beam/chain.py", line 440, in _persist_headers_if_tip_too_old
    self.logger, self._db, self._header_syncer, self._exit_if_launchpoint):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/sync/common/headers.py", line 1063, in persist_headers
    syncer._chain.validate_chain_extension(headers)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/eth/chains/base.py", line 184, in validate_chain_extension
    vm.validate_seal_extension(header, parents)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/eth/vm/base.py", line 607, in validate_seal_extension
    self._consensus.validate_seal_extension(header, parents)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/eth/consensus/clique/clique.py", line 131, in validate_seal_extension
    header.block_number - 1, header.parent_hash, parents)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/eth/consensus/clique/snapshot_manager.py", line 161, in get_or_create_snapshot
    return self.create_snapshot_for(block_hash, parents)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/eth/consensus/clique/snapshot_manager.py", line 186, in create_snapshot_for
    current_header = self._lookup_header(current_header.parent_hash, cached_parents)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/eth/consensus/clique/snapshot_manager.py", line 79, in _lookup_header
    raise ValidationError("Unknown ancestor %s", encode_hex(block_hash))
eth_utils.exceptions.ValidationError: ('Unknown ancestor %s', '0xc2d21a0f717538299bb56faf8507f410b6a23476814f8c92578a2211b98ceec9')[0m
```

Resolving a checkpoint from etherscan doesn't take cliques checkpointing rules into account which means it will land on a random header that one can not retrieve the current lists of signers from.

### How can it be fixed

Probably one of these:

1. Detect if we are on a Clique network and if yes, enforce that the header we pick from etherscan aligns to the checkpointing rules of the network (e.g blocknumber % 30000 for Görli)

2. Tell the user to pick a checkpoint manually

**Comment by Elnaril** [comment]
Hello Team,

I've been looking into Trinity's code and would like to give a try to contribute. I am using this issue #1785 as a way to enter the project.
If it's fine for you, I could pull a request in order to start a discussion based on my current understanding of the issue, the  preferred method to solve it and the project's guidelines.

Best Regards

**Comment by cburgdorf** [comment]
Hi @Elnaril 

>If it's fine for you, I could pull a request in order to start a discussion based on my current understanding of the issue, the preferred method to solve it and the project's guidelines.

Yes, that would be great!

**Comment by Elnaril** [comment]
Hello @cburgdorf ,
I guess this issue can be marked as closed now ! :)
