### ISSUE TITLE
SyncerComponent gets stuck during shutdown

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#1859]
@gsalgado please feel free to close this if you already have an issue where you are tracking this:

### What is wrong?

When shutting down Trinity using `CTRL+C` I consistently get the following warning:

```bash
 WARNING  2020-07-08 13:06:32,000  asyncio_run_in_process  Child process pid=2390502 failed to exit cleanly.  Sending SIGKILL
Traceback (most recent call last):
  File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/asyncio_run_in_process/main.py", line 373, in _open_in_process
    raise err
  File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/asyncio_run_in_process/main.py", line 323, in _open_in_process
    yield proc
  File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/asyncio_run_in_process/main.py", line 410, in run_in_process
    await proc.wait()
  File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/asyncio_run_in_process/process.py", line 244, in wait
    await self.wait_returncode()
  File "/home/piper/python-environments/trinity/lib/python3.7/site-packages/asyncio_run_in_process/process.py", line 174, in wait_returncode
    await self._has_returncode.wait()
  File "/home/piper/.pyenv/versions/3.7.3/lib/python3.7/asyncio/locks.py", line 293, in wait
    await fut
concurrent.futures._base.CancelledError
```

### How can it be fixed

:woman_shrugging:

**Comment by gsalgado** [comment]
I haven't seen these in a really long time.

@pipermerriam do you get that for all processes? Can you paste the full logs somewhere? Are you on python3.7 on 3.8?

**Comment by gsalgado** [comment]
I can't reproduce it on 3.7 either

**Comment by pipermerriam** [comment]
I was using some very old version of python 3.7 (3.7.3).

I'm investigating if this is still present after upgrading.  I'll re-open if it is.

**Comment by gsalgado** [comment]
Was able to reproduce it; it's the Syncer component that seems to get stuck and needs to be sent a SIGKILL

```
  DEBUG  2020-07-09 15:01:33,521  asyncio_run_in_process  waiting for process Process[<bound method AsyncioIsolatedComponent._do_run of <trinity.components.builtin.syncer.component.SyncerComponent object at 0x7f13e312d550>>] (pid=188721) to finish
...
  WARNING  2020-07-09 15:40:16,502  asyncio_run_in_process  Child process pid=188721 failed to exit cleanly.  Sending SIGKILL
Traceback (most recent call last):
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/main.py", line 373, in _open_in_process
    raise err
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/main.py", line 323, in _open_in_process
    yield proc
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/main.py", line 410, in run_in_process
    await proc.wait()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/process.py", line 244, in wait
    await self.wait_returncode()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/process.py", line 174, in wait_returncode
    await self._has_returncode.wait()
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
asyncio.exceptions.CancelledError
```

**Comment by gsalgado** [comment]
BeamChainExecutionComponent and BeamChainPreviewComponent[0-3] also seem to get stuck and require a SIGKILL

**Comment by cburgdorf** [comment]
That might also explain why we can't yet activate the `test_clean_shutdown` test for beam sync.

**Comment by pipermerriam** [comment]
(probably obvious at this point but I'm still getting these in my shiny new python versions
