### ISSUE TITLE
Trinity crash looking up protocol while connection is closing.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#1875]
### What is wrong?

Another probably race condition:

```
Traceback (most recent call last):
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 367, in cleanup_tasks
    yield
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 435, in background_asyncio_service
    yield manager
  File "/home/piper/projects/trinity/trinity/components/builtin/syncer/component.py", line 388, in do_run
    await wait_first([sync_task, asyncio.create_task(node_manager.wait_finished())])
  File "/home/piper/projects/trinity/p2p/logic.py", line 93, in wait_first
    await cancel_futures(pending)
  File "/home/piper/projects/trinity/p2p/logic.py", line 166, in cancel_futures
    raise MultiError(errors)
asyncio.exceptions.TimeoutError: ('Tasks never returned after being cancelled: %s', {<Task finished name='Task-19' coro=<SyncerComponent.launch_sync() done, defined at /home/piper/projects/trinity/trinity/components/builtin/syncer/component.py:390> exception=OSError(9, 'Bad file descriptor')>})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 205, in run_process
    runner(async_fn, args, to_parent)
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 168, in _run_on_asyncio
    result: Any = loop.run_until_complete(_do_async_fn(async_fn, args, to_parent, loop))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 160, in _do_async_fn
    return await async_fn_task
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 85, in _handle_coro
    return await coro_task
  File "/home/piper/projects/trinity/trinity/extensibility/asyncio.py", line 51, in _do_run
    await self.do_run(event_bus)
  File "/home/piper/projects/trinity/trinity/components/builtin/syncer/component.py", line 388, in do_run
    await wait_first([sync_task, asyncio.create_task(node_manager.wait_finished())])
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 441, in background_asyncio_service
    raise MultiError(
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/piper/projects/trinity/p2p/peer.py", line 268, in run
    self.p2p_api = self.connection.get_logic('p2p', P2PAPI)
  File "/home/piper/projects/trinity/p2p/connection.py", line 284, in get_logic
    if not self.has_logic(name):
  File "/home/piper/projects/trinity/p2p/connection.py", line 280, in has_logic
    raise PeerConnectionLost("Cannot look up subprotocol when connection is closing")
p2p.exceptions.PeerConnectionLost: Cannot look up subprotocol when connection is closing
```

### How can it be fixed

:shrug:

**Comment by gsalgado** [comment]
Ok, so `Peer.run()` crashes if the connection is closing, and that should be easy to fix, but the following is the real issue that caused the component to stop, no?

```
asyncio.exceptions.TimeoutError: ('Tasks never returned after being cancelled: %s', {<Task finished name='Task-19' coro=<SyncerComponent.launch_sync() done, defined at /home/piper/projects/trinity/trinity/components/builtin/syncer/component.py:390> exception=OSError(9, 'Bad file descriptor')>})
```
