### ISSUE TITLE
OSError (Bad file descriptor) on FastChainBodySyncer crashes trinity

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1878]
### What is wrong?

This one popped up on my logs after the PCL error I reported in #1877. And may also be the same as in #1875, but I can't see how they could be related.

```
   DEBUG  2020-07-13 12:24:58,009               Manager  <Manager[FastChainBodySyncer] flags=SRcfe>: task _launch_prerequisite_tasks[daemon=True] exited with error: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/salgado/src/snakecharmers/trinity/trinity/sync/full/chain.py", line 658, in _launch_prerequisite_tasks
    async for headers in self._sync_from_headers(
  File "/home/salgado/src/snakecharmers/trinity/trinity/sync/full/chain.py", line 191, in _sync_from_headers
    async for headers in get_headers_coro:
  File "/home/salgado/src/snakecharmers/trinity/trinity/sync/common/headers.py", line 576, in new_sync_headers
    header = await self._db.coro_get_canonical_block_header_by_number(
  File "/home/salgado/src/snakecharmers/trinity/trinity/_utils/async_dispatch.py", line 22, in wrapper
    return await loop.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/eth/db/header.py", line 121, in get_canonical_block_header_by_number
    return self._get_canonical_block_header_by_number(self.db, block_number)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/eth/db/header.py", line 129, in _get_canonical_block_header_by_number
    canonical_block_hash = cls._get_canonical_block_hash(db, block_number)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/eth/db/header.py", line 112, in _get_canonical_block_hash
    encoded_key = db[number_to_hash_key]
  File "/home/salgado/src/snakecharmers/trinity/trinity/db/manager.py", line 283, in __getitem__
    self._socket.sendall(GET.value + len(key).to_bytes(LEN_BYTES, 'little') + key)
OSError: [Errno 9] Bad file descriptor
```

### How can it be fixed

No idea

**Comment by gsalgado** [comment]
This is the full traceback sent to stderr when trinity finally terminated

```
   ERROR  2020-07-13 12:25:01,062                  root  Error during trinity run
asyncio_run_in_process._utils.RemoteTraceback:
""" (exception from process: 422184)
Traceback (most recent call last):
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 367, in cleanup_tasks
    yield
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 435, in background_asyncio_service
    yield manager
  File "/home/salgado/src/snakecharmers/trinity/trinity/components/builtin/syncer/component.py", line 233, in sync
    await manager.wait_finished()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 280, in wait_finished
    await self._finished.wait()
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 367, in cleanup_tasks
    yield
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 435, in background_asyncio_service
    yield manager
  File "/home/salgado/src/snakecharmers/trinity/trinity/components/builtin/syncer/component.py", line 388, in do_run
    await wait_first([sync_task, asyncio.create_task(node_manager.wait_finished())])
  File "/home/salgado/src/snakecharmers/trinity/p2p/logic.py", line 94, in wait_first
    await cancel_futures(pending)
  File "/home/salgado/src/snakecharmers/trinity/p2p/logic.py", line 167, in cancel_futures
    raise MultiError(errors)
  File "/home/salgado/src/snakecharmers/trinity/trinity/components/builtin/syncer/component.py", line 397, in launch_sync
    await strategy.sync(
  File "/home/salgado/src/snakecharmers/trinity/trinity/components/builtin/syncer/component.py", line 233, in sync
    await manager.wait_finished()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 441, in background_asyncio_service
    raise MultiError(
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/salgado/src/snakecharmers/trinity/trinity/sync/beam/chain.py", line 521, in run
    await self.manager.run_service(self._body_syncer)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 182, in run_service
    await manager.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/salgado/src/snakecharmers/trinity/trinity/sync/full/chain.py", line 658, in _launch_prerequisite_tasks
    async for headers in self._sync_from_headers(
  File "/home/salgado/src/snakecharmers/trinity/trinity/sync/full/chain.py", line 191, in _sync_from_headers
    async for headers in get_headers_coro:
  File "/home/salgado/src/snakecharmers/trinity/trinity/sync/common/headers.py", line 576, in new_sync_headers
    header = await self._db.coro_get_canonical_block_header_by_number(
  File "/home/salgado/src/snakecharmers/trinity/trinity/_utils/async_dispatch.py", line 22, in wrapper
    return await loop.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/eth/db/header.py", line 121, in get_canonical_block_header_by_number
    return self._get_canonical_block_header_by_number(self.db, block_number)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/eth/db/header.py", line 129, in _get_canonical_block_header_by_number
    canonical_block_hash = cls._get_canonical_block_hash(db, block_number)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/eth/db/header.py", line 112, in _get_canonical_block_hash
    encoded_key = db[number_to_hash_key]
  File "/home/salgado/src/snakecharmers/trinity/trinity/db/manager.py", line 283, in __getitem__
    self._socket.sendall(GET.value + len(key).to_bytes(LEN_BYTES, 'little') + key)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 168, in _run_on_asyncio
    result: Any = loop.run_until_complete(_do_async_fn(async_fn, args, to_parent, loop))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 160, in _do_async_fn
    return await async_fn_task
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 85, in _handle_coro
    return await coro_task
  File "/home/salgado/src/snakecharmers/trinity/trinity/extensibility/asyncio.py", line 51, in _do_run
    await self.do_run(event_bus)
  File "/home/salgado/src/snakecharmers/trinity/trinity/components/builtin/syncer/component.py", line 388, in do_run
    await wait_first([sync_task, asyncio.create_task(node_manager.wait_finished())])
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 441, in background_asyncio_service
    raise MultiError(
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/salgado/src/snakecharmers/trinity/trinity/sync/full/chain.py", line 825, in _run_receipt_download_batch
    self._receipt_peers.put_nowait(peer)
  File "/home/salgado/src/snakecharmers/trinity/trinity/sync/common/peers.py", line 82, in put_nowait
    self._waiting_peers.put_nowait(self._peer_wrapper(peer))
  File "/home/salgado/src/snakecharmers/trinity/trinity/_utils/datastructures.py", line 67, in __init__
    _comparable_val = self._order_fn(task)
  File "/home/salgado/src/snakecharmers/trinity/trinity/sync/common/peers.py", line 67, in _get_peer_rank
    for exchange in peer.get_chain_api().exchanges
  File "/home/salgado/src/snakecharmers/trinity/trinity/protocol/common/peer.py", line 100, in get_chain_api
    raise PeerConnectionLost(f"{self} is no longer alive")
p2p.exceptions.PeerConnectionLost: ETHPeer (eth, 63) <Session <Node(0x89d5ce@207.246.102.120)> 966865cc-2e5c-4bb1-aa5c-42ab30d48384> is no longer alive
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/salgado/src/snakecharmers/trinity/trinity/bootstrap.py", line 311, in run
    loop.run_until_complete(_run(boot_info, get_base_db_fn, component_manager_manager))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/salgado/src/snakecharmers/trinity/trinity/bootstrap.py", line 271, in _run
    await component_manager.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/salgado/src/snakecharmers/trinity/trinity/extensibility/component_manager.py", line 102, in run
    await wait_first(futures)
  File "/home/salgado/src/snakecharmers/trinity/p2p/logic.py", line 101, in wait_first
    raise done_future.exception()
  File "/home/salgado/src/snakecharmers/trinity/trinity/extensibility/asyncio.py", line 29, in _run_in_process
    return await run_in_process(async_fn, *args, subprocess_kwargs=subprocess_kwargs)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/main.py", line 411, in run_in_process
    return proc.get_result_or_raise()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/process.py", line 219, in get_result_or_raise
    raise self._error
p2p.exceptions.PeerConnectionLost: ETHPeer (eth, 63) <Session <Node(0x89d5ce@207.246.102.120)> 966865cc-2e5c-4bb1-aa5c-42ab30d48384> is no longer alive
```
