### ISSUE TITLE
Exception escaping from Discovery service

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#1894]
### What is wrong?

This leaked out of the Discovery service

```
   ERROR  2020-07-14 15:29:37,201      DiscoveryService  Unexpected error sending msg to ('127.0.0.1', 0)
Traceback (most recent call last):
  File "/home/piper/projects/trinity/p2p/discovery.py", line 724, in _sendto
    await self.socket.sendto(msg, (ip, port))
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/trio/_socket.py", line 754, in sendto
    return await self._nonblocking_helper(
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/trio/_socket.py", line 589, in _nonblocking_helper
    return fn(self._sock, *args, **kwargs)
OSError: [Errno 22] Invalid argument
```

I suspect it is because it's trying to send to port 0

### How can it be fixed

Might need to add some small validation to disallow this.

**Comment by gsalgado** [comment]
This is just a logged exception.  I think what we need is to find out why we have a node with port 0 in our records.  Since the IP is localhost, I wonder if you were connecting two local instances?  Otherwise we might be trying to talk to ourselves...
