### ISSUE TITLE
Remove stack trace from RPC exception warnings

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1913]
### What is wrong?

When finding #1912 , @stobiewan also reported (in gitter) that sync halted:
```
trying to read the chain id was enough to stop trinity syncing...
/trinity/trinity/rpc/main.py", line 105, in _lookup_method
    raise ValueError("Method not implemented: %r" % rpc_method)
ValueError: Method not implemented: 'eth_chainId'
trinity kept running after that but did nothing but NAT port forwarding.
```

That's definitely not supposed to happen. All exceptions are supposed to be caught and returned to the RPC caller as a string, and not be re-raised (or cause any other havoc).

### How can it be fixed

TBD

**Comment by carver** [comment]
This might belong in a first stable milestone instead, but we can demote it from beta when we groom the backlog. (and have created a stable milestone)

**Comment by cburgdorf** [comment]
I can't confirm this from my own test. The sync seems to move on unaffected.

```
    INFO  2020-07-21 11:05:58,913   BaseBodyChainSyncer  blks=1744  txs=507    bps=54   tps=28    elapsed=5.0  head=#54673 a49e..ea4f  age=4y11m1w
 WARNING  2020-07-21 11:05:59,691             RPCServer  RPC method caused exception
Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/rpc/main.py", line 103, in _lookup_method
    return getattr(module, method_name)
AttributeError: 'Eth' object has no attribute 'chainid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/rpc/main.py", line 120, in _get_result
    method = self._lookup_method(request['method'])
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/rpc/main.py", line 105, in _lookup_method
    raise ValueError("Method not implemented: %r" % rpc_method)
ValueError: Method not implemented: 'eth_chainid'
    INFO  2020-07-21 11:05:59,805        SkeletonSyncer  Unable to find common ancestor betwen our chain and ETHPeer (eth, 63) <Session <Node(0x08c094@139.5.203.2)> a04eb2bd-653a-4229-a102-a99176c9d124>
    INFO  2020-07-21 11:06:03,914   BaseBodyChainSyncer  blks=852   txs=444    bps=60   tps=31    elapsed=5.0  head=#55525 b1e2..1e50  age=4y11m1w
    INFO  2020-07-21 11:06:04,090  HeaderChainGapSyncer  Imported 388 gap headers from <BlockHeader #593406 8f21d78a> to <BlockHeader #593793 bfebc650> in 0.67 seconds,
    INFO  2020-07-21 11:06:05,093        SkeletonSyncer  Unable to find common ancestor betwen our chain and ETHPeer (eth, 63) <Session <Node(0x08c094@139.5.203.2)> a04eb2bd-653a-4229-a102-a99176c9d124>
    INFO  2020-07-21 11:06:06,630  HeaderChainGapSyncer  Imported 388 gap headers from <BlockHeader #593794 0b8f5c57> to <BlockHeader #594181 2525e7d9> in 0.51 seconds,
    INFO  2020-07-21 11:06:06,810  HeaderChainGapSyncer  Imported 194 gap headers from <BlockHeader #594182 c449f2c5> to <BlockHeader #594375 7c7f0b6a> in 0.17 seconds,
    INFO  2020-07-21 11:06:08,914   BaseBodyChainSyncer  blks=1712  txs=701    bps=74   tps=36    elapsed=5.0  head=#57237 f717..b092  age=4y11m1w
    INFO  2020-07-21 11:06:10,623        SkeletonSyncer  Unable to find common ancestor betwen our chain and ETHPeer (eth, 63) <Session <Node(0x08c094@139.5.203.2)> a04eb2bd-653a-4229-a102-a99176c9d124>
    INFO  2020-07-21 11:06:11,067  HeaderChainGapSyncer  Imported 970 gap headers from <BlockHeader #594376 47bb656f> to <BlockHeader #595345 6c2ca3bf> in 1.58 seconds,
    INFO  2020-07-21 11:06:11,723  HeaderChainGapSyncer  Imported 194 gap headers from <BlockHeader #595346 882877e4> to <BlockHeader #595539 871588e6> in 0.64 seconds,
    INFO  2020-07-21 11:06:12,221        SkeletonSyncer  Unable to find common ancestor betwen our chain and ETHPeer (eth, 63) <Session <Node(0x08c094@139.5.203.2)> a04eb2bd-653a-4229-a102-a99176c9d124>
    INFO  2020-07-21 11:06:13,915   BaseBodyChainSyncer  blks=1410  txs=238    bps=84   tps=37    elapsed=5.0  head=#58647 2b77..d48b  age=4y11m1w
    INFO  2020-07-21 11:06:15,058  HeaderChainGapSyncer  Imported 776 gap headers from <BlockHeader #595540 72f13bae> to <BlockHeader #596315 d22d712c> in 2.35 seconds,

```

I think it's debatable if we really need the traceback in the logged warning (I think it may even contribute to the perception of "this broke it") but I don't think it causes any havoc to other running parts of Trinity.

Here is the code that catches the exception.

https://github.com/ethereum/trinity/blob/fc6cea3b866924ef46b325f8874b4a1dd0d25bda/trinity/rpc/main.py#L142-L146

Notice that there does exist an `if debug` branch that would re-raise the error but it looks like that code is never exercised. I will add that this area of Trinity is still one that has received less attention and the code is quite a bit old.

**Comment by carver** [comment]
Yeah, I think the `debug` flag is only ever something that I flipped on during local testing. :+1: to remove the `exc_info=True`. I'd say we can close this issue when that's done.
