### ISSUE TITLE
Sync trinity and py-evm versions

### ISSUE THREAD

**Issue by rayrapetyan** [ethereum/trinity#194]
* py-evm Version: any

### What is wrong?
Before segregating trinity and py-evm development process was straightforward - checkout code from git and go ahead with making changes \ debugging any part of the project.

After segregating trinity's required py-evm version and py-evm version from master branch are almost always in a conflict, therefore trinity fails to start with a py-evm built from the master.

### How can it be fixed
There should be some better way, but for now I could suggest making py-evm dependency less strict, e.g. using `"py-evm>=0.2,<1.0.0""` instead of `"py-evm==0.2.0a38"`

**Comment by pipermerriam** [comment]
I think it just means a slower dev process requiring a py-evm release prior to the trinity side being mergable.

Ignoring the ethereum2.0 stuff, I'll be curious to see how often this is actually needed and whether py-evm becomes sufficiently stable/functional that we mostly don't run into this problem.

**Comment by rayrapetyan** [comment]
> For local development, if you want to hack on Py-EVM and then put that version to work in Trinity, I believe the best practice is to install it locally via pip install -e /path/to/py-evm.

Could you clarify. I've checked out master branch of py-evm, installed it using: `pip install -e .\[dev\]` and immediately get: `trinity 0.1.0a20 has requirement py-evm==0.2.0a38, but you'll have py-evm 0.2.0a40 which is incompatible.` error at the end.

**Comment by cburgdorf** [comment]
Oh you're correct! I think there's an issue. But just do be clear, here's the workflow that I'm describing (assuming we start on a fresh system)

1. Clone Trinity
2. Go to Trinity directory and run `pip install -e .[dev]`
3. Clone Py-EVM
4. Go to Py-EVM directory and run `pip install -e .[dev]`
5. Now, to work on a Py-EVM feature and run Trinity against this **local** `Py-EVM` version, go to the Trinity directory and run `pip install -e /path/to/py-evm/on/my/system`

But you are correct, that this will immediately give you an error 

>Trinity 0.1.0a20 has requirement py-evm==0.2.0a38, but you'll have py-evm 0.2.0a40 which is incompatible.

At first, I thought this wouldn't matter as I assumed it is only a warning and it doesn't matter as you'll end up with a locally linked `py-evm` anyway but it appears you can not run `trinity` with that version conflict.

So, running trinity against this locally linked `py-evm` version does indeed fail.

```
$ trinity
Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (py-evm 0.2.0a40 (/home/cburgdorf/Documents/hacking/ef/py-evm), Requirement.parse('py-evm==0.2.0a38'), {'trinity'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/bin/trinity", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'py-evm==0.2.0a38' distribution was not found and is required by trinity
```

So, it does indeed not work unless you manually change the version number, which I agree, is a bad developer UX.

However, I suspect that if we don't pin trinity to a specific version, we'll see this resulting in runtime bugs sooner than later. I don't have a good answer for that.

**Comment by carver** [comment]
This is at least temporarily resolved. It's also only a problem until py-evm stabilizes, which should be sometime this year. Then, the requirement will loosen up a bit so that we can do patch releases without `trinity` warning us.
