### ISSUE TITLE
Enabling metrics crashes the client

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#1942]
### What is wrong?

It looks like we are using `asyncio` within the `trio` async context which is throwing an exception. 

```
<bound method TrioIsolatedComponent._do_run of <trinity.components.builtin.metrics.component.MetricsComponent object at 0x7f9f705b9730>> raised an unexpected exception
Traceback (most recent call last):
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 205, in run_process
    runner(async_fn, args, to_parent)
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child_trio.py", line 63, in _run_on_trio
    result = trio.run(_do_async_fn, async_fn, args, to_parent)
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/trio/_core/_run.py", line 1804, in run
    raise runner.main_task_outcome.error
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child_trio.py", line 55, in _do_async_fn
    result = await async_fn(*args)
  File "/home/piper/projects/trinity/trinity/extensibility/trio.py", line 69, in _do_run
    nursery.cancel_scope.cancel()
  File "/home/piper/python-environments/trinity/lib/python3.8/site-packages/trio/_core/_run.py", line 730, in __aexit__
    raise combined_error_from_nursery
  File "/home/piper/projects/trinity/trinity/extensibility/trio.py", line 50, in run_process
    await self.do_run(event_bus)
  File "/home/piper/projects/trinity/trinity/components/builtin/metrics/component.py", line 159, in do_run
    await run_background_trio_services([
  File "/home/piper/projects/trinity/trinity/_utils/services.py", line 20, in run_background_trio_services
    await _run_background_services(services, background_trio_service)
  File "/home/piper/projects/trinity/trinity/_utils/services.py", line 33, in _run_background_services
    await wait_first([
  File "/home/piper/projects/trinity/trinity/_utils/services.py", line 34, in <listcomp>
    asyncio.create_task(manager.wait_finished())
  File "/home/piper/.pyenv/versions/3.8.3/lib/python3.8/asyncio/tasks.py", line 381, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
```

### How can it be fixed

Looks like using `wait_first` inside of `_run_background_services` is the culprit.

**Comment by cburgdorf** [comment]
I'm 99.9999 % sure that is fixed in latest master but feel free to re-open if you insist it isn't :sweat_smile:

**Comment by pipermerriam** [comment]
indeed it is.  :facepalm:
