### ISSUE TITLE
TaskQueue complete can raise a QueueFull

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1972]
* Trinity version: cade65ccb9922985d44e8a4baec24c39354c3d00

### What is wrong?

Got this exception in local testing
```
Traceback (most recent call last):
  File "/home/jcarver/code/async-service/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/jcarver/code/async-service/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/jcarver/code/async-service/async_service/asyncio.py", line 246, in run
    for _, exc_value, exc_tb in self._errors
  File "/home/jcarver/code/async-service/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/jcarver/code/async-service/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/jcarver/code/trinity/trinity/sync/beam/state.py", line ???, in _match_predictive_node_requests_to_peers
    ???
  File "/home/jcarver/code/trinity/trinity/_utils/datastructures.py", line 262, in complete
    self._open_queue.put_nowait(self._task_wrapper(task))
  File "/usr/lib/python3.7/asyncio/queues.py", line 144, in put_nowait
    raise QueueFull
asyncio.queues.QueueFull
```

It seems that this comment's claim is not true:
https://github.com/ethereum/trinity/blob/cade65ccb9922985d44e8a4baec24c39354c3d00/trinity/_utils/datastructures.py#L261-L262
### How can it be fixed

:man_shrugging: I will look into it

**Comment by carver** [comment]
Well, I couldn't spot why it was happening with a code review. I think the simplest solution is to make `complete()` async and just `await open_queue.put(...)`. It's not too painful a change. Will take it on tomorrow.
