### ISSUE TITLE
SyncerComponent crashes with UnknownAPI: No API registered for the name 'eth'

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1973]
```
<bound method AsyncioIsolatedComponent._do_run of <trinity.components.builtin.syncer.component.SyncerComponent object at 0x7f7cc900e8b0>> raised an unexpected exception
Traceback (most recent call last):
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 205, in run_process
    runner(async_fn, args, to_parent)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 168, in _run_on_asyncio
    result: Any = loop.run_until_complete(_do_async_fn(async_fn, args, to_parent, loop))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 160, in _do_async_fn
    return await async_fn_task
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 85, in _handle_coro
    return await coro_task
  File "/home/salgado/src/snakecharmers/trinity/trinity/extensibility/asyncio.py", line 72, in _do_run
    await self.do_run(event_bus)
  File "/home/salgado/src/snakecharmers/trinity/trinity/components/builtin/syncer/component.py", line 378, in do_run
    await wait_first([sync_task, node_manager_task])
  File "/home/salgado/src/snakecharmers/trinity/p2p/asyncio_utils.py", line 48, in wait_first
    raise done_task.exception()
  File "/home/salgado/src/snakecharmers/trinity/trinity/components/builtin/syncer/component.py", line 386, in launch_sync
    await strategy.sync(
  File "/home/salgado/src/snakecharmers/trinity/trinity/components/builtin/syncer/component.py", line 222, in sync
    await manager.wait_finished()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 441, in background_asyncio_service
    raise MultiError(
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/salgado/src/snakecharmers/trinity/trinity/sync/common/headers.py", line 956, in run
    await self._build_skeleton()
  File "/home/salgado/src/snakecharmers/trinity/trinity/sync/common/headers.py", line 963, in _build_skeleton
    async for peer in self._tip_monitor.wait_tip_info():
  File "/home/salgado/src/snakecharmers/trinity/trinity/protocol/common/monitors.py", line 52, in wait_tip_info
    highest_td_peer = self._peer_pool.highest_td_peer
  File "/home/salgado/src/snakecharmers/trinity/trinity/protocol/common/peer.py", line 262, in highest_td_peer
    peers_by_td = groupby(td_getter, peers)
  File "cytoolz/itertoolz.pyx", line 118, in cytoolz.itertoolz.groupby
  File "cytoolz/itertoolz.pyx", line 149, in cytoolz.itertoolz.groupby
  File "cytoolz/functoolz.pyx", line 838, in cytoolz.functoolz.excepts.__call__
  File "/home/salgado/src/snakecharmers/trinity/trinity/protocol/common/api.py", line 66, in head_td
    return self._tracker.head_td
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/salgado/src/snakecharmers/trinity/trinity/protocol/common/api.py", line 61, in _tracker
    api = choose_eth_or_les_api(self.connection)
  File "/home/salgado/src/snakecharmers/trinity/trinity/protocol/common/api.py", line 31, in choose_eth_or_les_api
    return connection.get_logic(ETHV63API.name, ETHV63API)
  File "/home/salgado/src/snakecharmers/trinity/p2p/connection.py", line 325, in get_logic
    raise UnknownAPI(f"No API registered for the name '{name}'")
p2p.exceptions.UnknownAPI: No API registered for the name 'eth'
```

**Comment by gsalgado** [comment]
I think we may be missing a call to `Multiplexer.close()` when a connection is terminated. We used to close the multiplexer at the end of `Connection.run()`: https://github.com/ethereum/trinity/commit/49f233d5c144afbcb7f1cccfdabd3df04e026ea7#diff-e7941748edce5bb431bc060d8f08fb0aL154-L155

But now we only do that when the connection is GCed: https://github.com/ethereum/trinity/commit/49f233d5c144afbcb7f1cccfdabd3df04e026ea7#diff-e7941748edce5bb431bc060d8f08fb0aR135-R140

So this could be caused by a Peer/Connection that is no longer running but for which the multiplexer/transport hasn't been closed yet. Because of that, `Connection.has_logic()` is not raising a `PeerConnectionLost`: it only does that when the multiplexer's `.is_closing` is True

**Comment by gsalgado** [comment]
Unfortunately my hypothesis above doesn't seem to be possible as `Connection.run()` ensures the multiplexer is closed by calling `wait_streaming_finished()`
