### ISSUE TITLE
Syncing from checkpoint too close to tip will crash without user friendly error.

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1998]
### What is wrong?

I ran into a fatal crash when trying to sync Görli from a checkpoint.

Run: `trinity --goerli -sync-from-checkpoint eth://block/byhash/0x69ff653c3c46ab62cf4b678695b0b31a9e00579287befb3afaab5fcaf74a45ac?score=4,773,702`

Right at the moment where we want to start beamsyncing I'm getting this:

```
    INFO  2020-08-27 11:16:42,556     HeaderOnlyPersist  Imported 300 headers in 0.21 seconds, new head: <BlockHeader #3296506 00c5dfbe>
    INFO  2020-08-27 11:16:43,109     HeaderOnlyPersist  Imported 4 headers in 0.00 seconds, new head: <BlockHeader #3296510 d3950d6e>
    INFO  2020-08-27 11:16:43,199     HeaderOnlyPersist  Imported 6 headers in 0.00 seconds, new head: <BlockHeader #3296516 eda94f91>
    INFO  2020-08-27 11:16:43,314     HeaderOnlyPersist  Imported 4 headers in 0.01 seconds, new head: <BlockHeader #3296520 a8e256ba>
    INFO  2020-08-27 11:16:43,438     HeaderOnlyPersist  Imported 22 headers in 0.01 seconds, new head: <BlockHeader #3296542 b26afc40>
    INFO  2020-08-27 11:16:43,644     HeaderOnlyPersist  Imported 34 headers in 0.03 seconds, new head: <BlockHeader #3296576 92f4b5fc>
    INFO  2020-08-27 11:16:43,808     HeaderOnlyPersist  Imported 18 headers in 0.01 seconds, new head: <BlockHeader #3296594 c52ce58b>
    INFO  2020-08-27 11:16:44,171     HeaderOnlyPersist  Caught up to skeleton peer. Switching to beam mode at <BlockHeader #3296827 245a7842>
    INFO  2020-08-27 11:16:44,376            BeamSyncer  Downloading 8 block bodies for uncle validation, before <BlockHeader #3296827 245a7842>
    INFO  2020-08-27 11:16:44,386            BeamSyncer  Getting recent block data for uncle validation
    INFO  2020-08-27 11:16:44,618            BeamSyncer  Have all data needed for Beam validation, continuing...
    INFO  2020-08-27 11:16:44,619  HeaderLaunchpointSyncer  Choosing ['<BlockHeader #3296827 245a7842>'] as launchpoint headers to sync from
    INFO  2020-08-27 11:16:44,623        BeamDownloader  Starting beam state sync
    INFO  2020-08-27 11:16:44,626  HeaderChainGapSyncer  Launching from 41794
    INFO  2020-08-27 11:16:44,718            FullServer  TCP Listener finished, cancelling Server
<bound method AsyncioIsolatedComponent._do_run of <trinity.components.builtin.syncer.component.SyncerComponent object at 0x7fb760cb9670>> raised an unexpected exception
Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/eth/db/header.py", line 112, in _get_canonical_block_hash
    encoded_key = db[number_to_hash_key]
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/db/manager.py", line 291, in __getitem__
    raise KeyError(key)
KeyError: b'block-number-to-hash:3196818'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 205, in run_process
    runner(async_fn, args, to_parent)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 168, in _run_on_asyncio
    result: Any = loop.run_until_complete(_do_async_fn(async_fn, args, to_parent, loop))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 160, in _do_async_fn
    return await async_fn_task
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 85, in _handle_coro
    return await coro_task
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/extensibility/asyncio.py", line 71, in _do_run
    await wait_first(
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/asyncio_utils.py", line 69, in wait_first
    raise done_task.exception()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/components/builtin/syncer/component.py", line 378, in do_run
    await wait_first([sync_task, node_manager_task], max_wait_after_cancellation=2)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/asyncio_utils.py", line 69, in wait_first
    raise done_task.exception()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/components/builtin/syncer/component.py", line 386, in launch_sync
    await strategy.sync(
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/components/builtin/syncer/component.py", line 222, in sync
    await manager.wait_finished()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/asyncio.py", line 441, in background_asyncio_service
    raise MultiError(
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/sync/beam/chain.py", line 531, in run
    await self._setup_for_next_gap()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/sync/beam/chain.py", line 452, in _setup_for_next_gap
    _starting_tip = await self._db.coro_get_canonical_block_header_by_number(start_num)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/_utils/async_dispatch.py", line 22, in wrapper
    return await loop.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/eth/db/header.py", line 121, in get_canonical_block_header_by_number
    return self._get_canonical_block_header_by_number(self.db, block_number)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/eth/db/header.py", line 129, in _get_canonical_block_header_by_number
    canonical_block_hash = cls._get_canonical_block_hash(db, block_number)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/eth/db/header.py", line 114, in _get_canonical_block_hash
    raise HeaderNotFound(
eth.exceptions.HeaderNotFound: No canonical header for block number #3196818
sys:1: ResourceWarning: unclosed <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 30303)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
    INFO  2020-08-27 11:16:47,940      ComponentManager  Stopping components
    INFO  2020-08-27 11:16:47,940      ComponentManager  Components stopped.
    INFO  2020-08-27 11:16:47,943               trinity  Terminating DB process
 WARNING  2020-08-27 11:16:47,943  asyncio_run_in_process  Child process pid=87988 failed to exit cleanly.  Sending SIGKILL
asyncio_run_in_process._utils.RemoteTraceback: 
""" (exception from process: 88007)
Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/eth/db/header.py", line 112, in _get_canonical_block_hash
    encoded_key = db[number_to_hash_key]
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/db/manager.py", line 291, in __getitem__
    raise KeyError(key)
KeyError: b'block-number-to-hash:3196818'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 168, in _run_on_asyncio
    result: Any = loop.run_until_complete(_do_async_fn(async_fn, args, to_parent, loop))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 160, in _do_async_fn
    return await async_fn_task
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 85, in _handle_coro
    return await coro_task
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/extensibility/asyncio.py", line 71, in _do_run
    await wait_first(
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/asyncio_utils.py", line 69, in wait_first
    raise done_task.exception()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/components/builtin/syncer/component.py", line 378, in do_run
    await wait_first([sync_task, node_manager_task], max_wait_after_cancellation=2)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/asyncio_utils.py", line 69, in wait_first
    raise done_task.exception()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/components/builtin/syncer/component.py", line 386, in launch_sync
    await strategy.sync(
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/components/builtin/syncer/component.py", line 222, in sync
    await manager.wait_finished()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/asyncio.py", line 441, in background_asyncio_service
    raise MultiError(
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/sync/beam/chain.py", line 531, in run
    await self._setup_for_next_gap()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/sync/beam/chain.py", line 452, in _setup_for_next_gap
    _starting_tip = await self._db.coro_get_canonical_block_header_by_number(start_num)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/_utils/async_dispatch.py", line 22, in wrapper
    return await loop.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/eth/db/header.py", line 121, in get_canonical_block_header_by_number
    return self._get_canonical_block_header_by_number(self.db, block_number)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/eth/db/header.py", line 129, in _get_canonical_block_header_by_number
    canonical_block_hash = cls._get_canonical_block_hash(db, block_number)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/eth/db/header.py", line 114, in _get_canonical_block_hash
    raise HeaderNotFound(
eth.exceptions.HeaderNotFound: No canonical header for block number #3196818
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/asyncio_run_in_process/main.py", line 323, in _open_in_process
    yield proc
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/bootstrap.py", line 275, in _run
    await component_manager.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/extensibility/component_manager.py", line 105, in run
    await wait_first(tasks, max_wait_after_cancellation=10)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/asyncio_utils.py", line 69, in wait_first
    raise done_task.exception()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/extensibility/asyncio.py", line 21, in run_in_process
    await run_in_process(self._do_run, subprocess_kwargs=self.get_subprocess_kwargs())
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/asyncio_run_in_process/main.py", line 411, in run_in_process
    return proc.get_result_or_raise()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/asyncio_run_in_process/process.py", line 219, in get_result_or_raise
    raise self._error
eth.exceptions.HeaderNotFound: No canonical header for block number #3196818
   ERROR  2020-08-27 11:16:47,958                  root  Error during trinity run
asyncio_run_in_process._utils.RemoteTraceback: 
""" (exception from process: 88007)
Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/eth/db/header.py", line 112, in _get_canonical_block_hash
    encoded_key = db[number_to_hash_key]
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/db/manager.py", line 291, in __getitem__
    raise KeyError(key)
KeyError: b'block-number-to-hash:3196818'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 168, in _run_on_asyncio
    result: Any = loop.run_until_complete(_do_async_fn(async_fn, args, to_parent, loop))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 160, in _do_async_fn
    return await async_fn_task
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 85, in _handle_coro
    return await coro_task
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/extensibility/asyncio.py", line 71, in _do_run
    await wait_first(
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/asyncio_utils.py", line 69, in wait_first
    raise done_task.exception()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/components/builtin/syncer/component.py", line 378, in do_run
    await wait_first([sync_task, node_manager_task], max_wait_after_cancellation=2)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/asyncio_utils.py", line 69, in wait_first
    raise done_task.exception()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/components/builtin/syncer/component.py", line 386, in launch_sync
    await strategy.sync(
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/components/builtin/syncer/component.py", line 222, in sync
    await manager.wait_finished()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/asyncio.py", line 441, in background_asyncio_service
    raise MultiError(
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/sync/beam/chain.py", line 531, in run
    await self._setup_for_next_gap()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/sync/beam/chain.py", line 452, in _setup_for_next_gap
    _starting_tip = await self._db.coro_get_canonical_block_header_by_number(start_num)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/_utils/async_dispatch.py", line 22, in wrapper
    return await loop.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/eth/db/header.py", line 121, in get_canonical_block_header_by_number
    return self._get_canonical_block_header_by_number(self.db, block_number)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/eth/db/header.py", line 129, in _get_canonical_block_header_by_number
    canonical_block_hash = cls._get_canonical_block_hash(db, block_number)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/eth/db/header.py", line 114, in _get_canonical_block_hash
    raise HeaderNotFound(
eth.exceptions.HeaderNotFound: No canonical header for block number #3196818
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/bootstrap.py", line 315, in run
    loop.run_until_complete(_run(boot_info, get_base_db_fn, component_manager_manager))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/bootstrap.py", line 275, in _run
    await component_manager.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/asyncio.py", line 243, in run
    raise MultiError(
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/extensibility/component_manager.py", line 105, in run
    await wait_first(tasks, max_wait_after_cancellation=10)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/asyncio_utils.py", line 69, in wait_first
    raise done_task.exception()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/trinity/extensibility/asyncio.py", line 21, in run_in_process
    await run_in_process(self._do_run, subprocess_kwargs=self.get_subprocess_kwargs())
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/asyncio_run_in_process/main.py", line 411, in run_in_process
    return proc.get_result_or_raise()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.8/site-packages/asyncio_run_in_process/process.py", line 219, in get_result_or_raise
    raise self._error
eth.exceptions.HeaderNotFound: No canonical header for block number #3196818
    INFO  2020-08-27 11:16:47,959                  root  Shutting down Trinity
 WARNING  2020-08-27 11:16:47,961                  root  Removed dangling IPC socket file  /tmp/tttrinityyyys/goerli/ipcs-eth1/bbeam-sync-chain-execution.ipc
 WARNING  2020-08-27 11:16:47,963                  root  Removed dangling IPC socket file  /tmp/tttrinityyyys/goerli/ipcs-eth1/bjson-rpc-api.ipc
 WARNING  2020-08-27 11:16:47,963                  root  Removed dangling IPC socket file  /tmp/tttrinityyyys/goerli/ipcs-eth1/bbeam-sync-chain-preview-1.ipc
 WARNING  2020-08-27 11:16:47,963                  root  Removed dangling IPC socket file  /tmp/tttrinityyyys/goerli/ipcs-eth1/bbeam-sync-chain-preview-3.ipc
 WARNING  2020-08-27 11:16:47,964                  root  Removed dangling IPC socket file  /tmp/tttrinityyyys/goerli/ipcs-eth1/logging.ipc
 WARNING  2020-08-27 11:16:47,964                  root  Removed dangling IPC socket file  /tmp/tttrinityyyys/goerli/ipcs-eth1/network-db.ipc
 WARNING  2020-08-27 11:16:47,964                  root  Removed dangling IPC socket file  /tmp/tttrinityyyys/goerli/ipcs-eth1/btxcomponent.ipc
 WARNING  2020-08-27 11:16:47,965                  root  Removed dangling IPC socket file  /tmp/tttrinityyyys/goerli/ipcs-eth1/brequest-server.ipc
 WARNING  2020-08-27 11:16:47,965                  root  Removed dangling IPC socket file  /tmp/tttrinityyyys/goerli/ipcs-eth1/bbeam-sync-chain-preview-0.ipc
 WARNING  2020-08-27 11:16:47,965                  root  Removed dangling IPC socket file  /tmp/tttrinityyyys/goerli/ipcs-eth1/bbeam-sync-chain-preview-2.ipc

```

The reason this happened is because Trinity tried to access a block that was *before* my choosen checkpoint. When I tried it with a checkpoint that was more than 60000 blocks away from the tip things work as expected.

### How can it be fixed

If the user chooses a checkpoint that is too close to the tip reject it with a friendly error method that tells the user to choose a checkpoint that is at least `n` blocks away from the tip.

**Comment by cburgdorf** [comment]
Oh, it just appeared to me that the checkpoint chosen was likely to close to the tip. It's block `3270000` and the reported missing blocks are before that (likely because of the 30k reorg lookback). So, I guess this isn't actually any new severe regression but rather a UX issue that's always been around. I will try to confirm that.

**Comment by cburgdorf** [comment]
Ok, confirmed. I changed title, description and labels accordingly.
