### ISSUE TITLE
RegularChainSyncer finishes unexpectedly 

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#219]
### What is wrong?

```
DEBUG  01-23 14:16:38                 Chain  IMPORTED_BLOCK: number 3307 | hash 0x69aced532616756c20071742c4890b84f9d35eba798df590b7f78ff5a0cb1e64
    INFO  01-23 14:16:38  RegularChainBodySyncer  Imported block 3307 (0 txs) in 0.76 seconds
   DEBUG  01-23 14:16:38               ETHPeer  Finished P2P handshake with <Node(0x4e95@176.9.28.175)>, using sub-protocol (eth, 63)
   DEBUG  01-23 14:16:39               ETHPeer  Disconnecting from remote peer <Node(0x4e95@176.9.28.175)>; reason: useless_peer
   DEBUG  01-23 14:16:39           ETHPeerPool  Could not complete handshake with <Node(0x4e95a1845288ab87ad799e2049b62427b650cf03450ced4be71277fa5cab0aa652aeb4304a65c6f7044e5f28c4d0d8de9c6c6b94c614bc01e9a9e5966e7d4517@176.9.28.175:30305)>: HandshakeFailure('ETHPeer <Node(0x4e95@176.9.28.175)> network (200625) does not match ours (1), disconnecting',)
   DEBUG  01-23 14:16:39        SkeletonSyncer  Requsting chain of headers from ETHPeer <Node(0x5030@120.143.183.152)> starting at #3649
   DEBUG  01-23 14:16:39  ETHHeaderChainSyncer  Skeleton syncer asserts that parent (9cfb..e003) of the first header (<BlockHeader #3307 69aced53>) is already present
   DEBUG  01-23 14:16:39  RegularChainBodySyncer  <coroutine object RegularChainBodySyncer._launch_prerequisite_tasks at 0x7f13e879d9e8> finished while <trinity.sync.full.chain.RegularChainBodySyncer object at 0x7f13e878e470> is still running, terminating as well
   DEBUG  01-23 14:16:39  RegularChainBodySyncer  Cancelling <trinity.sync.full.chain.RegularChainBodySyncer object at 0x7f13e878e470>
 WARNING  01-23 14:16:39  RegularChainBodySyncer  Task <coroutine object RegularChainBodySyncer._launch_prerequisite_tasks at 0x7f13e879d990> finished unexpectedly: Cannot prepare task <CompletionForBlockImportPrereqs(<BlockHeader #3307 69aced53>, done=set(), remaining={<BlockImportPrereqs.StoreBlockBodies: 1>})> with id b'i\xac\xedS&\x16ul \x07\x17B\xc4\x89\x0b\x84\xf9\xd3^\xbay\x8d\xf5\x90\xb7\xf7\x8f\xf5\xa0\xcb\x1ed' and dependency b'\x9c\xfb\xe0&\xdbt#\x9fD\xf8\xa2L\xb1Y\xa3].\xb9\xf5x\xd3P\x06\x9a\x04\xae\x05 7-\xe0\x03' before preparing its dependency
   DEBUG  01-23 14:16:39  RegularChainBodySyncer  Task failure traceback
Traceback (most recent call last):
  File "/home/ubuntu/trinity/p2p/service.py", line 141, in _run_task_wrapper
    await awaitable
  File "/home/ubuntu/trinity/p2p/service.py", line 160, in _run_daemon_task_wrapper
    await awaitable
  File "/home/ubuntu/trinity/trinity/sync/full/chain.py", line 851, in _launch_prerequisite_tasks
    self._block_import_tracker.register_tasks(headers)
  File "/home/ubuntu/trinity/trinity/_utils/datastructures.py", line 547, in register_tasks
    f"Cannot prepare task {prereq_tracker!r} with id {task_id} and "
trinity._utils.datastructures.MissingDependency: Cannot prepare task <CompletionForBlockImportPrereqs(<BlockHeader #3307 69aced53>, done=set(), remaining={<BlockImportPrereqs.StoreBlockBodies: 1>})> with id b'i\xac\xedS&\x16ul \x07\x17B\xc4\x89\x0b\x84\xf9\xd3^\xbay\x8d\xf5\x90\xb7\xf7\x8f\xf5\xa0\xcb\x1ed' and dependency b'\x9c\xfb\xe0&\xdbt#\x9fD\xf8\xa2L\xb1Y\xa3].\xb9\xf5x\xd3P\x06\x9a\x04\xae\x05 7-\xe0\x03' before preparing its dependency
   DEBUG  01-23 14:16:39  RegularChainBodySyncer  <trinity.sync.full.chain.RegularChainBodySyncer object at 0x7f13e878e470> cancelled, cleaning up...
   DEBUG  01-23 14:16:39  RegularChainBodySyncer  Waiting for tasks: [<Task pending coro=<BaseBodyChainSyncer._assign_body_download_to_peers() running at /home/ubuntu/trinity/p2p/service.py:141> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f13b85aa9d8>()]>>, <Task pending coro=<RegularChainBodySyncer._import_ready_blocks() running at /home/ubuntu/trinity/p2p/service.py:141> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f139ac942e8>()]>>]
   DEBUG  01-23 14:16:39  RegularChainBodySyncer  Pending block bodies call to ETHPeer <Node(0xbe04ca4fa27fab6992a2f04901f194346d74fb94965a4e3f455213b0d61489068c437bf48ef55f30270811f12911631b6247f1d524bf7020210fdbbe069c0bcf@47.52.206.86:32774)> future cancelled
   DEBUG  01-23 14:16:39  RegularChainBodySyncer  All tasks finished
   DEBUG  01-23 14:16:39  RegularChainBodySyncer  <trinity.sync.full.chain.RegularChainBodySyncer object at 0x7f13e878e470> halted cleanly
   DEBUG  01-23 14:16:39    RegularChainSyncer  <trinity.sync.full.chain.RegularChainBodySyncer object at 0x7f13e878e470> finished while <trinity.sync.full.chain.RegularChainSyncer object at 0x7f13f0374518> is still running, terminating as well
   DEBUG  01-23 14:16:39    RegularChainSyncer  Cancelling <trinity.sync.full.chain.RegularChainSyncer object at 0x7f13f0374518>
   DEBUG  01-23 14:16:39    RegularChainSyncer  <trinity.sync.full.chain.RegularChainSyncer object at 0x7f13f0374518> cancelled, cleaning up...
   DEBUG  01-23 14:16:39    RegularChainSyncer  Waiting for child services: [<trinity.protocol.eth.sync.ETHHeaderChainSyncer object at 0x7f13e8795128>, <trinity.sync.full.chain.RegularChainBodySyncer object at 0x7f13e878e470>]
   DEBUG  01-23 14:16:39      HeaderMeatSyncer  Service cancellation while fetching segment, dropping ETHPeer <Node(0x5030@120.143.183.152)> from queue
Traceback (most recent call last):
  File "/home/ubuntu/trinity/trinity/sync/common/headers.py", line 599, in _run_fetch_segment
    completed_headers = await peer.wait(self._fetch_segment(peer, parent_header, length))
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/ubuntu/trinity/venv/lib/python3.6/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/home/ubuntu/trinity/trinity/sync/common/headers.py", line 669, in _fetch_segment
    SEAL_CHECK_RANDOM_SAMPLE_RATE,
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/ubuntu/trinity/venv/lib/python3.6/site-packages/cancel_token/token.py", line 150, in cancellable_wait
    "Cancellation requested by {} token".format(self.triggered_token)
cancel_token.exceptions.OperationCancelled: Cancellation requested by RegularChainSyncer:FullChainSyncer:FullNode token
   DEBUG  01-23 14:16:39  ETHHeaderChainSyncer  <trinity.protocol.eth.sync.ETHHeaderChainSyncer object at 0x7f13e8795128> finished: Cancellation requested by RegularChainSyncer:FullChainSyncer:FullNode token
   DEBUG  01-23 14:16:39  ETHHeaderChainSyncer  Waiting for child services: [<trinity.sync.common.headers.HeaderMeatSyncer object at 0x7f13e8795a20>, <trinity.protocol.eth.monitors.ETHChainTipMonitor object at 0x7f13e8795438>, <trinity.sync.common.headers.SkeletonSyncer object at 0x7f13a86d8ef0>]
   DEBUG  01-23 14:16:39      HeaderMeatSyncer  <trinity.sync.common.headers.HeaderMeatSyncer object at 0x7f13e8795a20> finished: Cancellation requested by RegularChainSyncer:FullChainSyncer:FullNode token
   DEBUG  01-23 14:16:39      HeaderMeatSyncer  Waiting for tasks: [<Task pending coro=<HeaderMeatSyncer._run_fetch_segment() running at /home/ubuntu/trinity/p2p/service.py:141> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f13b840ebe8>()]>>, <Task pending coro=<HeaderMeatSyncer._run_fetch_segment() running at /home/ubuntu/trinity/p2p/service.py:141> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f139ac1ee58>()]>>, <Task pending coro=<HeaderMeatSyncer._display_stats() running at /home/ubuntu/trinity/p2p/service.py:141> wait_for=<Future finished result=None>>, <Task pending coro=<HeaderMeatSyncer._run_fetch_segment() running at /home/ubuntu/trinity/p2p/service.py:141> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f13e8849be8>()]>>]
    INFO  01-23 14:16:39  ETHHeaderChainSyncer  Skeleton sync with ETHPeer <Node(0x5030@120.143.183.152)> ended
   DEBUG  01-23 14:16:39    ETHChainTipMonitor  <trinity.protocol.eth.monitors.ETHChainTipMonitor object at 0x7f13e8795438> finished: Cancellation requested by ETHHeaderChainSyncer:RegularChainSyncer:FullChainSyncer:FullNode token
   DEBUG  01-23 14:16:39    ETHChainTipMonitor  Waiting for tasks: [<Task pending coro=<BaseChainTipMonitor._handle_msg_loop() running at /home/ubuntu/trinity/p2p/service.py:141> wait_for=<Future finished result=None>>]
   DEBUG  01-23 14:16:39        SkeletonSyncer  <trinity.sync.common.headers.SkeletonSyncer object at 0x7f13a86d8ef0> finished: Cancellation requested by ETHHeaderChainSyncer:RegularChainSyncer:FullChainSyncer:FullNode token
   DEBUG  01-23 14:16:39        SkeletonSyncer  Waiting for tasks: [<Task pending coro=<SkeletonSyncer._display_stats() running at /home/ubuntu/trinity/p2p/service.py:141> wait_for=<Future finished result=None>>]
   DEBUG  01-23 14:16:39               ETHPeer  Finished P2P handshake with <Node(0x1b08@116.62.216.210)>, using sub-protocol (eth, 63)
   DEBUG  01-23 14:16:39    ETHChainTipMonitor  All tasks finished
   DEBUG  01-23 14:16:39    ETHChainTipMonitor  <trinity.protocol.eth.monitors.ETHChainTipMonitor object at 0x7f13e8795438> halted cleanly
   DEBUG  01-23 14:16:39        SkeletonSyncer  All tasks finished
   DEBUG  01-23 14:16:39        SkeletonSyncer  <trinity.sync.common.headers.SkeletonSyncer object at 0x7f13a86d8ef0> halted cleanly
   DEBUG  01-23 14:16:39      HeaderMeatSyncer  Service cancellation while fetching segment, dropping ETHPeer <Node(0x0fa0@117.27.142.8)> from queue
Traceback (most recent call last):
  File "/home/ubuntu/trinity/trinity/sync/common/headers.py", line 599, in _run_fetch_segment
    completed_headers = await peer.wait(self._fetch_segment(peer, parent_header, length))
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/ubuntu/trinity/venv/lib/python3.6/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/home/ubuntu/trinity/trinity/sync/common/headers.py", line 669, in _fetch_segment
    SEAL_CHECK_RANDOM_SAMPLE_RATE,
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/ubuntu/trinity/venv/lib/python3.6/site-packages/cancel_token/token.py", line 150, in cancellable_wait
    "Cancellation requested by {} token".format(self.triggered_token)
cancel_token.exceptions.OperationCancelled: Cancellation requested by HeaderMeatSyncer:RegularChainSyncer:FullChainSyncer:FullNode token
   DEBUG  01-23 14:16:39      HeaderMeatSyncer  Service cancellation while fetching segment, dropping ETHPeer <Node(0xedf5@96.76.162.22)> from queue
Traceback (most recent call last):
  File "/home/ubuntu/trinity/trinity/sync/common/headers.py", line 599, in _run_fetch_segment
    completed_headers = await peer.wait(self._fetch_segment(peer, parent_header, length))
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/ubuntu/trinity/venv/lib/python3.6/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/home/ubuntu/trinity/trinity/sync/common/headers.py", line 669, in _fetch_segment
    SEAL_CHECK_RANDOM_SAMPLE_RATE,
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/ubuntu/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/ubuntu/trinity/venv/lib/python3.6/site-packages/cancel_token/token.py", line 150, in cancellable_wait
    "Cancellation requested by {} token".format(self.triggered_token)
cancel_token.exceptions.OperationCancelled: Cancellation requested by HeaderMeatSyncer:RegularChainSyncer:FullChainSyncer:FullNode token
   DEBUG  01-23 14:16:39           ETHPeerPool  Could not complete handshake with <Node(0x4768a1ed23f06525e5096bf2912cba8fdb7ccc305eceb048f3d70ebbfff5c12c1cdffaac76bcde238ffd50c380190b9aaf3bd53c7ffe2cb17ef3acb548a6cb1c@123.249.41.95:1779)>: UnreachablePeer("Can't reach <Node(0x4768a1ed23f06525e5096bf2912cba8fdb7ccc305eceb048f3d70ebbfff5c12c1cdffaac76bcde238ffd50c380190b9aaf3bd53c7ffe2cb17ef3acb548a6cb1c@123.249.41.95:1779)>",)
   DEBUG  01-23 14:16:39               ETHPeer  Finished (eth, 63) handshake with <Node(0x1b08@116.62.216.210)>
   DEBUG  01-23 14:16:39  ResponseCandidateStream  Launching <ResponseCandidateStream(ETHPeer <Node(0x1b08@116.62.216.210)>, <class 'trinity.protocol.eth.commands.BlockHeaders'>)>
   DEBUG  01-23 14:16:39              protocol  client > Frame(fin=True, opcode=1, data=b'{"emit": ["node-ping", {"clientTime": 1548252999401, "id": "snake charmers"}]}', rsv1=False, rsv2=False, rsv3=False)
   DEBUG  01-23 14:16:39              protocol  client > Frame(fin=True, opcode=1, data=b'{"emit": ["stats", {"stats": {"active": true, "uptime": 100, "peers": 4}, "id": "snake charmers"}]}', rsv1=False, rsv2=False, rsv3=False)
   DEBUG  01-23 14:16:39              protocol  client > Frame(fin=True, opcode=1, data=b'{"emit": ["block", {"block": {"number": 3307, "hash": "0x69aced532616756c20071742c4890b84f9d35eba798df590b7f78ff5a0cb1e64", "difficulty": 84818368219, "totalDifficulty": 140278320687421, "transactions": [], "uncles": []}, "id": "snake charmers"}]}', rsv1=False, rsv2=False, rsv3=False)
   DEBUG  01-23 14:16:39              protocol  client < Frame(fin=True, opcode=1, data=b'{"emit":["node-pong",{"clientTime":1548252999401,"serverTime":1548252999403}]}', rsv1=False, rsv2=False, rsv3=False)
   DEBUG  01-23 14:16:39              protocol  client > Frame(fin=True, opcode=1, data=b'{"emit": ["latency", {"latency": 18, "id": "snake charmers"}]}', rsv1=False, rsv2=False, rsv3=False)
   DEBUG  01-23 14:16:39  ResponseCandidateStream  Got unexpected BlockHeaders payload from ETHPeer <Node(0x5030@120.143.183.152)>
   DEBUG  01-23 14:16:39            FrontierVM  BLOCK REWARD: 5000000000000000000 -> b'\xbb{\x82\x87\xf3\xf0\xa93GJy\xea\xe4,\xbc\xa9wy\x11q'
   DEBUG  01-23 14:16:39                 Chain  IMPORTED_BLOCK: number 3308 | hash 0x18fe8f216f125981667548c1ed52b571be3a18daed0a09ceccef9ddcaba09776
   DEBUG  01-23 14:16:39      HeaderMeatSyncer  Timed out requesting 192 headers from ETHPeer <Node(0xbe04@47.52.206.86)>
   DEBUG  01-23 14:16:39      HeaderMeatSyncer  Pausing ETHPeer <Node(0xbe04@47.52.206.86)> for 15.0s, for sending 0 headers
   DEBUG  01-23 14:16:39      HeaderMeatSyncer  All tasks finished
   DEBUG  01-23 14:16:39      HeaderMeatSyncer  <trinity.sync.common.headers.HeaderMeatSyncer object at 0x7f13e8795a20> halted cleanly
   DEBUG  01-23 14:16:39  ETHHeaderChainSyncer  All child services finished
   DEBUG  01-23 14:16:39  ETHHeaderChainSyncer  <trinity.protocol.eth.sync.ETHHeaderChainSyncer object at 0x7f13e8795128> halted cleanly
   DEBUG  01-23 14:16:39    RegularChainSyncer  All child services finished
   DEBUG  01-23 14:16:39    RegularChainSyncer  <trinity.sync.full.chain.RegularChainSyncer object at 0x7f13f0374518> halted cleanly
   DEBUG  01-23 14:16:39       FullChainSyncer  <trinity.sync.full.service.FullChainSyncer object at 0x7f13e933d9e8> had nothing left to do, ceasing operation...
   DEBUG  01-23 14:16:39       FullChainSyncer  <trinity.sync.full.service.FullChainSyncer object at 0x7f13e933d9e8> halted cleanly
   ERROR  01-23 14:16:39  BasePlugin#Syncer Plugin  Sync ended unexpectedly. Shutting down trinity

```

Notice that this is from `--sync-mode full` provided by #155 

### How can it be fixed

Needs investigation

**Comment by pipermerriam** [comment]
This looks a lot like the very confusing bug we encountered a while back with an `OperationCancelled` exception being raised from another service causing the local service to shutdown.

Said differently.

- Let `A` be a service
- Let `B` be a service such that cancellation of service `B`'s cancel token should not effect service `A`

Somewhere service `A` is awaiting a method from service `B`.  When service `B` exits, the awaited method ends up raising an `OperationCancelled`.  Service `A` sees an `OperationCancelled` and interprets that as if it's own cancel token was triggered and shuts itself down.

Assuming this is in fact this bug, I think worth re-exploring how we can prevent this from happening by ensuring that `OperationCancelled` exceptions from unrelated cancel tokens do not propagate in this way.

**Comment by cburgdorf** [comment]
It seems to be related to the `trinity._utils.datastructures.MissingDependency` error raised earlier. That's why I tried if #220 would fix it but apparently it did not. //cc @carver

**Comment by carver** [comment]
Huh, yeah, this is a pretty strange scenario. It suggests that block 3307 is trying to be imported before its parent (block hash `b'\x9c\xfb\xe`) was found:

`trinity._utils.datastructures.MissingDependency: Cannot prepare task <CompletionForBlockImportPrereqs(<BlockHeader #3307 69aced53>, done=set(), remaining={<BlockImportPrereqs.StoreBlockBodies: 1>})> with id b'i\xac\xedS&\x16ul \x07\x17B\xc4\x89\x0b\x84\xf9\xd3^\xbay\x8d\xf5\x90\xb7\xf7\x8f\xf5\xa0\xcb\x1ed' and dependency b'\x9c\xfb\xe0&\xdbt#\x9fD\xf8\xa2L\xb1Y\xa3].\xb9\xf5x\xd3P\x06\x9a\x04\xae\x05 7-\xe0\x03' before preparing its dependency
`

Seems like maybe something else went wrong earlier that we didn't catch.

**Comment by carver** [comment]
The handling code of regular chain syncer got changed pretty significantly in #446 -- I suspect this got fixed. If someone sees it again, please say so. I'll optimistically close for now, and reopen if it pops up again.
