### ISSUE TITLE
Error during snappy decompression

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#292]
### What is wrong?

```
b'\x1b[1m\x1b[31m   ERROR  02-19 09:50:08           ETHPeerPool  Unexpected error during auth/p2p handshake with <Node(0x865a63255b3bb68023b6bffd5095118fcc13e79dcf014fe4e47e065c350c7cc72af2e53eff895f11ba1bbb6a2b33271c1116ee870f266618eadfc2e78aa7349c@52.176.100.77:30303)>\n'
b'Traceback (most recent call last):\n'
b'  File "/home/circleci/repo/p2p/peer_pool.py", line 255, in connect\n'
b'    peer = await self.wait(handshake(remote, self.get_peer_factory()))\n'
b'  File "/home/circleci/repo/p2p/cancellable.py", line 20, in wait\n'
b'    return await self.wait_first(awaitable, token=token, timeout=timeout)\n'
b'  File "/home/circleci/repo/p2p/cancellable.py", line 42, in wait_first\n'
b'    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)\n'
b'  File "/home/circleci/repo/.tox/py36-long_run_integration/lib/python3.6/site-packages/cancel_token/token.py", line 152, in cancellable_wait\n'
b'    return done.pop().result()\n'
b'  File "/home/circleci/repo/p2p/peer.py", line 128, in handshake\n'
b'    await peer.do_sub_proto_handshake()\n'
b'  File "/home/circleci/repo/p2p/peer.py", line 321, in do_sub_proto_handshake\n'
b'    cmd, msg = await self.read_msg()\n'
b'  File "/home/circleci/repo/p2p/peer.py", line 460, in read_msg\n'
b'    decoded_msg = cast(Dict[str, Any], cmd.decode(msg))\n'
b'  File "/home/circleci/repo/p2p/p2p_proto.py", line 78, in decode\n'
b'    raw_decoded = cast(Dict[str, int], super().decode(data))\n'
b'  File "/home/circleci/repo/p2p/protocol.py", line 123, in decode\n'
b'    encoded_payload = self.decompress_payload(compressed_payload)\n'
b'  File "/home/circleci/repo/p2p/protocol.py", line 130, in decompress_payload\n'
b'    return snappy.decompress(raw_payload)\n'
b'  File "/home/circleci/repo/.tox/py36-long_run_integration/lib/python3.6/site-packages/snappy/snappy.py", line 92, in uncompress\n'
b'    return _uncompress(data)\n'
b'snappy.CompressedLengthError: Can not calculate uncompressed length\x1b[0m\n'
```

### How can it be fixed

Need to look into it. /cc @Bhargavasomu

**Comment by Bhargavasomu** [comment]
@cburgdorf can you please tell me more details as in 
* The command which you used when this came up
* Roughly the time after which you saw this exception.

Thankyou.

**Comment by cburgdorf** [comment]
@Bhargavasomu This has been caught in one of our 90 second runs with `--ropsten`. You'll find it [here](https://circleci.com/gh/ethereum/trinity/12338). Sorry, should have included that right from the start.

**Comment by Bhargavasomu** [comment]
@cburgdorf this error is not occurring on master (Ran the tests **Thrice** myself). Could you please link me the `PR` which triggered this `error`?

**Comment by pipermerriam** [comment]
@cburgdorf maybe we can alter those tests to dump `DEBUG` logs to the terminal on failure.

**Comment by carver** [comment]
> @cburgdorf maybe we can alter those tests to dump `DEBUG` logs to the terminal on failure.

Should be as straightforward as `pytest ... --log-level=DEBUG`

**Comment by pipermerriam** [comment]
Alternate would be to actually `cat` the logfile on failure which might be a bit nicer to look at.

**Comment by carver** [comment]
Just reproduced in #504

https://circleci.com/gh/ethereum/trinity/25078?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Yeah, it will depend on connecting to a particular kind of peer, so probably the most important step is to add a test that simulates the bad peer. (which will be useful in many ways)

Copied out the full log:
```
Successfully installed trinity-0.1.0a23
py37-wheel-cli run-test: commands[3] | pytest tests/integration/ -k trinity_cli
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-4.4.0, py-1.8.0, pluggy-0.9.0
cachedir: .tox/py37-wheel-cli/.pytest_cache
rootdir: /home/circleci/repo, inifile: pytest.ini
plugins: asyncio-0.10.0
collected 19 items / 2 deselected / 17 selected                                

tests/integration/test_trinity_cli.py .............F...                  [100%]

=================================== FAILURES ===================================
________________________ test_does_not_throw[command4] _________________________

async_process_runner = <trinity.tools.async_process_runner.AsyncProcessRunner object at 0x7f9143c90a20>
command = ('trinity', '--ropsten', '--tx-pool')

    @pytest.mark.parametrize(
        'command',
        (
            # mainnet
            ('trinity',),
            ('trinity', '--tx-pool',),
            ('trinity', '--sync-mode=light',),
            # ropsten
            ('trinity', '--ropsten',),
            ('trinity', '--ropsten', '--tx-pool',),
            ('trinity', '--sync-mode=light', '--ropsten',),
        )
    )
    @pytest.mark.asyncio
    async def test_does_not_throw(async_process_runner, command):
        # This is our last line of defence. This test basically observes the first
        # 20 seconds of the Trinity boot process and fails if Trinity logs any exceptions
>       await run_command_and_detect_errors(async_process_runner, command, 20)

async_process_runner = <trinity.tools.async_process_runner.AsyncProcessRunner object at 0x7f9143c90a20>
command    = ('trinity', '--ropsten', '--tx-pool')

tests/integration/test_trinity_cli.py:158: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

async_process_runner = <trinity.tools.async_process_runner.AsyncProcessRunner object at 0x7f9143c90a20>
command = ('trinity', '--ropsten', '--tx-pool'), time = 20

    async def run_command_and_detect_errors(async_process_runner, command, time):
        """
        Run the given ``command`` on the given ``async_process_runner`` for ``time`` seconds and
        throw an Exception in case any unresolved Exceptions are detected in the output of the command.
        """
        lines_since_error = 0
        await async_process_runner.run(command, timeout_sec=time)
        async for line in async_process_runner.stderr:
    
            # We detect errors by some string at the beginning of the Traceback and keep
            # counting lines from there to be able to read and report more valuable info
            if "Traceback (most recent call last)" in line and lines_since_error == 0:
                lines_since_error = 1
            elif lines_since_error > 0:
                lines_since_error += 1
    
            # Keep on listening for output for a maxmimum of 100 lines after the error
            if lines_since_error >= 100:
                break
    
        if lines_since_error > 0:
>           raise Exception("Exception during Trinity boot detected")
E           Exception: Exception during Trinity boot detected

async_process_runner = <trinity.tools.async_process_runner.AsyncProcessRunner object at 0x7f9143c90a20>
command    = ('trinity', '--ropsten', '--tx-pool')
line       = '  return f(*args, **kwds)\n'
lines_since_error = 100
time       = 20

tests/integration/helpers.py:22: Exception
----------------------------- Captured stdout call -----------------------------
b'    INFO  04-16 22:53:51               trinity  \n'
b'      ______     _       _ __       \n'
b'     /_  __/____(_)___  (_) /___  __\n'
b'      / / / ___/ / __ \\/ / __/ / / /\n'
b'     / / / /  / / / / / / /_/ /_/ / \n'
b'    /_/ /_/  /_/_/ /_/_/\\__/\\__, /  \n'
b'                           /____/   \n'
b'    INFO  04-16 22:53:51               trinity  Started main process (pid=2680)\n'
b'    INFO  04-16 22:53:51               trinity  Trinity/0.1.0a23/linux/cpython3.7.3\n'
b'    INFO  04-16 22:53:51               trinity  Trinity DEBUG log file is created at /tmp/pyt--circleci/0/test_does_not_throw_command4_0/t/ropsten/logs-eth1/trinity.log\n'
b'    INFO  04-16 22:53:51               trinity  Started DB server process (pid=2693)\n'
b'    INFO  04-16 22:53:52               trinity  Started networking process (pid=2699)\n'
b'    INFO  04-16 22:53:52  BasePlugin#JSON-RPC API  Plugin started: JSON-RPC API (pid=2700)\n'
b'    INFO  04-16 22:53:52  BasePlugin#Discovery  Plugin started: Discovery (pid=2701)\n'
b'    INFO  04-16 22:53:53     DiscoveryProtocol  Preferred peers: (<Node(0x053d2f57829e5785d10697fa6c5333e4d98cc564dbadd87805fd4fedeb09cbcb642306e3a73bd4191b27f821fb442fcf964317d6a520b29651e7dd09d1beb0ec@79.98.29.154:30303)>, <Node(0x94c15d1b9e2fe7ce56e458b9a3b672ef11894ddedd0c6f247e0f1d3487f52b66208fb4aeb8179fce6e3a749ea93ed147c37976d67af557508d199d9594c35f09@192.81.208.223:30303)>, <Node(0xa147a3adde1daddc0d86f44f1a76404914e44cee018c26d49248142d4dc8a9fb0e7dd14b5153df7e60f23b037922ae1f33b8f318844ef8d2b0453b9ab614d70d@72.36.89.11:30303)>, <Node(0xd8714127db3c10560a2463c557bbe509c99969078159c69f9ce4f71c2cd1837bcd33db3b9c3c3e88c971b4604bbffa390a0a7f53fc37f122e2e6e0022c059dfd@51.15.217.106:30303)>, <Node(0xefc75f109d91cdebc62f33be992ca86fce2637044d49a954a8bdceb439b1239afda32e642456e9dfd759af5b440ef4d8761b9bda887e2200001c5f3ab2614043@34.228.166.142:30303)>, <Node(0xc8b9ec645cd7fe570bc73740579064c528771338c31610f44d160d2ae63fd00699caa163f84359ab268d4a0aed8ead66d7295be5e9c08b0ec85b0198273bae1f@178.62.246.6:30303)>, <Node(0x7a34c02d5ef9de43475580cbb88fb492afb2858cfc45f58cf5c7088ceeded5f58e65be769b79c31c5ae1f012c99b3e9f2ea9ef11764d553544171237a691493b@35.227.38.243:30303)>, <Node(0xbbb3ad8be9684fa1d67ac057d18f7357dd236dc01a806fef6977ac9a259b352c00169d092c50475b80aed9e28eff12d2038e97971e0be3b934b366e86b59a723@81.169.153.213:30303)>, <Node(0x30b7ab30a01c124a6cceca36863ece12c4f5fa68e3ba9b0b51407ccc002eeed3b3102d20a88f1c1d3c3154e2449317b8ef95090e77b312d5cc39354f86d5d606@52.176.7.10:30303)>, <Node(0x02508da84b37a1b7f19f77268e5b69acc9e9ab6989f8e5f2f8440e025e633e4277019b91884e46821414724e790994a502892144fc1333487ceb5a6ce7866a46@54.175.255.230:30303)>, <Node(0x0eec3472a46f0b637045e41f923ce1d4a585cd83c1c7418b183c46443a0df7405d020f0a61891b2deef9de35284a0ad7d609db6d30d487dbfef72f7728d09ca9@181.168.193.197:30303)>, <Node(0x643c31104d497e3d4cd2460ff0dbb1fb9a6140c8bb0fca66159bbf177d41aefd477091c866494efd3f1f59a0652c93ab2f7bb09034ed5ab9f2c5c6841aef8d94@34.198.237.7:30303)>)\n'
b'    INFO  04-16 22:53:53     DiscoveryProtocol  bootnode: enode://30b7ab30...86d5d606@52.176.7.10:30303\n'
b'    INFO  04-16 22:53:53     DiscoveryProtocol  bootnode: enode://865a6325...8aa7349c@52.176.100.77:30303\n'
b'    INFO  04-16 22:53:53     DiscoveryProtocol  bootnode: enode://6332792c...b16b0b0f@52.232.243.152:30303\n'
b'    INFO  04-16 22:53:53     DiscoveryProtocol  bootnode: enode://94c15d1b...94c35f09@192.81.208.223:30303\n'
b'    INFO  04-16 22:53:53              Endpoint  EventBus Endpoint discovery connecting to other Endpoint bjson-rpc-api\n'
b'    INFO  04-16 22:53:53             IPCServer  IPC started at: /tmp/pyt--circleci/0/test_does_not_throw_command4_0/t/ropsten/ipcs-eth1/jsonrpc.ipc\n'
b'    INFO  04-16 22:53:53              Endpoint  EventBus Endpoint bjson-rpc-api connecting to other Endpoint discovery\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n"
b'  return f(*args, **kwds)\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/rlp/sedes/raw.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\n"
b'  from collections import Sequence\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/rlp/lazy.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\n"
b'  from collections import Iterable, Sequence\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/eth_keys/datatypes.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\n"
b'  class BaseKey(ByteString, collections.Hashable):\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/jsonschema/compat.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\n"
b'  from collections import MutableMapping, Sequence  # noqa\n'
b'    INFO  04-16 22:53:53              Endpoint  EventBus Endpoint discovery connecting to other Endpoint networking\n'
b'    INFO  04-16 22:53:53              Endpoint  EventBus Endpoint bjson-rpc-api connecting to other Endpoint networking\n'
b'    INFO  04-16 22:53:53              Endpoint  EventBus Endpoint networking connecting to other Endpoint discovery\n'
b'    INFO  04-16 22:53:53              Endpoint  EventBus Endpoint networking connecting to other Endpoint bjson-rpc-api\n'
b'    INFO  04-16 22:53:53   BasePlugin#TxPlugin  Plugin started: TxPlugin\n'
b'    INFO  04-16 22:53:53  BasePlugin#Syncer Plugin  Plugin started: Syncer Plugin\n'
b'    INFO  04-16 22:53:53            FullServer  Running server...\n'
b'    INFO  04-16 22:53:53           UPnPService  Setting up NAT portmap...\n'
b'    INFO  04-16 22:53:53                TxPool  Running Tx Pool\n'
b'    INFO  04-16 22:53:53  FastThenFullChainSyncer  Starting fast-sync; current head: <BlockHeader #0 41941023>\n'
b'    INFO  04-16 22:53:58           UPnPService  No UPNP-enabled devices found\n'
b'    INFO  04-16 22:53:58   FastChainBodySyncer  blks=0     txs=0      bps=0    tps=0     elapsed=5.0  head=#0 4194..4a2d  age=49y3m3w\n'
b'    INFO  04-16 22:53:58            FullServer  enode://3b62d1db6691fe29758bcb82c2f5250109676a69e40cf0f4def2b6dba59da2a2a6fe43cba53142e8f1b8124860872c1b07f3f56bc204f812842122ff6115c18e@0.0.0.0:30303\n'
b'    INFO  04-16 22:53:58            FullServer  network: 3\n'
b'    INFO  04-16 22:53:58            FullServer  peers: max_peers=25\n'
b'    INFO  04-16 22:53:58           ETHPeerPool  Connected peers: 0 inbound, 0 outbound\n'
b'    INFO  04-16 22:53:58           ETHPeerPool  Peer subscribers: 5, longest queue: TxPool(0)\n'
b'    INFO  04-16 22:54:03   FastChainBodySyncer  blks=0     txs=0      bps=0    tps=0     elapsed=5.0  head=#0 4194..4a2d  age=49y3m3w\n'
b'\x1b[1m\x1b[31m   ERROR  04-16 22:54:04           ETHPeerPool  Unexpected error during auth/p2p handshake with <Node(0x865a63255b3bb68023b6bffd5095118fcc13e79dcf014fe4e47e065c350c7cc72af2e53eff895f11ba1bbb6a2b33271c1116ee870f266618eadfc2e78aa7349c@52.176.100.77:30303)>\n'
b'Traceback (most recent call last):\n'
b'  File "/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/p2p/peer_pool.py", line 279, in connect\n'
b'    peer = await self.wait(handshake(remote, self.get_peer_factory()))\n'
b'  File "/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/p2p/cancellable.py", line 20, in wait\n'
b'    return await self.wait_first(awaitable, token=token, timeout=timeout)\n'
b'  File "/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/p2p/cancellable.py", line 42, in wait_first\n'
b'    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)\n'
b'  File "/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/cancel_token/token.py", line 152, in cancellable_wait\n'
b'    return done.pop().result()\n'
b'  File "/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/p2p/peer.py", line 128, in handshake\n'
b'    await peer.do_sub_proto_handshake()\n'
b'  File "/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/p2p/peer.py", line 318, in do_sub_proto_handshake\n'
b'    cmd, msg = await self.read_msg()\n'
b'  File "/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/p2p/peer.py", line 457, in read_msg\n'
b'    decoded_msg = cast(Dict[str, Any], cmd.decode(msg))\n'
b'  File "/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/p2p/p2p_proto.py", line 78, in decode\n'
b'    raw_decoded = cast(Dict[str, int], super().decode(data))\n'
b'  File "/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/p2p/protocol.py", line 123, in decode\n'
b'    encoded_payload = self.decompress_payload(compressed_payload)\n'
b'  File "/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/p2p/protocol.py", line 130, in decompress_payload\n'
b'    return snappy.decompress(raw_payload)\n'
b'  File "/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/snappy/snappy.py", line 92, in uncompress\n'
b'    return _uncompress(data)\n'
b'snappy.CompressedLengthError: Can not calculate uncompressed length\x1b[0m\n'
b'\x1b[1m\x1b[33m WARNING  04-16 22:54:04           ETHPeerPool  Task <coroutine object BasePeerPool.maybe_connect_more_peers at 0x7f12544e83c8> finished unexpectedly: Can not calculate uncompressed length\x1b[0m\n'
b'    INFO  04-16 22:54:04               trinity  Shutting down Trinity (Node finished unexpectedly)\n'
b"    INFO  04-16 22:54:04         PluginManager  Shutting down PluginManager with scope <class 'trinity.extensibility.plugin_manager.MainAndIsolatedProcessScope'>\n"
b'    INFO  04-16 22:54:04           ETHPeerPool  Stopping all peers ...\n'
b'    INFO  04-16 22:54:04         PluginManager  Stopping plugin: JSON-RPC API\n'
b'    INFO  04-16 22:54:04         PluginManager  Stopping plugin: Discovery\n'
b'    INFO  04-16 22:54:04         PluginManager  Sent SIGINT to process 2700, waiting 10 seconds for it to terminate\n'
b'    INFO  04-16 22:54:04         PluginManager  Sent SIGINT to process 2701, waiting 10 seconds for it to terminate\n'
b'\x1b[1m\x1b[31m   ERROR  04-16 22:54:04               asyncio  Task exception was never retrieved\n'
b'future: <Task finished coro=<<async_generator_asend without __name__>()> exception=StopAsyncIteration()>\n'
b'StopAsyncIteration\x1b[0m\n'
b'\x1b[1m\x1b[31m   ERROR  04-16 22:54:04               asyncio  Task exception was never retrieved\n'
b'future: <Task finished coro=<<async_generator_asend without __name__>()> exception=StopAsyncIteration()>\n'
b'StopAsyncIteration\x1b[0m\n'
b'\x1b[1m\x1b[31m   ERROR  04-16 22:54:04               asyncio  Task exception was never retrieved\n'
b'future: <Task finished coro=<<async_generator_asend without __name__>()> exception=StopAsyncIteration()>\n'
b'StopAsyncIteration\x1b[0m\n'
b'    INFO  04-16 22:54:04            FullServer  Closing server...\n'
b'\x1b[1m\x1b[31m   ERROR  04-16 22:54:04               asyncio  Task exception was never retrieved\n'
b'future: <Task finished coro=<<async_generator_asend without __name__>()> exception=StopAsyncIteration()>\n'
b'StopAsyncIteration\x1b[0m\n'
b'\x1b[1m\x1b[33m WARNING  04-16 22:54:04  ETHHeaderChainSyncer  Tried to cancel <trinity.protocol.eth.sync.ETHHeaderChainSyncer object at 0x7f125c07bcf8>, but it was already cancelled\x1b[0m\n'
b'\x1b[1m\x1b[31m   ERROR  04-16 22:54:04  BasePlugin#Syncer Plugin  Sync ended unexpectedly. Shutting down trinity\x1b[0m\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n"
b'  return f(*args, **kwds)\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/rlp/sedes/raw.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\n"
b'  from collections import Sequence\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/rlp/lazy.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\n"
b'  from collections import Iterable, Sequence\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/eth_keys/datatypes.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\n"
b'  class BaseKey(ByteString, collections.Hashable):\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/jsonschema/compat.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\n"
b'  from collections import MutableMapping, Sequence  # noqa\n'
b'\x1b[1m\x1b[31m   ERROR  04-16 22:54:04               asyncio  Task exception was never retrieved\n'
b'future: <Task finished coro=<<async_generator_asend without __name__>()> exception=StopAsyncIteration()>\n'
b'StopAsyncIteration\x1b[0m\n'
b'\x1b[1m\x1b[31m   ERROR  04-16 22:54:04               asyncio  Task exception was never retrieved\n'
b'future: <Task finished coro=<<async_generator_asend without __name__>()> exception=StopAsyncIteration()>\n'
b'StopAsyncIteration\x1b[0m\n'
b'    INFO  04-16 22:54:04     DiscoveryProtocol  Bootstrapping cancelled: Cancellation requested by DiscoveryBootstrapService token\n'
b'    INFO  04-16 22:54:04     DiscoveryProtocol  stopping discovery\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n"
b'  return f(*args, **kwds)\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/rlp/sedes/raw.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\n"
b'  from collections import Sequence\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/rlp/lazy.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\n"
b'  from collections import Iterable, Sequence\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/eth_keys/datatypes.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\n"
b'  class BaseKey(ByteString, collections.Hashable):\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/jsonschema/compat.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\n"
b'  from collections import MutableMapping, Sequence  # noqa\n'
b'    INFO  04-16 22:54:04         PluginManager  Process 2700 has already terminated\n'
b'    INFO  04-16 22:54:04         PluginManager  Process 2701 has already terminated\n'
b'    INFO  04-16 22:54:04         PluginManager  Process 2700 has already terminated\n'
b'    INFO  04-16 22:54:04         PluginManager  Process 2701 has already terminated\n'
b'    INFO  04-16 22:54:04         PluginManager  Successfully stopped plugin: JSON-RPC API\n'
b'    INFO  04-16 22:54:04         PluginManager  Successfully stopped plugin: Discovery\n'
b'    INFO  04-16 22:54:06               trinity  Sent SIGINT to process 2699, waiting 10 seconds for it to terminate\n'
b'\x1b[1m\x1b[33m WARNING  04-16 22:54:06              FullNode  Tried to cancel <trinity.nodes.full.FullNode object at 0x7f125d623898>, but it was already cancelled\x1b[0m\n'
b"    INFO  04-16 22:54:06         PluginManager  Shutting down PluginManager with scope <class 'trinity.extensibility.plugin_manager.SharedProcessScope'>\n"
b'    INFO  04-16 22:54:06         PluginManager  Stopping plugin: Syncer Plugin\n'
b'    INFO  04-16 22:54:06         PluginManager  Stopping plugin: TxPlugin\n'
b'    INFO  04-16 22:54:06         PluginManager  Successfully stopped plugin: Syncer Plugin\n'
b'    INFO  04-16 22:54:06         PluginManager  Successfully stopped plugin: TxPlugin\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n"
b'  return f(*args, **kwds)\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/rlp/sedes/raw.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\n"
b'  from collections import Sequence\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/rlp/lazy.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\n"
b'  from collections import Iterable, Sequence\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/eth_keys/datatypes.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\n"
b'  class BaseKey(ByteString, collections.Hashable):\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/site-packages/jsonschema/compat.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\n"
b'  from collections import MutableMapping, Sequence  # noqa\n'
b"/home/circleci/repo/.tox/py37-wheel-cli/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n"
b'  return f(*args, **kwds)\n'
----------------------------- Captured stderr call -----------------------------
Exception ignored in: <function _releaseLock at 0x7f914c026048>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 226, in _releaseLock
    _lock.release()
RuntimeError: cannot release un-acquired lock
Ignoring exception from logging atfork <LogCaptureHandler (NOTSET)> release method: cannot release un-acquired lock
Ignoring exception from logging atfork <LogCaptureHandler (NOTSET)> release method: cannot release un-acquired lock
Ignoring exception from logging atfork <_StderrHandler <_io.FileIO name=9 mode='rb+' closefd=True> (WARNING)> release method: cannot release un-acquired lock
========================== slowest 50 test durations ===========================
30.05s call     tests/integration/test_trinity_cli.py::test_logger[command1-False]
20.10s call     tests/integration/test_trinity_cli.py::test_does_not_throw[command0]
20.10s call     tests/integration/test_trinity_cli.py::test_does_not_throw[command1]
20.09s call     tests/integration/test_trinity_cli.py::test_does_not_throw[command2]
20.07s call     tests/integration/test_trinity_cli.py::test_does_not_throw[command5]
20.05s call     tests/integration/test_trinity_cli.py::test_does_not_throw[command3]
19.52s call     tests/integration/test_trinity_cli.py::test_full_boot[command0]
17.08s call     tests/integration/test_trinity_cli.py::test_web3[command0]
16.89s call     tests/integration/test_trinity_cli.py::test_txpool_full_boot[command0]
16.44s call     tests/integration/test_trinity_cli.py::test_does_not_throw[command4]
15.81s call     tests/integration/test_trinity_cli.py::test_logger[command0-True]
13.77s call     tests/integration/test_trinity_cli.py::test_light_boot[command0]
10.08s call     tests/integration/test_trinity_cli.py::test_txpool_deactivated[command0]
4.07s call     tests/integration/test_trinity_cli.py::test_txpool_full_boot[command1]
3.39s call     tests/integration/test_trinity_cli.py::test_full_boot[command1]
3.33s call     tests/integration/test_trinity_cli.py::test_txpool_deactivated[command1]
3.27s call     tests/integration/test_trinity_cli.py::test_light_boot[command1]
0.04s setup    tests/integration/test_trinity_cli.py::test_txpool_full_boot[command1]
0.03s teardown tests/integration/test_trinity_cli.py::test_web3[command0]
0.03s setup    tests/integration/test_trinity_cli.py::test_full_boot[command1]

(0.00 durations hidden.  Use -vv to show these durations.)
============= 1 failed, 16 passed, 2 deselected in 255.14 seconds ==============
ERROR: InvocationError for command /home/circleci/repo/.tox/py37-wheel-cli/bin/pytest tests/integration/ -k trinity_cli (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py37-wheel-cli: commands failed
Exited with code 1
```

**Comment by pipermerriam** [comment]
```
   ERROR  05-09 15:34:40           ETHPeerPool  Unexpected error during auth/p2p handshake with <Node(0x1cafcf5336ce162dbf515b271dc557389da16e19ed2de2f5be1e9e47832aadd41b778e52f48d4cbc4b9fbe704f319d5db3493eccf1fff61fa8352a9387454160@54.169.189.50:30303)>
Traceback (most recent call last):
  File "/home/piper/projects/trinity/p2p/peer_pool.py", line 330, in connect
    peer = await self.wait(handshake(remote, self.get_peer_factory()))
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/home/piper/projects/trinity/p2p/peer.py", line 101, in handshake
    await peer.do_sub_proto_handshake()
  File "/home/piper/projects/trinity/p2p/peer.py", line 269, in do_sub_proto_handshake
    cmd, msg = await self.read_msg()
  File "/home/piper/projects/trinity/p2p/peer.py", line 371, in read_msg
    decoded_msg = cast(Dict[str, Any], cmd.decode(msg))
  File "/home/piper/projects/trinity/p2p/p2p_proto.py", line 74, in decode
    raw_decoded = cast(Dict[str, int], super().decode(data))
  File "/home/piper/projects/trinity/p2p/protocol.py", line 134, in decode
    encoded_payload = self.decompress_payload(compressed_payload)
  File "/home/piper/projects/trinity/p2p/protocol.py", line 141, in decompress_payload
    return snappy.decompress(raw_payload)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/snappy/snappy.py", line 92, in uncompress
    return _uncompress(data)
snappy.CompressedLengthError: Can not calculate uncompressed length
```

Just got same error.
