### ISSUE TITLE
Duplicate task error

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#357]
* py-evm Version: x.x.x
* OS: osx/linux/win
* Python Version (python --version):
* Environment (output of `pip freeze`):

### What is wrong?

```
   ERROR  03-02 20:48:48  ETHHeaderChainSyncer  Unexpected error in <trinity.protocol.eth.sync.ETHHeaderChainSyncer object at 0x7f727c861da0>, exiting
Traceback (most recent call last):
  File "/home/piper/projects/trinity/p2p/service.py", line 101, in run
    await self._run()
  File "/home/piper/projects/trinity/trinity/sync/common/headers.py", line 782, in _run
    await self.wait(self._build_skeleton())
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/home/piper/projects/trinity/trinity/sync/common/headers.py", line 796, in _build_skeleton
    await self._full_skeleton_sync(syncer)
  File "/home/piper/projects/trinity/trinity/sync/common/headers.py", line 876, in _full_skeleton_sync
    skeleton_syncer.peer,
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/home/piper/projects/trinity/trinity/sync/common/headers.py", line 553, in schedule_segment
    (parent_header, gap_length, skeleton_peer),
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/home/piper/projects/trinity/trinity/_utils/datastructures.py", line 159, in add
    f"Duplicate tasks detected: {already_pending!r} are already present in the queue"
eth_utils.exceptions.ValidationError: Duplicate tasks detected: {(<BlockHeader #7286730 6086b5f2>, 192, ETHPeer <Node(0x56693080998880e202be3f140438b8b0e57015daa0b1bc12e5d8d51c52d1583eb8428d1749006b8db6c157aae33850fba54c436db0832ac15f9b13aa8d5b0076@127.0.0.1:46548)>)} are already present in the queue
```

Full DEBUG logs: https://gist.github.com/pipermerriam/77d4d82700e32c371ed90c004c5ee93a

### How can it be fixed

Haven't investigated.

**Comment by pipermerriam** [comment]
Had a thought.  In theory, when trinity crashes we could pull the recent DEBUG logs from the logfiles for something like the last 5 minutes and write them to a bug-report file and then dump some info to the console about where that file can be found to make reporting these types of things easier.
