### ISSUE TITLE
Unclean shutdowns

### ISSUE THREAD

**Issue by lithp** [ethereum/trinity#373]
* py-evm Version: 0e389db67b671d51d56c35837f496e03bd088e75
* Python Version (python --version): 3.7.2

### What is wrong?

I think everyone is already aware of this issue, just opening it to have a record somewhere and have somewhere to track progress.

Every time I ctrl-c out of trinity I'm faced with a LOT of output:

```
^C    INFO  03-06 17:13:36               trinity  Shutting down Trinity (CTRL+C / Keyboard Interrupt)
    INFO  03-06 17:13:36         PluginManager  Shutting down PluginManager with scope <class 'trinity.extensibility.plugin_manager.MainAndIsolatedProcessScope'>
    INFO  03-06 17:13:36         PluginManager  Stopping plugin: JSON-RPC API
    INFO  03-06 17:13:36         PluginManager  Stopping plugin: Discovery
Process SpawnProcess-3:
    INFO  03-06 17:13:36         PluginManager  Sent SIGINT to process 21158, waiting 10 seconds for it to terminate
    INFO  03-06 17:13:36         PluginManager  Sent SIGINT to process 21207, waiting 10 seconds for it to terminate
   ERROR  03-06 17:13:36               asyncio  Task exception was never retrieved
future: <Task finished coro=<<async_generator_asend without __name__>()> exception=StopAsyncIteration()>
StopAsyncIteration
StopAsyncIteration
   ERROR  03-06 17:13:36               asyncio  Task exception was never retrieved
future: <Task finished coro=<<async_generator_asend without __name__>()> exception=StopAsyncIteration()>
StopAsyncIteration
StopAsyncIteration
   ERROR  03-06 17:13:36               asyncio  Task exception was never retrieved
future: <Task finished coro=<<async_generator_asend without __name__>()> exception=StopAsyncIteration()>
StopAsyncIteration
StopAsyncIteration
    INFO  03-06 17:13:36     DiscoveryProtocol  stopping discovery
Traceback (most recent call last):
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/process.py", line 300, in _bootstrap
    util._exit_function()
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/util.py", line 299, in _exit_function
    _run_finalizers(0)
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/util.py", line 265, in _run_finalizers
    finalizer()
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/util.py", line 189, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/managers.py", line 848, in _decref
    conn = _Client(token.address, authkey=authkey)
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/connection.py", line 498, in Client
    answer_challenge(c, authkey)
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/connection.py", line 741, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
   ERROR  03-06 17:13:36               asyncio  Task exception was never retrieved
future: <Task finished coro=<<async_generator_asend without __name__>()> exception=StopAsyncIteration()>
StopAsyncIteration
StopAsyncIteration
   ERROR  03-06 17:13:36               asyncio  Task exception was never retrieved
future: <Task finished coro=<<async_generator_asend without __name__>()> exception=StopAsyncIteration()>
StopAsyncIteration
StopAsyncIteration
    INFO  03-06 17:13:36           ETHPeerPool  Stopping all peers ...
    INFO  03-06 17:13:36            FullServer  Closing server...
 WARNING  03-06 17:13:36  ETHHeaderChainSyncer  Tried to cancel <trinity.protocol.eth.sync.ETHHeaderChainSyncer object at 0x7fddc8511048>, but it was already cancelled
    INFO  03-06 17:13:36         PluginManager  Shutting down PluginManager with scope <class 'trinity.extensibility.plugin_manager.SharedProcessScope'>
    INFO  03-06 17:13:36         PluginManager  Stopping plugin: Syncer Plugin
    INFO  03-06 17:13:36         PluginManager  Successfully stopped plugin: Syncer Plugin
   ERROR  03-06 17:13:36               futures  exception calling callback for <Future at 0x7fddd1281208 state=finished raised ConnectionResetError>
Traceback (most recent call last):
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/managers.py", line 796, in _callmethod
    kind, result = conn.recv()
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "uvloop/loop.pyx", line 1258, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 603, in uvloop.loop.Loop._call_soon
  File "uvloop/loop.pyx", line 607, in uvloop.loop.Loop._call_soon_handle
  File "uvloop/loop.pyx", line 636, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
Traceback (most recent call last):
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/managers.py", line 796, in _callmethod
    kind, result = conn.recv()
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/home/brian/.pyenv/versions/3.7.0/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "uvloop/loop.pyx", line 1258, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 603, in uvloop.loop.Loop._call_soon
  File "uvloop/loop.pyx", line 607, in uvloop.loop.Loop._call_soon_handle
  File "uvloop/loop.pyx", line 636, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
    INFO  03-06 17:13:36         PluginManager  Process 21158 has already terminated
    INFO  03-06 17:13:36         PluginManager  Process 21207 has already terminated
    INFO  03-06 17:13:36         PluginManager  Process 21158 has already terminated
    INFO  03-06 17:13:36         PluginManager  Process 21207 has already terminated
    INFO  03-06 17:13:36         PluginManager  Successfully stopped plugin: JSON-RPC API
    INFO  03-06 17:13:36         PluginManager  Successfully stopped plugin: Discovery
    INFO  03-06 17:13:36               trinity  networking process (pid=21156) terminated
    INFO  03-06 17:13:36               trinity  DB process (pid=21151) terminated
 WARNING  03-06 17:13:36               trinity  Removed dangling IPC socket file  /home/brian/.local/share/trinity/mainnet/ipcs-eth1/bjson-rpc-api.ipc
Trinity shutdown complete (CTRL+C / Keyboard Interrupt)
```

This is not a nice user experience!

**Comment by cburgdorf** [comment]
Yep, ugly. If we ever get rid of all of them, we should add a new test to our CLI tests that sends a `CTRL+C` and scans for exceptions in the output.

Linking #330 here as it fixes the `StopAsyncIteration` errors. However, it's probably not the right approach and we haven't been able yet to come up with a test case that clearly isolates the issue so that we can compare approaches against it. I'm currently busy elsewhere and anyone who cares for nice puzzles is free to pick it up. :smile:

**Comment by pipermerriam** [comment]
>  If we ever get rid of all of them, we should add a new test to our CLI tests that sends a CTRL+C and scans for exceptions in the output.

@cburgdorf you could add that today with a `pytest.mark.xfail` so it's ready to go **and** it will start failing as soon as we actually fix them, forcing us to switch that test on.

**Comment by cburgdorf** [comment]
@pipermerriam Ha! I've never thought about using `xfail` like that. Clever!

**Comment by gsalgado** [comment]
`DiscoveryService` is now a trio component and no longer uses the multiprocessing package, plus I've never seen this myself, so closing for now
