### ISSUE TITLE
AF_UNIX path too long

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/trinity#404]
* py-evm Version: py-evm==0.2.0a42
* OS: osx
* Python Version (python --version): Python 3.7.0
* Environment (output of `pip freeze`):

### What is wrong?

To reproduce

```
pytest -s tests/integration/test_trinity_cli.py::test_web3[command0]
```

Error message
```

tests/integration/test_trinity_cli.py b'    INFO  03-15 12:37:40               trinity  \n'
b'      ______     _       _ __       \n'
b'     /_  __/____(_)___  (_) /___  __\n'
b'      / / / ___/ / __ \\/ / __/ / / /\n'
b'     / / / /  / / / / / / /_/ /_/ / \n'
b'    /_/ /_/  /_/_/ /_/_/\\__/\\__, /  \n'
b'                           /____/   \n'
b'    INFO  03-15 12:37:40               trinity  Started main process (pid=49940)\n'
b'    INFO  03-15 12:37:40               trinity  Trinity/0.1.0a23/darwin/cpython3.7.0\n'
b'    INFO  03-15 12:37:40               trinity  Trinity DEBUG log file is created at /private/var/folders/cb/yk2xzls57qg9f5d18hps4q8w0000gn/T/pyt--liangcc/54/test_web3_command0_0/t/mainnet/logs-eth1/trinity.log\n'
b'Traceback (most recent call last):\n'
b'  File "/usr/local/var/pyenv/versions/3.7.0/envs/py-evm/bin/trinity", line 11, in <module>\n'
b"    load_entry_point('trinity', 'console_scripts', 'trinity')()\n"
b'  File "/Users/liangcc/projects/EAPL/eth2.0s/trinity/trinity/main.py", line 85, in main\n'
b'    main_entry(trinity_boot, APP_IDENTIFIER_ETH1, get_all_plugins(), (Eth1AppConfig,))\n'
b'  File "/Users/liangcc/projects/EAPL/eth2.0s/trinity/trinity/bootstrap.py", line 203, in main_entry\n'
b'    main_endpoint.start_serving_nowait(main_connection_config)\n'
b'  File "/usr/local/var/pyenv/versions/3.7.0/envs/py-evm/lib/python3.7/site-packages/lahja/endpoint.py", line 156, in start_serving_nowait\n'
b'    self._create_external_api(self._ipc_path)\n'
b'  File "/usr/local/var/pyenv/versions/3.7.0/envs/py-evm/lib/python3.7/site-packages/lahja/endpoint.py", line 231, in _create_external_api\n'
b'    server = manager.get_server()   # type: ignore\n'
b'  File "/usr/local/var/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/managers.py", line 505, in get_server\n'
b'    self._authkey, self._serializer)\n'
b'  File "/usr/local/var/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/managers.py", line 145, in __init__\n'
b'    self.listener = Listener(address=address, backlog=16)\n'
b'  File "/usr/local/var/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/connection.py", line 438, in __init__\n'
b'    self._listener = SocketListener(address, family, backlog)\n'
b'  File "/usr/local/var/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/connection.py", line 581, in __init__\n'
b'    self._socket.bind(address)\n'
b'OSError: AF_UNIX path too long\n'
b''
F

======================================================================== FAILURES ========================================================================
__________________________________________________________________ test_web3[command0] ___________________________________________________________________

command = ('trinity',), async_process_runner = <trinity.tools.async_process_runner.AsyncProcessRunner object at 0x10e1a7860>

    @pytest.mark.parametrize(
        'command',
        (
            ('trinity', ),
        )
    )
    @pytest.mark.asyncio
    async def test_web3(command, async_process_runner):
        await async_process_runner.run(command, timeout_sec=20)
>       assert await contains_all(async_process_runner.stderr, {
            "Started DB server process",
            "Started networking process",
            "IPC started at",
        })
E       assert False

async_process_runner = <trinity.tools.async_process_runner.AsyncProcessRunner object at 0x10e1a7860>
command    = ('trinity',)

tests/integration/test_trinity_cli.py:121: AssertionError
```

### How can it be fixed

Not investigate hard yet.

**Comment by pipermerriam** [comment]
Unix has a maximum path length for sockets.  We've encountered this before.  Take a look at the line that shows the logfile path

```
/private/var/folders/cb/yk2xzls57qg9f5d18hps4q8w0000gn/T/pyt--liangcc/54/test_web3_command0_0/t/
```

This code is supposed to keep that path short:  https://github.com/ethereum/trinity/blob/40c3ffbbf2ebeafefd31dc9e753c85d1480e3ceb/tests/conftest.py#L77-L102

But it appears to not be working correctly for whatever your environment is producing.

**Comment by ralexstokes** [comment]
i'll just +1 that i also saw this when i was sorting through some strange CI failure.

the obvious difference is that @ChihChengLiang and i are running this on mac os. can't remember if i have seen this on `circleci.com` or not but i suppose not.

**Comment by pipermerriam** [comment]
We should setup some smoke tests on CircleCI for OSX since I'm pretty sure they offer it as an environment we can test against.

**Comment by webknjaz** [comment]
FTR: https://github.com/agronholm/anyio/pull/42/files#diff-f0c1c7497545019b8489fa8bc06be6cdR208
