### ISSUE TITLE
Wrong Pong can crash discovery

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#484]
### What is wrong?

Ran into this error today

```
58437-   ERROR  04-05 12:42:07               asyncio  Exception in callback UDPTransport._on_read_ready
58438-handle: <Handle UDPTransport._on_read_ready created at /home/ubuntu/trinity/trinity/plugins/builtin/peer_discovery/plugin.py:178>
58439-source_traceback: Object created at (most recent call last):
58440-  File "<string>", line 1, in <module>
58441-  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
58442-    exitcode = _main(fd)
58443-  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 118, in _main
58444-    return self._bootstrap()
58445-  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
58446-    self.run()
58447-  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
58448-    self._target(*self._args, **self._kwargs)
58449-  File "/home/ubuntu/trinity/trinity/extensibility/plugin.py", line 338, in _prepare_start
58450-    self.do_start()
58451-  File "/home/ubuntu/trinity/trinity/plugins/builtin/peer_discovery/plugin.py", line 178, in do_start
58452-    loop.run_forever()
58453-Traceback (most recent call last):
58454-  File "uvloop/cbhandles.pyx", line 69, in uvloop.loop.Handle._run
58455-  File "uvloop/handles/udp.pyx", line 64, in uvloop.loop.UDPTransport._on_read_ready
58456-  File "/home/ubuntu/trinity/p2p/discovery.py", line 441, in datagram_received
58457-    self.receive(address, cast(bytes, data))
58458-  File "/home/ubuntu/trinity/p2p/discovery.py", line 478, in receive
58459-    handler(node, payload, message_hash)
58460-  File "/home/ubuntu/trinity/p2p/discovery.py", line 483, in recv_pong_v4
58461:    self.logger.debug2('<<< pong (v4) from %s (token == %s)', node, encode_hex(token))
58462:  File "/home/ubuntu/trinity/venv/lib/python3.6/site-packages/eth_utils/hexadecimal.py", line 22, in encode_hex
58463-    raise TypeError("Value must be an instance of str or unicode")
58464-TypeError: Value must be an instance of str or unicode

```

### How can it be fixed

Fill this in if you know how to fix it.

**Comment by pipermerriam** [comment]
I think this is from us not using any sedes when we decode RLP messages but instead just do a plain `rlp.decode`.  While we expect the token to be a `bytes`, this would allow someone to craft a message that decodes to a `list` in any position.

Assuming this is correct, we should use proper `sedes` classes for decoding **or** apply some basic type validation to the decoded values.  We *may* have to do the later since the discovery messages are allowed to have extra fields which are silently discarded and I don't know if that functionality can be supported with `rlp.Serializable`.
