### ISSUE TITLE
Beam sync crash: access headers before set

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#722]
### What is wrong?

Beam sync crash!

```
   DEBUG  06-14 08:20:18      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x9ea6@35.226.70.19)>
   DEBUG  06-14 08:20:18        SkeletonSyncer  During header sync launch, skipping over (192) already stored headers 7948845-7949036: <BlockHeader #7948845 29f8b7de>..<BlockHeader #7949036 50d22972>
   DEBUG  06-14 08:20:18        SkeletonSyncer  Canonical head updated while finding new head from ETHPeer <Node(0x9ea6@35.226.70.19)>, returning old <BlockHeader #7949036 50d22972> instead
   DEBUG  06-14 08:20:18        SkeletonSyncer  Requsting chain of headers from ETHPeer <Node(0x9ea6@35.226.70.19)> starting at #7949229
   DEBUG  06-14 08:20:18  ETHHeaderChainSyncer  Skeleton syncer asserts that parent (f7b2..121a) of the first header (<BlockHeader #7949036 50d22972>) is already present
    INFO  06-14 08:20:18     HeaderOnlyPersist  Imported 582 headers in 0.12 seconds, new head: <BlockHeader #7952216 fe67db75>
    INFO  06-14 08:20:18     HeaderOnlyPersist  Imported 194 headers in 0.03 seconds, new head: <BlockHeader #7952410 910bd2b9>
    INFO  06-14 08:20:18     HeaderOnlyPersist  Imported 1 headers in 0.03 seconds, new head: <BlockHeader #7952410 910bd2b9>
   DEBUG  06-14 08:20:19      HeaderMeatSyncer  Header Skeleton Gaps: active=5 queued=25 max=50
   DEBUG  06-14 08:20:19        SkeletonSyncer  Requsting chain of headers from ETHPeer <Node(0x9ea6@35.226.70.19)> starting at #7949230
   DEBUG  06-14 08:20:19      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x9ea6@35.226.70.19)>
   DEBUG  06-14 08:20:19        SkeletonSyncer  Requsting chain of headers from ETHPeer <Node(0x9ea6@35.226.70.19)> starting at #7954081
   DEBUG  06-14 08:20:19      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0xb045@46.105.118.30)>
   DEBUG  06-14 08:20:19      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0xaa12@94.130.68.239)>
   DEBUG  06-14 08:20:19      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x8826@104.248.251.159)>
    INFO  06-14 08:20:19     HeaderOnlyPersist  Imported 194 headers in 0.06 seconds, new head: <BlockHeader #7952604 4714fa4e>
   DEBUG  06-14 08:20:19        SkeletonSyncer  Got new header bones from ETHPeer <Node(0x9ea6@35.226.70.19)>: <BlockHeader #7949229 ba32431f>-<BlockHeader #7957184 333b1d1e>
   DEBUG  06-14 08:20:19        SkeletonSyncer  Requsting chain of headers from ETHPeer <Node(0x9ea6@35.226.70.19)> starting at #7957376
    INFO  06-14 08:20:19     HeaderOnlyPersist  Imported 582 headers in 0.22 seconds, new head: <BlockHeader #7953186 914f788b>
   DEBUG  06-14 08:20:19      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x9ea6@35.226.70.19)>
    INFO  06-14 08:20:19        SkeletonSyncer  Got no new headers from ETHPeer <Node(0x9ea6@35.226.70.19)>, exiting skeleton sync
   DEBUG  06-14 08:20:19        SkeletonSyncer  Requsting chain of headers from ETHPeer <Node(0x9ea6@35.226.70.19)> starting at #7957185
    INFO  06-14 08:20:19     HeaderOnlyPersist  Imported 194 headers in 0.11 seconds, new head: <BlockHeader #7953380 369c4681>
   DEBUG  06-14 08:20:20      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0xaa12@94.130.68.239)>
   DEBUG  06-14 08:20:20        SkeletonSyncer  Requsting chain of headers from ETHPeer <Node(0x9ea6@35.226.70.19)> starting at #7957274
   DEBUG  06-14 08:20:20      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0xb045@46.105.118.30)>
   DEBUG  06-14 08:20:20      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x8826@104.248.251.159)>
   DEBUG  06-14 08:20:20      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x9ea6@35.226.70.19)>
    INFO  06-14 08:20:20     HeaderOnlyPersist  Imported 388 headers in 0.07 seconds, new head: <BlockHeader #7953768 1660be86>
    INFO  06-14 08:20:20        SkeletonSyncer  Got no new headers from ETHPeer <Node(0x9ea6@35.226.70.19)>, exiting skeleton sync
    INFO  06-14 08:20:20        SkeletonSyncer  Skeleton ETHPeer <Node(0x9ea6@35.226.70.19)> stopped responding, waiting for sync to complete
    INFO  06-14 08:20:20     HeaderOnlyPersist  Imported 506 headers in 0.10 seconds, new head: <BlockHeader #7954274 86f37bbe>
   DEBUG  06-14 08:20:20      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0xaa12@94.130.68.239)>
   DEBUG  06-14 08:20:20      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x9ea6@35.226.70.19)>
   DEBUG  06-14 08:20:20      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x8826@104.248.251.159)>
    INFO  06-14 08:20:20     HeaderOnlyPersist  Imported 194 headers in 0.03 seconds, new head: <BlockHeader #7954274 86f37bbe>
   DEBUG  06-14 08:20:20      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0xb045@46.105.118.30)>
    INFO  06-14 08:20:20     HeaderOnlyPersist  Imported 582 headers in 0.01 seconds, new head: <BlockHeader #7954274 86f37bbe>
   DEBUG  06-14 08:20:20      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x9ea6@35.226.70.19)>
   DEBUG  06-14 08:20:20      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0xaa12@94.130.68.239)>
    INFO  06-14 08:20:20     HeaderOnlyPersist  Imported 388 headers in 0.05 seconds, new head: <BlockHeader #7954274 86f37bbe>
   DEBUG  06-14 08:20:20      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0xb045@46.105.118.30)>
    INFO  06-14 08:20:20        SkeletonSyncer  Skeleton ETHPeer <Node(0x9ea6@35.226.70.19)> emitted all headers
   DEBUG  06-14 08:20:20        SkeletonSyncer  <trinity.sync.common.headers.SkeletonSyncer object at 0x7f8940797d68> had nothing left to do, ceasing operation...
   DEBUG  06-14 08:20:20        SkeletonSyncer  Waiting for tasks (1): [<Task pending coro=<SkeletonSyncer._display_stats() running at /home/piper/projects/trinity/p2p/service.py:150> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f899c3d4e88>()]>>]
   DEBUG  06-14 08:20:20        SkeletonSyncer  All tasks finished
   DEBUG  06-14 08:20:20        SkeletonSyncer  <trinity.sync.common.headers.SkeletonSyncer object at 0x7f8940797d68> halted cleanly
    INFO  06-14 08:20:20  ETHHeaderChainSyncer  Skeleton sync with ETHPeer <Node(0x9ea6@35.226.70.19)> ended
   DEBUG  06-14 08:20:20      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x9ea6@35.226.70.19)>
   DEBUG  06-14 08:20:20      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x9ea6@35.226.70.19)>
   DEBUG  06-14 08:20:20      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0xaa12@94.130.68.239)>
   DEBUG  06-14 08:20:20      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x8826@104.248.251.159)>
   DEBUG  06-14 08:20:20      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0xb045@46.105.118.30)>
    INFO  06-14 08:20:20     HeaderOnlyPersist  Imported 776 headers in 0.02 seconds, new head: <BlockHeader #7954274 86f37bbe>
    INFO  06-14 08:20:20     HeaderOnlyPersist  Imported 388 headers in 0.02 seconds, new head: <BlockHeader #7954274 86f37bbe>
   DEBUG  06-14 08:20:20      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x9ea6@35.226.70.19)>
    INFO  06-14 08:20:21     HeaderOnlyPersist  Imported 194 headers in 0.01 seconds, new head: <BlockHeader #7954274 86f37bbe>
   DEBUG  06-14 08:20:21      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0xaa12@94.130.68.239)>
   DEBUG  06-14 08:20:21      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x9ea6@35.226.70.19)>
    INFO  06-14 08:20:21     HeaderOnlyPersist  Imported 194 headers in 0.04 seconds, new head: <BlockHeader #7954274 86f37bbe>
   DEBUG  06-14 08:20:21      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0xb045@46.105.118.30)>
   DEBUG  06-14 08:20:21      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x8826@104.248.251.159)>
    INFO  06-14 08:20:21     HeaderOnlyPersist  Imported 582 headers in 0.03 seconds, new head: <BlockHeader #7954274 86f37bbe>
   DEBUG  06-14 08:20:21      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x9ea6@35.226.70.19)>
   DEBUG  06-14 08:20:21      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0xaa12@94.130.68.239)>
    INFO  06-14 08:20:21     HeaderOnlyPersist  Imported 386 headers in 0.05 seconds, new head: <BlockHeader #7954274 86f37bbe>
   DEBUG  06-14 08:20:21      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0xb045@46.105.118.30)>
   DEBUG  06-14 08:20:21      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x8826@104.248.251.159)>
   DEBUG  06-14 08:20:21      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x9ea6@35.226.70.19)>
   DEBUG  06-14 08:20:21      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0xaa12@94.130.68.239)>
   DEBUG  06-14 08:20:21      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x8826@104.248.251.159)>
   DEBUG  06-14 08:20:21      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0xb045@46.105.118.30)>
   DEBUG  06-14 08:20:21      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x9ea6@35.226.70.19)>
   DEBUG  06-14 08:20:22      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0x9ea6@35.226.70.19)>
   DEBUG  06-14 08:20:22      HeaderMeatSyncer  Requesting 192 headers from ETHPeer <Node(0xaa12@94.130.68.239)>
    INFO  06-14 08:20:22     HeaderOnlyPersist  Imported 76 headers in 0.03 seconds, new head: <BlockHeader #7954350 7a8aa9f1>
   DEBUG  06-14 08:20:22     HeaderOnlyPersist  <coroutine object HeaderOnlyPersist._persist_headers at 0x7f899e37b728> finished while <trinity.sync.beam.chain.HeaderOnlyPersist object at 0x7f899e3624a8> is still running, terminating as well
   DEBUG  06-14 08:20:22     HeaderOnlyPersist  Cancelling <trinity.sync.beam.chain.HeaderOnlyPersist object at 0x7f899e3624a8>
[1m[33m WARNING  06-14 08:20:22     HeaderOnlyPersist  Task <coroutine object HeaderOnlyPersist._persist_headers at 0x7f899e37b780> finished unexpectedly: b'\x82g\x87\xb7\x00\xd9\xb1x\xfc_<\xa9>\xff\xb1\xdc\x96\x8a\x7f\xeeK\xc8+\xb2\x83\x81\x82y\x8caiW'[0m
   DEBUG  06-14 08:20:22     HeaderOnlyPersist  Task failure traceback
Traceback (most recent call last):
  File "/home/piper/projects/trinity/p2p/service.py", line 150, in _run_task_wrapper
    await awaitable
  File "/home/piper/projects/trinity/p2p/service.py", line 169, in _run_daemon_task_wrapper
    await awaitable
  File "/home/piper/projects/trinity/trinity/sync/beam/chain.py", line 196, in _persist_headers
    async for headers in self._header_syncer.new_sync_headers(HEADER_QUEUE_SIZE_TARGET):
  File "/home/piper/projects/trinity/trinity/sync/common/headers.py", line 780, in new_sync_headers
    headers = await self.wait(self._stitcher.ready_tasks(max_batch_size))
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/home/piper/projects/trinity/trinity/_utils/datastructures.py", line 622, in ready_tasks
    self._prune_finished(task_id)
  File "/home/piper/projects/trinity/trinity/_utils/datastructures.py", line 698, in _prune_finished
    self._prune(root_task_id)
  File "/home/piper/projects/trinity/trinity/_utils/datastructures.py", line 703, in _prune
    del self._dependencies[prune_task_id]
KeyError: b'\x82g\x87\xb7\x00\xd9\xb1x\xfc_<\xa9>\xff\xb1\xdc\x96\x8a\x7f\xeeK\xc8+\xb2\x83\x81\x82y\x8caiW'
   DEBUG  06-14 08:20:22     HeaderOnlyPersist  <trinity.sync.beam.chain.HeaderOnlyPersist object at 0x7f899e3624a8> finished: Cancellation requested by HeaderOnlyPersist:BeamSyncer:BeamSyncService:FullNode token
   DEBUG  06-14 08:20:22     HeaderOnlyPersist  <trinity.sync.beam.chain.HeaderOnlyPersist object at 0x7f899e3624a8> halted cleanly
[1m[31m   ERROR  06-14 08:20:22            BeamSyncer  Unexpected error in <trinity.sync.beam.chain.BeamSyncer object at 0x7f899e3ee748>, exiting
Traceback (most recent call last):
  File "/home/piper/projects/trinity/p2p/service.py", line 112, in run
    await self._run()
  File "/home/piper/projects/trinity/trinity/sync/beam/chain.py", line 124, in _run
    final_headers = self._header_persister.get_final_headers()
  File "/home/piper/projects/trinity/trinity/sync/beam/chain.py", line 274, in get_final_headers
    raise ValidationError("Must not try to access final headers before it has been set")
eth_utils.exceptions.ValidationError: Must not try to access final headers before it has been set[0m
   DEBUG  06-14 08:20:22            BeamSyncer  Waiting for child services: [<trinity.sync.beam.chain.MissingDataEventHandler object at 0x7f899e36a518>, <trinity.protocol.eth.sync.ETHHeaderChainSyncer object at 0x7f899e0ac898>, <trinity.sync.full.chain.RegularChainBodySyncer object at 0x7f899e36a940>]
   DEBUG  06-14 08:20:22  ETHHeaderChainSyncer  <trinity.protocol.eth.sync.ETHHeaderChainSyncer object at 0x7f899e0ac898> finished: Cancellation requested by BeamSyncer:BeamSyncService:FullNode token
   DEBUG  06-14 08:20:22  ETHHeaderChainSyncer  Waiting for child services: [<trinity.protocol.eth.monitors.ETHChainTipMonitor object at 0x7f899e357390>, <trinity.sync.common.headers.HeaderMeatSyncer object at 0x7f899e357b38>, <trinity.sync.common.headers.SkeletonSyncer object at 0x7f8940797d68>]
   DEBUG  06-14 08:20:22  MissingDataEventHandler  <trinity.sync.beam.chain.MissingDataEventHandler object at 0x7f899e36a518> finished: Cancellation requested by BeamSyncer:BeamSyncService:FullNode token
   DEBUG  06-14 08:20:22  MissingDataEventHandler  Waiting for tasks (3): [<Task pending coro=<MissingDataEventHandler._provide_missing_account_tries() running at /home/piper/projects/trinity/p2p/service.py:150> wait_for=<Future finished result=None>>, <Task pending coro=<MissingDataEventHandler._provide_missing_bytecode() running at /home/piper/projects/trinity/p2p/service.py:150> wait_for=<Future finished result=None>>, <Task pending coro=<MissingDataEventHandler._provide_missing_storage() running at /home/piper/projects/trinity/p2p/service.py:150> wait_for=<Future finished result=None>>]
   DEBUG  06-14 08:20:22  RegularChainBodySyncer  <trinity.sync.full.chain.RegularChainBodySyncer object at 0x7f899e36a940> finished: Cancellation requested by BeamSyncer:BeamSyncService:FullNode token
```

### How can it be fixed

Not sure, just documenting it for now.

**Comment by carver** [comment]
Closed by #731 -- looks like the first crash caused the second one.
