### ISSUE TITLE
docs build failing

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#805]
### What is wrong?

readthedocs build is failing, eg~
https://readthedocs.org/projects/trinity-client/builds/9381206/

Because:
```
Building wheels for collected packages: blspy
  Building wheel for blspy (setup.py): started
  Building wheel for blspy (setup.py): finished with status 'error'
  ERROR: Complete output from command /home/docs/checkouts/readthedocs.org/user_builds/trinity-client/envs/latest/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-57700gbe/blspy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4ppoyr_f --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "/tmp/pip-install-57700gbe/blspy/setup.py", line 22, in run
      out = subprocess.check_output(['cmake', '--version'])
    File "/home/docs/.pyenv/versions/3.6.8/lib/python3.6/subprocess.py", line 356, in check_output
      **kwargs).stdout
    File "/home/docs/.pyenv/versions/3.6.8/lib/python3.6/subprocess.py", line 423, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/home/docs/.pyenv/versions/3.6.8/lib/python3.6/subprocess.py", line 729, in __init__
      restore_signals, start_new_session)
    File "/home/docs/.pyenv/versions/3.6.8/lib/python3.6/subprocess.py", line 1364, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-57700gbe/blspy/setup.py", line 78, in <module>
      zip_safe=False,
    File "/home/docs/checkouts/readthedocs.org/user_builds/trinity-client/envs/latest/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/docs/.pyenv/versions/3.6.8/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/docs/.pyenv/versions/3.6.8/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/docs/.pyenv/versions/3.6.8/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/docs/checkouts/readthedocs.org/user_builds/trinity-client/envs/latest/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/home/docs/.pyenv/versions/3.6.8/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/docs/.pyenv/versions/3.6.8/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/docs/.pyenv/versions/3.6.8/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/docs/.pyenv/versions/3.6.8/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/docs/.pyenv/versions/3.6.8/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-57700gbe/blspy/setup.py", line 26, in run
      ", ".join(e.name for e in self.extensions))
  RuntimeError: CMake must be installed to build the following extensions: blspy
  ----------------------------------------
  ERROR: Failed building wheel for blspy
  Running setup.py clean for blspy
Failed to build blspy
```

### How can it be fixed

Some options:

- Don't install `blspy` for docs build
- Figure out how to add cmake to the readthedocs build environment

**Comment by cburgdorf** [comment]
We do have a standard way to respond to things that should be excluded from RTD.

https://github.com/ethereum/trinity/blob/4850957c0bbaf7dd27d31f21bb1ef96aea8aaa7e/setup.py#L122-L126

However, this one is more surprising. RTD only depends on `install_requires` which consists of `trinity`, `p2p`, `eth2`  as well as the `doc` extra.

I don't understand how `blspy` is pulled into this.

But I can confirm to get the same error even if I just run `pip install -e .[lint]`. So, this is not only our doc build failing but a more broader issue that will effect many people trying to install trinity.

**Comment by cburgdorf** [comment]
Oh, stupid me! Now I see it, `blspy` is not only in the `bls-bindings` extra but also in `eth2` which end up in the `install_requires`. Wondering if it should be dropped from `eth2` and only live in `bls-bindings`.

**Comment by cburgdorf** [comment]
This is the issue to track for a fix https://github.com/ethereum/trinity/pull/808

**Comment by carver** [comment]
Docs build now, since #808 was merged:
https://trinity-client.readthedocs.io/en/latest/release_notes.html#trinity-0-1-0-alpha-26-2019-07-16

**Comment by cburgdorf** [comment]
Reopening this. Turns out the docs build has been failing for the past 4 weeks and it looks like this is the commit that failed it https://github.com/ethereum/trinity/commit/b6ca964b0440d8608e94a60039e34d9ca3884749

Seems like `CMake` became a dependency again.
