### ISSUE TITLE
IncompleteReadError comes out of Transport/Multiplexer

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#871]
### What is wrong?

```
   ERROR  08-02 16:59:44               ETHPeer  Unexpected error in ETHPeer <Node(0xebbc1d05fec4e7e859fdea4f7ba8a4fe408eb289f74c4e7a8c2d35eaab60677f1bacd434cc2f151f9028c516d70b568d4d875af4f98399e4e6ac9f836b494a1b@178.62.196.234:30303)>, exiting
Traceback (most recent call last):
  File "/home/piper/projects/trinity/p2p/multiplexer.py", line 276, in multiplex
    yield
  File "/home/piper/projects/trinity/p2p/peer.py", line 371, in _run
    await self.cancellation()
  File "/home/piper/projects/trinity/p2p/service.py", line 344, in cancellation
    await self.wait(self.events.cancelled.wait())
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/cancel_token/token.py", line 150, in cancellable_wait
    "Cancellation requested by {} token".format(self.triggered_token)
cancel_token.exceptions.OperationCancelled: Cancellation requested by ETHPeer:ETHPeerPool:FullServer:FullNode token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/piper/projects/trinity/p2p/service.py", line 112, in run
    await self._run()
  File "/home/piper/projects/trinity/p2p/peer.py", line 371, in _run
    await self.cancellation()
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/home/piper/projects/trinity/p2p/multiplexer.py", line 281, in multiplex
    fut.result()
  File "/home/piper/projects/trinity/p2p/multiplexer.py", line 300, in _do_multiplexing
    async for protocol, cmd, msg in msg_stream:
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 66, in wait_iter
    timeout=timeout,
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/home/piper/projects/trinity/p2p/multiplexer.py", line 58, in stream_transport_messages
    raw_msg = await transport.recv(token)
  File "/home/piper/projects/trinity/p2p/transport.py", line 239, in recv
    header_data = await self.read(HEADER_LEN + MAC_LEN, token)
  File "/home/piper/projects/trinity/p2p/transport.py", line 233, in read
    raise PeerConnectionLost(repr(e))
p2p.exceptions.PeerConnectionLost: IncompleteReadError('0 bytes read on a total of 32 expected bytes',)
```

### How can it be fixed

Need to handle this somewhere....

Fundamental issue here is we need an error handling strategy for the multiplexer since it's a little awkward to wrap the whole `with multiplexer.multiplex()` block in a `try/except`.

Probably acceptable for the multiplexer to "close" the transport if this happens or even for the transport to close itself as part of raising this error.

**Comment by pipermerriam** [comment]
Another one:

```

   ERROR  08-03 09:50:19             Transport  Attempted to send msg with cmd id 1 to disconnected peer <p2p.transport.Transport object at 0x7fc12020f630>
   ERROR  08-03 09:50:19               ETHPeer  Unexpected error in ETHPeer <Node(0xe35a2cf2a2dfe4b686958ddfe0f5eb00fc5168308c30acefc950b72c09b6d3129d1c4cec377a8d6a2a1f58e20fe6ca2588f144ef70ab48a7916133bc1b9eb9eb@47.99.107.32:30305)>, exiting
Traceback (most recent call last):
  File "/home/piper/projects/trinity/p2p/multiplexer.py", line 276, in multiplex
    yield
  File "/home/piper/projects/trinity/p2p/peer.py", line 371, in _run
    await self.cancellation()
  File "/home/piper/projects/trinity/p2p/service.py", line 344, in cancellation
    await self.wait(self.events.cancelled.wait())
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/cancel_token/token.py", line 150, in cancellable_wait
    "Cancellation requested by {} token".format(self.triggered_token)
cancel_token.exceptions.OperationCancelled: Cancellation requested by ETHPeer:ETHPeerPool:FullServer:FullNode token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/piper/projects/trinity/p2p/service.py", line 112, in run
    await self._run()
  File "/home/piper/projects/trinity/p2p/peer.py", line 371, in _run
    await self.cancellation()
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/home/piper/projects/trinity/p2p/multiplexer.py", line 281, in multiplex
    fut.result()
  File "/home/piper/projects/trinity/p2p/multiplexer.py", line 300, in _do_multiplexing
    async for protocol, cmd, msg in msg_stream:
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 66, in wait_iter
    timeout=timeout,
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/home/piper/projects/trinity/p2p/multiplexer.py", line 58, in stream_transport_messages
    raw_msg = await transport.recv(token)
  File "/home/piper/projects/trinity/p2p/transport.py", line 252, in recv
    frame_data = await self.read(read_size + MAC_LEN, token)
  File "/home/piper/projects/trinity/p2p/transport.py", line 233, in read
    raise PeerConnectionLost(repr(e))
p2p.exceptions.PeerConnectionLost: ConnectionResetError(104, 'Connection reset by peer')
```

Basically the same exception, just a different inner exception class.
