### ISSUE TITLE
trinity raises KeyError occasionally while syncing with ropsten

### ISSUE THREAD

**Issue by voith** [ethereum/trinity#888]
* Trinity version: master
* OS: osx
* Python version (output of `python --version`): Python 3.7.4
* Environment (output of `pip freeze`):
```
aio-timers==0.0.1
aniso8601==6.0.0
appnope==0.1.0
argcomplete==1.10.0
asn1crypto==0.24.0
async-generator==1.10
async-lru==0.1.0
asyncio-cancel-token==0.1.0a2
attrdict==2.0.1
attrs==19.1.0
backcall==0.1.0
base58==1.0.3
bloom-filter==1.3
blspy==0.1.9
cached-property==1.5.1
cachetools==3.1.1
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
Click==7.0
coincurve==10.0.0
cryptography==2.6.1
cytoolz==0.10.0
decorator==4.4.0
eth-abi==1.3.0
eth-account==0.2.3
eth-bloom==1.0.3
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.1.2
eth-typing==2.1.0
eth-utils==1.6.4
graphene==2.1.7
graphql-core==2.2.1
graphql-relay==2.0.0
grpcio==1.22.0
grpcio-tools==1.22.0
hexbytes==0.2.0
idna==2.8
ifaddr==0.1.6
ipython==6.5.0
ipython-genutils==0.2.0
jedi==0.14.1
jsonschema==3.0.1
lahja==0.14.0
libp2p==0.0.1
lru-dict==1.1.6
lxml==4.4.0
multiaddr==0.0.8
mypy==0.720
mypy-extensions==0.4.1
netaddr==0.7.19
netdisco==2.6.0
netifaces==0.10.9
outcome==1.0.0
parsimonious==0.8.1
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
plyvel==1.0.5
promise==2.2.1
prompt-toolkit==1.0.16
protobuf==3.9.1
ptyprocess==0.6.0
py-ecc==1.7.1
py-evm==0.3.0a1
pycparser==2.19
pycryptodome==3.8.2
pyethash==0.1.27
Pygments==2.4.2
pymultihash==0.8.2
pyrsistent==0.15.4
pysha3==1.0.2
python-dateutil==2.8.0
python-snappy==0.5.4
requests==2.22.0
rlp==1.1.0
rpcudp==3.0.0
ruamel.yaml==0.15.98
Rx==1.6.1
simplegeneric==0.8.1
six==1.12.0
sniffio==1.1.0
sortedcontainers==2.1.0
SQLAlchemy==1.3.6
ssz==0.1.3
termcolor==1.1.0
toolz==0.10.0
traitlets==4.3.2
trie==1.4.0
-e git+git@github.com:voith/trinity.git@7c059cc4b083b8de5a5b16838331ff6690184c24#egg=trinity
trio==0.11.0
trio-typing==0.2.0
typed-ast==1.4.0
typing-extensions==3.7.4
u-msgpack-python==2.5.1
uPnPClient==0.0.8
urllib3==1.25.3
uvloop==0.11.2
varint==1.0.2
wcwidth==0.1.7
web3==4.4.1
websockets==5.0.1
zeroconf==0.23.0
```

### What is wrong?
while syncing with ropsten I occasionally get the following error:
`trinity --ropsten`
```
   ERROR  08-08 00:52:50               asyncio  Exception in callback UDPTransport._on_read_ready
handle: <Handle UDPTransport._on_read_ready>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 69, in uvloop.loop.Handle._run
  File "uvloop/handles/udp.pyx", line 64, in uvloop.loop.UDPTransport._on_read_ready
  File "/Users/voith/Projects/new-ethereum/trinity/p2p/discovery.py", line 448, in datagram_received
    self.receive(address, cast(bytes, data))
  File "/Users/voith/Projects/new-ethereum/trinity/p2p/discovery.py", line 463, in receive
    remote_pubkey, cmd_id, payload, message_hash = _unpack_v4(message)
  File "/Users/voith/Projects/new-ethereum/trinity/p2p/discovery.py", line 1261, in _unpack_v4
    cmd = CMD_ID_MAP[cmd_id]
KeyError: 5
```

### How can it be fixed

:information_desk_person:

**Comment by voith** [comment]
Looks like this got fixed in #1063
