### ISSUE TITLE
`TimeoutError` escaping during beam sync

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#903]
### What is wrong?

```
   ERROR  08-09 21:43:28               ETHPeer  Unexpected error in ETHPeer <Node(0x49a644c6acfa08fc3bb0f74ec9453a93e30664d3375bfa2114d630d27a4cec0d7bc8882ce351ceb538b35932bf5658d52853d9275efcc0643e50b5bb94b72b18@84.22.101.15:30303)>, exiting
Traceback (most recent call last):
  File "/home/piper/projects/trinity/p2p/multiplexer.py", line 299, in multiplex
    yield
  File "/home/piper/projects/trinity/p2p/peer.py", line 375, in _run
    await self.cancellation()
  File "/home/piper/projects/trinity/p2p/service.py", line 344, in cancellation
    await self.wait(self.events.cancelled.wait())
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/cancel_token/token.py", line 150, in cancellable_wait
    "Cancellation requested by {} token".format(self.triggered_token)
cancel_token.exceptions.OperationCancelled: Cancellation requested by ETHPeer:ETHPeerPool:FullServer:FullNode token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/piper/projects/trinity/p2p/service.py", line 112, in run
    await self._run()
  File "/home/piper/projects/trinity/p2p/peer.py", line 375, in _run
    await self.cancellation()
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/home/piper/projects/trinity/p2p/multiplexer.py", line 307, in multiplex
    fut.result()
  File "/home/piper/projects/trinity/p2p/multiplexer.py", line 326, in _do_multiplexing
    async for protocol, cmd, msg in msg_stream:
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 66, in wait_iter
    timeout=timeout,
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/home/piper/projects/trinity/p2p/multiplexer.py", line 59, in stream_transport_messages
    raw_msg = await transport.recv(token)
  File "/home/piper/projects/trinity/p2p/transport.py", line 239, in recv
    header_data = await self.read(HEADER_LEN + MAC_LEN, token)
  File "/home/piper/projects/trinity/p2p/transport.py", line 230, in read
    timeout=CONN_IDLE_TIMEOUT,
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/cancel_token/token.py", line 143, in cancellable_wait
    raise TimeoutError()
TimeoutError
```

### How can it be fixed

Add handling for it.

**Comment by pipermerriam** [comment]
cc @carver I'm curious for you to take a look at this and tell me what you think.

You'll see the error is coming out of `p2p.multiplexer.stream_transport_messages`

For some of these errors such as when when we lose our connection it makes sense for the whole thing to just shut down and for us to make a hard disconnect from the peer.

However, in this case, it's a little puzzling.  In theory, when we hit this timeout, what we should do is send a `Ping`.  However, the place where we want to handle and respond to that isn't currently able to catch and handle the message.

This has me thinking that the `Multiplexer` might need a way for the party that is *multiplexing* to provide an error handler which would be allowed to either handle it or let it bubble.  Curious to get your thoughts.  I think the same thing applies to #901 since we will want to send a `DisconnectReason.bad_protocol` and formally disconnect (which isn't currently really doable with the existing API)

**Comment by carver** [comment]
Yeah, I can imagine a scenario where we would want to propagate the timeout error to the caller within each stream (although I'm not sure the best way to accomplish that).

But in both of these scenarios the handler seems to semantically cross protocols:
- if a peer sends an invalid subprotocol message, we probably just want to disconnect from them completely
- if a peer has been silent for some extended period, we want to know if they are still responding, regardless of any subprotocol specifics

So yeah, handling it at the mux creation level seems to fit :+1:
