### ISSUE TITLE
Error escaping beam sync during speculative transaction execution.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#940]
### What is wrong?

Looks like a failure case that needs to be gracefully handled.

```
--- Logging error ---
Traceback (most recent call last):
  File "/home/piper/projects/trinity/trinity/sync/beam/importer.py", line 450, in _trigger_missing_state_downloads
    _, receipts, _ = vm.apply_all_transactions(transactions, unused_header)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/eth/vm/base.py", line 241, in apply_all_transactions
    transaction,
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/eth/vm/base.py", line 161, in apply_transaction
    computation = self.state.apply_transaction(transaction)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/eth/vm/forks/frontier/state.py", line 195, in apply_transaction
    return executor(transaction)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/eth/vm/state.py", line 325, in __call__
    self.validate_transaction(transaction)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/eth/vm/forks/frontier/state.py", line 50, in validate_transaction
    self.vm_state.validate_transaction(transaction)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/eth/vm/forks/homestead/state.py", line 20, in validate_transaction
    validate_homestead_transaction(self, transaction)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/eth/vm/forks/homestead/validation.py", line 23, in validate_homestead_transaction
    validate_frontier_transaction(state, transaction)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/eth/vm/forks/frontier/validation.py", line 23, in validate_frontier_transaction
    sender_balance,
eth_utils.exceptions.ValidationError: Sender b'\xba\x0b\xba{t\xf5}\x81\x83(J[@\x8d&\xc9o\x0fE\x0c' cannot afford txn gas 437500000000000 with account balance 433214653663105

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/logging/handlers.py", line 1395, in emit
    self.enqueue(self.prepare(record))
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/logging/handlers.py", line 1382, in prepare
    self.format(record)
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not list
Call stack:
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/concurrent/futures/thread.py", line 69, in _worker
    work_item.run()
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/piper/projects/trinity/trinity/sync/beam/importer.py", line 458, in _trigger_missing_state_downloads
    exc,
Message: 'Speculative transactions %d failed for %s after %.1fs: %s'
Arguments: ([<eth.vm.forks.petersburg.transactions.PetersburgTransaction object at 0x7fb8b00899e8>, <eth.vm.forks.petersburg.transactions.PetersburgTransaction object at 0x7fb8b0089ef0>, <eth.vm.forks.petersburg.transactions.PetersburgTransaction object at 0x7fb8b00895f8>, <eth.vm.forks.petersburg.transactions.PetersburgTransaction object at 0x7fb8b0089780>], <eth.rlp.headers.BlockHeader object at 0x7fb8a823e128>, 19.707478989032097, ValidationError("Sender b'\\xba\\x0b\\xba{t\\xf5}\\x81\\x83(J[@\\x8d&\\xc9o\\x0fE\\x0c' cannot afford txn gas 437500000000000 with account balance 433214653663105",))
```

### How can it be fixed

figure out graceful handling of the error.

**Comment by carver** [comment]
Fixed by #1035
