### ISSUE TITLE
tests in test_service_shutdown_utils.py get stuck

### ISSUE THREAD

**Issue by voith** [ethereum/trinity#980]
* Trinity version: 8570b61c8660fa7f7447e4fb22d7d995ca674bd9
* OS: osx & linux
* Python version (output of `python --version`): Python 3.7.4
* Environment (output of `pip freeze`): same as test env setup by tox

----

### What is wrong?
I noticed that while running `pytest tests/core/`, `test_service_shutdown_utils.py` would wait indefinitely.
If I run`test_service_shutdown_utils.py` separately then it passes. So I realized that it was a combination of certain tests that were causing the issue. I dug a little deeper and figured out that the tests causing the problem are:
https://github.com/ethereum/trinity/blob/8570b61c8660fa7f7447e4fb22d7d995ca674bd9/tests/core/task-queue-utils/test_ordered_task_preparation.py#L154
https://github.com/ethereum/trinity/blob/8570b61c8660fa7f7447e4fb22d7d995ca674bd9/tests/core/shutdown-utils/test_service_shutdown_utils.py#L41

The tests need to be run in the same order that I have mentioned above in order to reproduce the problem.

I extracted the code into a single file to reproduce the error:
```python
import asyncio
import multiprocessing
import os
import signal
from enum import Enum, auto
import pytest

from eth_utils import (
    ValidationError,
)
from eth_utils.toolz import (
    identity,
)

from p2p.service import BaseService

from trinity._utils.shutdown import (
    exit_with_services,
)
from trinity._utils.datastructures import (
    OrderedTaskPreparation,
)


class TwoPrereqs(Enum):
    Prereq1 = auto()
    Prereq2 = auto()


class SimpleService(BaseService):
    def __init__(self, ready_to_kill_event, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.ready_to_kill_event = ready_to_kill_event

    async def _run(self):
        self.ready_to_kill_event.set()
        await self.cancellation()


def run_service(ready_to_kill_event):
    loop = asyncio.get_event_loop()

    service = SimpleService(ready_to_kill_event, loop=loop)

    asyncio.ensure_future(service.run())
    asyncio.ensure_future(exit_with_services(service))

    loop.run_forever()
    loop.close()

    assert service.is_cancelled


def test_finish_same_task_twice():
    ti = OrderedTaskPreparation(TwoPrereqs, identity, lambda x: x - 1)
    ti.set_finished_dependency(1)
    ti.register_tasks((2, ))
    ti.finish_prereq(TwoPrereqs.Prereq1, (2,))
    with pytest.raises(ValidationError):
        ti.finish_prereq(TwoPrereqs.Prereq1, (2,))


@pytest.mark.parametrize('sig', (signal.SIGINT, signal.SIGTERM))
@pytest.mark.asyncio
async def test_exit_with_endpoind_and_services_facilitates_clean_shutdown(sig):
    ready_to_kill_event = multiprocessing.Event()
    proc = multiprocessing.Process(target=run_service, args=(ready_to_kill_event,))
    proc.start()

    ready_to_kill_event.wait()
    os.kill(proc.pid, sig)
    proc.join(timeout=1)

```
before running this test uninstall `pytest-randomly` so that the tests run in the order as written in the file(I tried other plugins like `pytest-ordering`, but they weren't working for some reason ).
- `pip uninstall pytest-randomly`
- run the tests in this file and you should be able to reproduce the error.
- You should see that the test waits indefinitely. 
----
### Some diagnosis
I used a remote debugger to see what the issue is:
https://github.com/ethereum/trinity/blob/8570b61c8660fa7f7447e4fb22d7d995ca674bd9/tests/core/shutdown-utils/test_service_shutdown_utils.py#L33
The above line gives the following error:
```
Process Process-1:
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 705, in uvloop.loop.Loop._add_reader
KeyError: 17

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/voith/Projects/new-ethereum/trinity/tests/core/shutdown-utils/test_service_shutdown_utils.py", line 33, in run_service
    loop.run_forever()
  File "uvloop/loop.pyx", line 1344, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 464, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 262, in uvloop.loop.Loop._recv_signals_start
  File "uvloop/loop.pyx", line 707, in uvloop.loop.Loop._add_reader
  File "uvloop/handles/poll.pyx", line 30, in uvloop.loop.UVPoll.new
  File "uvloop/handles/poll.pyx", line 18, in uvloop.loop.UVPoll._init
OSError: [Errno 9] Bad file descriptor
```
Becase the event lop fails to start, `ready_to_kill_event.wait()` waits indefinitely.

------

I had a look at a similar issue over [here](https://github.com/huge-success/sanic/issues/305).
But the fixes mentioned there didn't work for me or I didn't try hard enough.

### How can it be fixed
I don't know what the actual issue here is. I couldn't figure out what code in `test_finish_same_task_twice` is causing an issue for `test_exit_with_endpoind_and_services_facilitates_clean_shutdown` that cause the `uvloop` to fail.

**Comment by voith** [comment]
cc @pipermerriam. 
I'm not sure if this is an issue on OSX only and I have a faint memory that piper uses OSX. 
@carver Can you reproduce this on Linux? (Again I have a faint memory of Jason using Linux).
I don't know what Christoph and Brian use.
