### ISSUE TITLE
Multiplexer not handling PeerConnectionLost error

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#984]
### What is wrong?

I haven't figured out exactly what is happening but here is what I see:

```
DEBUG2  08-28 17:19:24             Transport  Waiting for 32 bytes from <Node(0xd4e4@172.33.1.6)> 
```

This eventually raises a `PeerConnectionLost` error which ends up not being properly handled. Trinity seems to sit idle from that point on.

After I `Control+C` Trinity, I get this traceback.

```
   ERROR  08-28 17:22:26               asyncio  Task exception was never retrieved
future: <Task finished coro=<<async_generator_asend without __name__>()> exception=StopAsyncIteration()>
StopAsyncIteration
   ERROR  08-28 17:22:26               asyncio  Task exception was never retrieved
future: <Task finished coro=<BasePeerFactory.handshake() done, defined at /home/cburgdorf/Documents/hacking/ef/trinity/p2p/peer.py:588> exception=PeerConnectionLost()>
Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/transport.py", line 230, in read
    timeout=CONN_IDLE_TIMEOUT,
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/usr/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 32 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/peer.py", line 600, in handshake
    token=self.cancel_token
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/peer.py", line 96, in handshake
    token=token,
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/handshake.py", line 303, in negotiate_protocol_handshakes
    in zip(selected_handshakers, selected_protocols)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/multiplexer.py", line 307, in multiplex
    fut.result()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/multiplexer.py", line 326, in _do_multiplexing
    async for protocol, cmd, msg in msg_stream:
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/cancellable.py", line 66, in wait_iter
    timeout=timeout,
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/multiplexer.py", line 58, in stream_transport_messages
    raw_msg = await transport.recv(token)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/transport.py", line 239, in recv
    header_data = await self.read(HEADER_LEN + MAC_LEN, token)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/transport.py", line 233, in read
    raise PeerConnectionLost from err
p2p.exceptions.PeerConnectionLost

```

My guess is that the `stream_transport_messages` dies in the background but I haven't got around figuring out more about it yet...

cc @pipermerriam 

### How can it be fixed

:policeman:

**Comment by cburgdorf** [comment]
Just noting that I can still reproduce this even after #1006 landed with my local parity node when the local parity node does not respond as expected.

```
   ERROR  08-30 10:37:17               asyncio  Task exception was never retrieved
future: <Task finished coro=<BasePeerFactory.handshake() done, defined at /home/cburgdorf/Documents/hacking/ef/trinity/p2p/peer.py:574> exception=PeerConnectionLost()>
Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/transport.py", line 240, in read
    timeout=CONN_IDLE_TIMEOUT,
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/usr/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 32 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/peer.py", line 586, in handshake
    token=self.cancel_token
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/peer.py", line 96, in handshake
    token=token,
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/handshake.py", line 309, in negotiate_protocol_handshakes
    in zip(selected_handshakers, selected_protocols)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/multiplexer.py", line 343, in multiplex
    fut.result()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/multiplexer.py", line 365, in _do_multiplexing
    async for protocol, cmd, msg in msg_stream:
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/cancellable.py", line 66, in wait_iter
    timeout=timeout,
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/cancellable.py", line 42, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/multiplexer.py", line 59, in stream_transport_messages
    raw_msg = await transport.recv(token)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/transport.py", line 265, in recv
    header_data = await self.read(HEADER_LEN + MAC_LEN, token)
  File "/home/cburgdorf/Documents/hacking/ef/trinity/p2p/transport.py", line 243, in read
    raise PeerConnectionLost from err
p2p.exceptions.PeerConnectionLost
```

**Comment by carver** [comment]
Maybe this was taken care of in #1545 or #1548 ?

**Comment by gsalgado** [comment]
This has resurfaced in https://github.com/ethereum/trinity/pull/1671 (https://circleci.com/gh/ethereum/trinity/211744?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by gsalgado** [comment]
But in #1671 it happens before a `Ctrl-C`

**Comment by pipermerriam** [comment]
Maybe I'm missing something but this looks like a legitimate exception that just needs to be properly handled at some layer.

**Comment by gsalgado** [comment]
> Maybe I'm missing something but this looks like a legitimate exception that just needs to be properly handled at some layer.

It's an asyncio warning about the exception not being retrieved from the task (either by calling its .result() or .exception() methods), not about the exception not being handled

**Comment by gsalgado** [comment]
May have been addressed by https://github.com/ethereum/trinity/pull/1671#discussion_r408910574, so closing for now
